/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_droidtv_euinstallersat_model_mwapi_SatInstaller */

#ifndef _Included_org_droidtv_euinstallersat_model_mwapi_SatInstaller
#define _Included_org_droidtv_euinstallersat_model_mwapi_SatInstaller
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    CreateInstance
 * Signature: (ILorg/droidtv/euinstallersat/model/mwapi/SatInstaller;)I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_CreateInstance
  (JNIEnv *, jobject, jint, jobject);

#if 0
/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    GetCurrentInstallationState
 * Signature: ()Lorg/droidtv/euinstallersat/model/mwapi/InstallationState;
 */
JNIEXPORT jobject JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_GetCurrentInstallationState
  (JNIEnv *, jobject);

#endif
/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    StartInstallation
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_StartInstallation
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    StopInstallation
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_StopInstallation
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    ResetInstallation
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_ResetInstallation
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    GetNumberOfTvChannelsFound
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_GetNumberOfTvChannelsFound
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    GetNumberofRadioChannelsFound
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_GetNumberofRadioChannelsFound
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    GetNumberOfTvChannelsRemoved
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_GetNumberOfTvChannelsRemoved
  (JNIEnv *, jobject,jint);

/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    GetNumberofRadioChannelsRemoved
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_GetNumberofRadioChannelsRemoved
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    GetSatelliteName
 * Signature: (I)Lorg/droidtv/euinstallersat/model/mwapi/SatelliteName;
 */
JNIEXPORT jstring JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_GetSatelliteName
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    GetNumberOfDigitalChannelsAdded
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_GetNumberOfDigitalChannelsAdded
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    GetNumberOfDigitalChannelsRemoved
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_GetNumberOfDigitalChannelsRemoved
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    GetNumberOfDigitalChannelsMoved
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_GetNumberOfDigitalChannelsMoved
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    IdentifyPackagesAvailable
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_IdentifyPackagesAvailable
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    GetTotalNumberOfPackagesFound
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_GetTotalNumberOfPackagesFound
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    InstallAddedSatellites
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_InstallAddedSatellites
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    ResetAddedSatellites
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_ResetAddedSatellites
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    RemoveSatelliteEntry
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_RemoveSatelliteEntry
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    GetSatelliteSignalStrength
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_GetSatelliteSignalStrength
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    GetSatelliteSignalQuality
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_GetSatelliteSignalQuality
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    LoadManualInstallationDefaultValues
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_LoadManualInstallationDefaultValues
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    StoreManualInstallationValues
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_StoreManualInstallationValues
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    GetAttribute
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_GetAttribute
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    SetAttribute
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_SetAttribute
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    GetScanProgressStatus
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_GetScanProgressStatus
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    EnableUnicable
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_EnableUnicable
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    StopSignalStrengthMeas
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_StopSignalStrengthMeas
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    GetSignalQuality
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_GetSignalQuality
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    StartSignalStrengthMeas
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_StartSignalStrengthMeas
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    GetSignalStrength
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_GetSignalStrength
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    StartPredefinedListCopy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_StartPredefinedListCopy
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    SetUserPackageIndex
 * Signature: (S)I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_SetUserPackageIndex
  (JNIEnv *, jobject, jshort);

/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    GetPackageByIndex
 * Signature: (I)Lorg/droidtv/euinstallersat/model/mwapi/HsvPackageStructure;
 */
JNIEXPORT jobject JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_GetPackageByIndex
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    GetUserPackageIndex
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_GetUserPackageIndex
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    GetInstalledSatellites
 * Signature: (I)Lorg/droidtv/euinstallersat/model/mwapi/HsvInstalledSatellites;
 */
JNIEXPORT jobject JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_GetInstalledSatellites
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    GetSITableIds
 * Signature: ()Lorg/droidtv/euinstallersat/model/mwapi/SITableIds;
 */
JNIEXPORT jobject JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_GetSITableIds
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    GetSIDetails
 * Signature: ()Lorg/droidtv/euinstallersat/model/mwapi/HsvSDMSIDataValues;
 */
JNIEXPORT jobject JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_GetSIDetails
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    GetPackageName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_GetPackageName
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    onScanAborted_JNICall
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_onScanAborted_1JNICall
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    onScanEnded_JNICall
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_onScanEnded_1JNICall
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    onScanningStandardDetected_JNICall
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_onScanningStandardDetected_1JNICall
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    onTuned_JNICall
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_onTuned_1JNICall
  (JNIEnv *, jobject, jint, jint);


/*
 * Class:	  org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:	  GetLnbSettings
 * Signature: ()[I
 */
JNIEXPORT jobject JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_GetLnbSettings
  (JNIEnv *, jobject,jint index);

/*
 * Class:	  org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:	  ResetLnbSettings
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_ResetLnbSettings
  (JNIEnv *, jobject);

/*
 * Class:	  org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:	  ResetToDefaultLnbSettings
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_ResetToDefaultLnbSettings
  (JNIEnv *, jobject);

/*
 * Class:	  org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:	  GetLNBType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_GetLNBType
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    SetBouquetIndex
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_SetBouquetIndex
  (JNIEnv *, jobject, jint);

/*
 * Class:	  org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:	  GetFirstInstalledChannel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_GetFirstInstalledChannel
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    SetLnbSettings
 * Signature: (Lorg/droidtv/euinstallersat/model/mwapi/LnbSettingsEntry;)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_SetLnbSettings
  (JNIEnv *, jobject,jint index, jobject);

/*
 * Class:	  org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:	  SaveSatelliteSettingsToPersistent
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_SaveSatelliteSettingsToPersistent
  (JNIEnv *, jobject);

/*
 * Class:	  org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:	  CommitSatelliteSettingsToPersistent
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_CommitSatelliteSettingsToPersistent
  (JNIEnv *, jobject);

/*
 * Class:	  org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:	  SetUnicableUBNumber
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_SetUnicableUBNumber
  (JNIEnv *, jobject, jint);



/*
 * Class:	  org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:	  SetUnicableUBNumberTuner2
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_SetUnicableUBNumberTuner2
  (JNIEnv *, jobject, jint);



/*
 * Class:	  org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:	  SetUnicableUBFreq
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_SetUnicableUBFreq
  (JNIEnv *, jobject, jint);

 /*
 * Class: org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method: UpdateConfigXmlStrings
 * Signature: (Ljava/lang/String;ILjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_UpdateConfigXmlStrings
  (JNIEnv *, jobject, jstring, jint, jstring, jint);


/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    asset_manager_init
 * Signature: (Lorg/droidtv/euinstallersat/model/mwapi/SatInstaller;)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_asset_1manager_1init
  (JNIEnv *, jobject, jobject);
  
  
 /*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    GetSatId
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_GetSatId
  (JNIEnv *, jobject, jint);

 /*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    GetLnbSettingsArray
 * Signature: (I)[Lorg/droidtv/euinstallersat/model/mwapi/HsvLnbSettings;
 */
JNIEXPORT jobjectArray JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_GetLnbSettingsArray
  (JNIEnv *, jobject, jint);
 
/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    GetDefaultValues
 * Signature: ()Lorg/droidtv/euinstallersat/model/mwapi/LnbSettingsEntry;
 */
JNIEXPORT jobject JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_GetDefaultValues
  (JNIEnv *, jobject,jint);
/*
* Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
* Method:    SetLnbSettingsviaIndex
* Signature: (ILorg/droidtv/euinstallersat/model/mwapi/LnbSettingsEntry;)V
*/

JNIEXPORT void JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_SetLnbSettingsviaIndex
  (JNIEnv *env, jobject obj,jint lnbIndex, jobject lnbsettings);


/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    OnOpSearchStatus
 * Signature: (jObject)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_OnOpSearchStatus
  (JNIEnv *env, jobject, jobject );
  
/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    OnOpStatusInfo
 * Signature: (jObject)V
 */

JNIEXPORT void JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_OnOpStatusInfo
  (JNIEnv *env, jobject, jobject );
  
/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    OnOpNIT
 * Signature: (jObject)V
 */

JNIEXPORT void JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_OnOpNIT
  (JNIEnv *env, jobject, jobject);

  /*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    OnOpTune
 * Signature: (jObject)V
 */

JNIEXPORT void JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_OnOpTune
  (JNIEnv *env, jobject, jobject);

/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    OnCAMStatusChanged
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_OnCAMStatusChanged
  (JNIEnv *env, jobject, jint );

/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    setConnectionType
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_setConnectionType
  (JNIEnv *env, jobject,jint,jint);  

 /*
 * Class:	  org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:	  GetCurrentInstallationState
 * Signature: ()I */

JNIEXPORT jint JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_GetCurrentInstallationState
(JNIEnv *env, jobject);
/*
 * Class:	  org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:	  GetCurrentInstallationMode
 * Signature: ()I */

JNIEXPORT jint JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_GetCurrentInstallationMode
(JNIEnv *env, jobject );
  

/* Class:	  org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:	  GetLnbType
 * Signature: (I)I

 * * */

JNIEXPORT jint JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_GetLnbType
(JNIEnv *env, jobject , jint );

/* Class:	  org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:	  getLnbStatus
 * Signature: (I)I

 * * */

JNIEXPORT jint JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_getLnbStatus
(JNIEnv *env,jobject,jint);

/* Class:	  org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:	  GetHighLoFreq
 * Signature: (I)I

 * * */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_GetHighLoFreq
(JNIEnv *env, jobject , jint );


/* Class:	  org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:	  GetLowLoFreq
 * Signature: (I)I

 * * */

JNIEXPORT jint JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_GetLowLoFreq
(JNIEnv *env, jobject , jint );



/* Class:	  org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:	  GetToneControl
 * Signature: (I)B

 * * */

JNIEXPORT jbyte JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_GetToneControl
(JNIEnv *env, jobject , jint);

/* Class:	  org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:	  GetLnbPower
 * Signature: (I)B

 * * */

JNIEXPORT jbyte JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_GetLnbPower
(JNIEnv *env, jobject , jint);

/* Class:	  org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:	  GetUserBand
 * Signature: (I)B

 * * */

JNIEXPORT jbyte JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_GetUserBand
(JNIEnv *env, jobject , jint);

/* Class:	  org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:	  GetUserFrequency
 * Signature: (I)I

 * * */

JNIEXPORT jint JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_GetUserFrequency
(JNIEnv *env, jobject , jint);





/* Class:	  org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:	  GetSatelliteId
 * Signature: (I)I

 * * */

JNIEXPORT jint JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_GetSatelliteId
(JNIEnv *env, jobject , jint);

/* Class:	  org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:	  GetUpdateInstallEnabled
 * Signature: (I)Z

 * * */

JNIEXPORT jboolean JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_GetUpdateInstallEnabled
(JNIEnv *env, jobject , jint);

/* Class:	  org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:	  SelectLNBForUpdate
 * Signature: (IZ)V

 * * */

JNIEXPORT void JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_SelectLNBForUpdate
(JNIEnv *env, jobject , jint, jboolean);

/* Class:	  org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:	  setLnbpower
 * Signature: (IB)V

 * * */

JNIEXPORT void JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_setLnbpower
(JNIEnv *env, jobject , jint,jbyte);

/* Class:	  org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:	  settotone
 * Signature: (IB)V

 * * */

JNIEXPORT void JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_settotone
(JNIEnv *env, jobject , jint,jbyte);

/* Class:	  org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:	  setlnbLowLoFrequency
 * Signature: (II)V

 * * */

JNIEXPORT void JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_setlnbLowLoFrequency
(JNIEnv *env, jobject , jint,jint);

/* Class:	  org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:	  setlnbHighLoFrequency
 * Signature: (II)V

 * * */

JNIEXPORT void JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_setlnbHighLoFrequency
(JNIEnv *env, jobject , jint,jint);



/* Class:	  org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:	  GetUserpackage
 * Signature: ()Z
 * * */
JNIEXPORT jboolean JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_GetUserpackage
(JNIEnv *env, jobject);

/* Class:	  org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:	  SetUnicableUBFreqTuner2
 * Signature: (II)V
 * * */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_SetUnicableUBFreqTuner2
(JNIEnv *env, jobject,jint,jint);

/* Class:	  org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:	  GetUnicableUBFreqTuner2
 * Signature: (I)I
 * * */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_GetUnicableUBFreqTuner2
(JNIEnv *env, jobject,jint );

  /*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    setPostCode
 * Signature: (ILjava/lang/String;)V
 */

JNIEXPORT void JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_setPostCode
  (JNIEnv *env, jobject, jint,jstring);


/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    GetNumberOfDatabaseRecords
 * Signature: (I)I
 */

JNIEXPORT jint JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_GetNumberOfDatabaseRecords
  (JNIEnv *env, jobject obj, jint TSDataOnly);  


/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    GetTvProviderBlobDataByIndex
 * Signature: (II)Lorg/droidtv/euinstallersat/model/mwapi/SatInstallerTvProviderData
 */

JNIEXPORT jobject JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_GetTvProviderBlobDataByIndex
  (JNIEnv *env, jobject obj, jint Index, jint TSDataOnly);  

/*
 * Class:	  org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:	  PopulateMW
 * Signature: (jObject)V
 */

JNIEXPORT void JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_PopulateMW
  (JNIEnv *env, jobject obj, jobject objTvpData, jint Clear);

/*
 * Class:	  org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:	  syncUniqueIdToMW
 * Signature: (jObject)V
 */

JNIEXPORT void JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_syncUniqueIdToMW
  (JNIEnv *env, jobject obj, jobject tvpDataObj);


/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    startTricolorRegionParsing
 * Signature: ()V
 */

JNIEXPORT void JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_startTricolorRegionParsing
  (JNIEnv *env, jobject);
  
/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    setTricolorRegionIndex
 * Signature: (I)V
 */

JNIEXPORT void JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_setTricolorRegionIndex
  (JNIEnv *env, jobject, jint);

/*
 * Class:     org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:    getTricolorRegionNames
 * Signature: ()[LJava.lang.String
 */
JNIEXPORT jobjectArray JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_getTricolorRegionNames
  (JNIEnv *env, jobject);

/* Class:	  org_droidtv_euinstallersat_model_mwapi_SatInstaller
 * Method:	  setDemuxHandle
 * Signature: (J)V

 * * */

JNIEXPORT void JNICALL Java_org_droidtv_euinstallersat_model_mwapi_SatInstaller_setDemuxHandle
(JNIEnv *env, jobject , jlong);


#ifdef __cplusplus
}
#endif
#endif
