#ifndef  _CHSVEUROPEINSTALLATION_MSORTROUTE_PRIV_H
#define  _CHSVEUROPEINSTALLATION_MSORTROUTE_PRIV_H 

#include <InfraGlobals.h>
#include <provreq.h>
#include <IHsvSortRoute.h>
#include <IHsvHybridPresetSort.h>
#include <IHsvCountryIds.h>
#include <IHsvEuropeDiversity2.h>
#include <IHsvInstallation2.h>
#include <IHsvTcSystemSettings.h>
#include <CTCMwBase.h>
class CHsvEuropeInstallation_mSortRoute_Priv;
#define CLASSSCOPE CHsvEuropeInstallation_mSortRoute_Priv::
#include "locals_mSortRoute.h"

class CHsvEuropeInstallation_mSortRoute_Priv : public CTCMwBase
{
public:
virtual ~CHsvEuropeInstallation_mSortRoute_Priv();

private:
void params__init(void);
private:
#define MEMBERVARS
#include "locals_mSortRoute.h"
#undef MEMBERVARS
//Provided interfaces
private:
IHsvSortRouteImpl(CHsvEuropeInstallation_mSortRoute_Priv,isortroute);
IHsvHybridPresetSortImpl(CHsvEuropeInstallation_mSortRoute_Priv,istubsort);
public:
ProvidesInterface<IHsvSortRoute>	isortroute;

ProvidesInterface<IHsvHybridPresetSort>	istubsort;

//Required interfaces
public:
RequiresInterface<IHsvCountryIds>	cids;
RequiresInterface<IHsvEuropeDiversity2>	eurdiv;
RequiresInterface<IHsvHybridPresetSort>	idbooksort;
RequiresInterface<IHsvHybridPresetSort>	idvbclitesort;
RequiresInterface<IHsvHybridPresetSort>	idvbcsort;
RequiresInterface<IHsvHybridPresetSort>	iblizoosort;
RequiresInterface<IHsvHybridPresetSort>	idvbtlitesort;
RequiresInterface<IHsvHybridPresetSort>	idvbtsort;
RequiresInterface<IHsvHybridPresetSort>	ifinsort;
RequiresInterface<IHsvHybridPresetSort>	inorsort;
RequiresInterface<IHsvHybridPresetSort>	itasort;
RequiresInterface<IHsvInstallation2>	rins;
RequiresInterface<IHsvTcSystemSettings>	sysset;
RequiresInterface<IHsvHybridPresetSort>	idvbtapmeasort;
RequiresInterface<IHsvHybridPresetSort>	idvbthungarysort;

public:
CHsvEuropeInstallation_mSortRoute_Priv():i__isortroute(this),i__istubsort(this)
{
isortroute	=	&i__isortroute;
istubsort	=	&i__istubsort;
module__init();
params__init();
}

};

#ifdef GENERATE__LEGACY__DEFINES
#define cids_iPresent() (cids.Present())
#define cids_CountryAustria	IHsvCountryIds_CountryAustria
#define cids_CountryBelgium	IHsvCountryIds_CountryBelgium
#define cids_CountryCroatia	IHsvCountryIds_CountryCroatia
#define cids_CountryCzechrep	IHsvCountryIds_CountryCzechrep
#define cids_CountryDenmark	IHsvCountryIds_CountryDenmark
#define cids_CountryFinland	IHsvCountryIds_CountryFinland
#define cids_CountryFrance	IHsvCountryIds_CountryFrance
#define cids_CountryGermany	IHsvCountryIds_CountryGermany
#define cids_CountryGreece	IHsvCountryIds_CountryGreece
#define cids_CountryHungary	IHsvCountryIds_CountryHungary
#define cids_CountryIreland	IHsvCountryIds_CountryIreland
#define cids_CountryItaly	IHsvCountryIds_CountryItaly
#define cids_CountryLuxembourg	IHsvCountryIds_CountryLuxembourg
#define cids_CountryNetherlands	IHsvCountryIds_CountryNetherlands
#define cids_CountryNorway	IHsvCountryIds_CountryNorway
#define cids_CountryPoland	IHsvCountryIds_CountryPoland
#define cids_CountryPortugal	IHsvCountryIds_CountryPortugal
#define cids_CountryRomania	IHsvCountryIds_CountryRomania
#define cids_CountryRussia	IHsvCountryIds_CountryRussia
#define cids_CountrySerbia	IHsvCountryIds_CountrySerbia
#define cids_CountrySlovakia	IHsvCountryIds_CountrySlovakia
#define cids_CountrySlovenia	IHsvCountryIds_CountrySlovenia
#define cids_CountrySpain	IHsvCountryIds_CountrySpain
#define cids_CountrySweden	IHsvCountryIds_CountrySweden
#define cids_CountrySwitzerland	IHsvCountryIds_CountrySwitzerland
#define cids_CountryTurkey	IHsvCountryIds_CountryTurkey
#define cids_CountryUK	IHsvCountryIds_CountryUK
#define cids_CountryOther	IHsvCountryIds_CountryOther
#define cids_CountryAustralia	IHsvCountryIds_CountryAustralia
#define cids_CountryEstonia	IHsvCountryIds_CountryEstonia
#define cids_CountryLithuania	IHsvCountryIds_CountryLithuania
#define cids_CountryLatvia	IHsvCountryIds_CountryLatvia
#define cids_CountryKazakhstan	IHsvCountryIds_CountryKazakhstan
#define cids_CountryBulgaria	IHsvCountryIds_CountryBulgaria
#define cids_CountryChina	IHsvCountryIds_CountryChina
#define cids_CountryUkraine	IHsvCountryIds_CountryUkraine
#define cids_CountryBrazil	IHsvCountryIds_CountryBrazil
#define cids_CountryArgentina	IHsvCountryIds_CountryArgentina
#define cids_CountryAlbania	IHsvCountryIds_CountryAlbania
#define cids_CountryArmenia	IHsvCountryIds_CountryArmenia
#define cids_CountryAzerbaijan	IHsvCountryIds_CountryAzerbaijan
#define cids_CountryBelarus	IHsvCountryIds_CountryBelarus
#define cids_CountryBosniaAndHerzegovina	IHsvCountryIds_CountryBosniaAndHerzegovina
#define cids_CountryGeorgia	IHsvCountryIds_CountryGeorgia
#define cids_CountryMontenegro	IHsvCountryIds_CountryMontenegro
#define cids_CountryIsrael	IHsvCountryIds_CountryIsrael
#define cids_CountryMacedoniafyrom	IHsvCountryIds_CountryMacedoniafyrom
#define cids_CountryMax	IHsvCountryIds_CountryMax
#define cids_CountryThailand	IHsvCountryIds_CountryThailand
#define cids_CountryNewZealand	IHsvCountryIds_CountryNewZealand
#define cids_CountrySingapore	IHsvCountryIds_CountrySingapore
#define cids_CountryMalaysia	IHsvCountryIds_CountryMalaysia
#define cids_CountryTaiwan	IHsvCountryIds_CountryTaiwan
#define cids_CountryIndonesia	IHsvCountryIds_CountryIndonesia
#define cids_CountryUAE	IHsvCountryIds_CountryUAE
#define cids_CountryVietnam     IHsvCountryIds_CountryVietnam
#define eurdiv_iPresent() (eurdiv.Present())
#define eurdiv_iVersion	eurdiv->iVersion()
#define eurdiv_NITTimeoutTime	eurdiv->NITTimeoutTime()
#define eurdiv_AttenuatorDetectionInInstall	eurdiv->AttenuatorDetectionInInstall()
#define eurdiv_SupportNameExtractionInManIns	eurdiv->SupportNameExtractionInManIns()
#define eurdiv_WeakSignalStrengthThreshold	eurdiv->WeakSignalStrengthThreshold()
#define eurdiv_SignalStrengthSorting	eurdiv->SignalStrengthSorting()
#define eurdiv_SearchForColorSystemInInstallation	eurdiv->SearchForColorSystemInInstallation()
#define eurdiv_SearchForTvSystemInInstallation	eurdiv->SearchForTvSystemInInstallation()
#define eurdiv_ManualSearchWithWrapAround	eurdiv->ManualSearchWithWrapAround()
#define eurdiv_SortPresetsInAutoStoreModeNone	eurdiv->SortPresetsInAutoStoreModeNone()
#define eurdiv_SignalStrengthTimeoutTime	eurdiv->SignalStrengthTimeoutTime()
#define eurdiv_DefaultTunerPresetFrequency	eurdiv->DefaultTunerPresetFrequency()
#define eurdiv_PgctrlMuteColor	eurdiv->PgctrlMuteColor()
#define eurdiv_ChannelNameLength	eurdiv->ChannelNameLength()
#define eurdiv_PresetNameLength	eurdiv->PresetNameLength()
#define eurdiv_MuteRequiredOnInstallation	eurdiv->MuteRequiredOnInstallation()
#define eurdiv_ClearDataOnAutoInstallation	eurdiv->ClearDataOnAutoInstallation()
#define eurdiv_AnalogOnly()	eurdiv->AnalogOnly()
#define eurdiv_InstallTestStreams(installationmode,medium)	eurdiv->InstallTestStreams(installationmode,medium)
#define eurdiv_NotInstall	IHsvEuropeDiversity2_NotInstall
#define eurdiv_Install	IHsvEuropeDiversity2_Install
#define eurdiv_Hide	IHsvEuropeDiversity2_Hide
#define eurdiv_NoOfVirtualChannelsSupported(medium)	eurdiv->NoOfVirtualChannelsSupported(medium)
#define eurdiv_SupportMultipleOriginalNetworkId(medium)	eurdiv->SupportMultipleOriginalNetworkId(medium)
#define eurdiv_ForceLCNSyntax(medium)	eurdiv->ForceLCNSyntax(medium)
#define eurdiv_InstallDuplicateTsids(medium)	eurdiv->InstallDuplicateTsids(medium)
#define eurdiv_DefaultStreamPriority(medium)	eurdiv->DefaultStreamPriority(medium)
#define eurdiv_IsServiceInstallable(medium,ServiceType)	eurdiv->IsServiceInstallable(medium,ServiceType)
#define eurdiv_IsServiceSortable(medium,ServiceType)	eurdiv->IsServiceSortable(medium,ServiceType)
#define eurdiv_IsServiceHidden(medium,ServiceType)	eurdiv->IsServiceHidden(medium,ServiceType)
#define eurdiv_AcceptedStreamType(medium,StreamType)	eurdiv->AcceptedStreamType(medium,StreamType)
#define eurdiv_UpdateChannelName(medium)	eurdiv->UpdateChannelName(medium)
#define eurdiv_IsApmeaChannelListCountry()	eurdiv->IsApmeaChannelListCountry()
#define eurdiv_IsApmeaNetworkUpdateCountry()	eurdiv->IsApmeaNetworkUpdateCountry()
#define eurdiv_IsDbookCountry()	eurdiv->IsDbookCountry()
#define eurdiv_SkipInstallationPass	eurdiv->SkipInstallationPass()
#define eurdiv_FirstInstallationPass	eurdiv->FirstInstallationPass()
#define eurdiv_SkipAnalog	IHsvEuropeDiversity2_SkipAnalog
#define eurdiv_SkipDigital	IHsvEuropeDiversity2_SkipDigital
#define eurdiv_SkipNone	IHsvEuropeDiversity2_SkipNone
#define eurdiv_UpdateLCN(medium)	eurdiv->UpdateLCN(medium)
#define eurdiv_TxtInfoTimeout	eurdiv->TxtInfoTimeout()
#define eurdiv_VideoMuteColor	eurdiv->VideoMuteColor()
#define eurdiv_VideoMuteColorForLocks	eurdiv->VideoMuteColorForLocks()
#define eurdiv_VideoMuteBlack	IHsvEuropeDiversity2_VideoMuteBlack
#define eurdiv_VideoMuteBlue	IHsvEuropeDiversity2_VideoMuteBlue
#define eurdiv_VideoMuteGrey	IHsvEuropeDiversity2_VideoMuteGrey
#define eurdiv_DecoderSupported	eurdiv->DecoderSupported()
#define eurdiv_BreakInSupported	eurdiv->BreakInSupported()
#define eurdiv_ScartRuleSupported	eurdiv->ScartRuleSupported()
#define eurdiv_HsvAntennaAnalogTable	eurdiv->HsvAntennaAnalogTable()
#define eurdiv_HsvAntennaDigSrvcTable	eurdiv->HsvAntennaDigSrvcTable()
#define eurdiv_HsvAntennaDigPtcTable	eurdiv->HsvAntennaDigPtcTable()
#define eurdiv_HsvAntennaFreqMapTable	eurdiv->HsvAntennaFreqMapTable()
#define eurdiv_PersistentMemUpdateTimeout	eurdiv->PersistentMemUpdateTimeout()
#define eurdiv_MaxNoOfChannelsToStoreAntennaUserTable	eurdiv->MaxNoOfChannelsToStoreAntennaUserTable()
#define eurdiv_MaxNoOfChannelsToStoreAntennaDigSrvcTable	eurdiv->MaxNoOfChannelsToStoreAntennaDigSrvcTable()
#define eurdiv_MaxNoOfChannelsToStoreAntennaDigPtcTable	eurdiv->MaxNoOfChannelsToStoreAntennaDigPtcTable()
#define eurdiv_MaxNoOfChannelsToStoreAntennaAnalogTable	eurdiv->MaxNoOfChannelsToStoreAntennaAnalogTable()
#define eurdiv_MaxNoOfMultiplexsToStoreAntennaFreqMapTable	eurdiv->MaxNoOfMultiplexsToStoreAntennaFreqMapTable()
#define eurdiv_IsHDSubtitleSupported()	eurdiv->IsHDSubtitleSupported()
#define eurdiv_AvSignalDetectionTimeOut	eurdiv->AvSignalDetectionTimeOut()
#define eurdiv_HearingImpairedOn	eurdiv->HearingImpairedOn()
#define eurdiv_VisuallyImpairedOn()	eurdiv->VisuallyImpairedOn()
#define eurdiv_IsQaaSupported()	eurdiv->IsQaaSupported()
#define eurdiv_IsPremixedVISupported()	eurdiv->IsPremixedVISupported()
#define eurdiv_EPGSecondaryDirName	eurdiv->EPGSecondaryDirName()
#define eurdiv_DefaultCharacterTable	eurdiv->DefaultCharacterTable()
#define eurdiv_ShortInfoCacheForCountry	eurdiv->ShortInfoCacheForCountry()
#define eurdiv_OUI	eurdiv->OUI()
#define eurdiv_HardwareModel	eurdiv->HardwareModel()
#define eurdiv_HardwareVersion	eurdiv->HardwareVersion()
#define eurdiv_GetNoOfBackBuffers(clientId)	eurdiv->GetNoOfBackBuffers(clientId)
#define eurdiv_SubtitleTimeOut	eurdiv->SubtitleTimeOut()
#define eurdiv_IsMpeg4STBoltOnSupported()	eurdiv->IsMpeg4STBoltOnSupported()
#define eurdiv_IsAVCDescriptorSupported()	eurdiv->IsAVCDescriptorSupported()
#define eurdiv_ForceCharacterTable()	eurdiv->ForceCharacterTable()
#define eurdiv_RegionalCharacterTable()	eurdiv->RegionalCharacterTable()
#define eurdiv_CurrentCountryInvalidLCNSortKey1	eurdiv->CurrentCountryInvalidLCNSortKey1()
#define eurdiv_CurrentCountryInvalidLCNSortKey2	eurdiv->CurrentCountryInvalidLCNSortKey2()
#define eurdiv_CurrentCountryInvalidLCNSortKey3	eurdiv->CurrentCountryInvalidLCNSortKey3()
#define eurdiv_CurrentCountryInvalidLCNSortKey4	eurdiv->CurrentCountryInvalidLCNSortKey4()
#define eurdiv_CurrentCountryInvalidLCNSortKey5	eurdiv->CurrentCountryInvalidLCNSortKey5()
#define eurdiv_OtherCountrySortKey1	eurdiv->OtherCountrySortKey1()
#define eurdiv_OtherCountrySortKey2	eurdiv->OtherCountrySortKey2()
#define eurdiv_OtherCountrySortKey3	eurdiv->OtherCountrySortKey3()
#define eurdiv_OtherCountrySortKey4	eurdiv->OtherCountrySortKey4()
#define eurdiv_OtherCountrySortKey5	eurdiv->OtherCountrySortKey5()
#define eurdiv_KeyInvalid	IHsvEuropeDiversity2_KeyInvalid
#define eurdiv_KeyOriginalNetworkId	IHsvEuropeDiversity2_KeyOriginalNetworkId
#define eurdiv_KeyServiceType	IHsvEuropeDiversity2_KeyServiceType
#define eurdiv_KeyLCN	IHsvEuropeDiversity2_KeyLCN
#define eurdiv_KeyServiceName	IHsvEuropeDiversity2_KeyServiceName
#define eurdiv_KeyServiceId	IHsvEuropeDiversity2_KeyServiceId
#define eurdiv_TripletKey(medium)	eurdiv->TripletKey(medium)
#define eurdiv_InstallDuplicateServices(medium)	eurdiv->InstallDuplicateServices(medium)
#define eurdiv_MeasureSignalStrengthWhilePlaying	eurdiv->MeasureSignalStrengthWhilePlaying()
#define eurdiv_AnalogInstallationSequence	eurdiv->AnalogInstallationSequence()
#define eurdiv_Automatic	IHsvEuropeDiversity2_Automatic
#define eurdiv_PalOnly	IHsvEuropeDiversity2_PalOnly
#define eurdiv_PalSecam	IHsvEuropeDiversity2_PalSecam
#define eurdiv_SecamPal	IHsvEuropeDiversity2_SecamPal
#define eurdiv_SecamOnly	IHsvEuropeDiversity2_SecamOnly
#define eurdiv_ChannelListVariant	eurdiv->ChannelListVariant()
#define eurdiv_DefaultChannelList	IHsvEuropeDiversity2_DefaultChannelList
#define eurdiv_DualChannelList	IHsvEuropeDiversity2_DualChannelList
#define eurdiv_TripleChannelList	IHsvEuropeDiversity2_TripleChannelList
#define eurdiv_EnableCountryFallbackForLCNSyntax(medium)	eurdiv->EnableCountryFallbackForLCNSyntax(medium)
#define eurdiv_EnableONIDFallbackForLCNSyntax(medium)	eurdiv->EnableONIDFallbackForLCNSyntax(medium)
#define eurdiv_HsvCableAnalogTable	eurdiv->HsvCableAnalogTable()
#define eurdiv_HsvCableDigSrvcTable	eurdiv->HsvCableDigSrvcTable()
#define eurdiv_HsvCableDigPtcTable	eurdiv->HsvCableDigPtcTable()
#define eurdiv_HsvCableSvcListDescTable	eurdiv->HsvCableSvcListDescTable()
#define eurdiv_HsvCableFreqMapTable	eurdiv->HsvCableFreqMapTable()
#define eurdiv_MaxNoOfChannelsToStoreCableUserTable	eurdiv->MaxNoOfChannelsToStoreCableUserTable()
#define eurdiv_MaxNoOfChannelsToStoreCableDigSrvcTable	eurdiv->MaxNoOfChannelsToStoreCableDigSrvcTable()
#define eurdiv_MaxNoOfChannelsToStoreCableDigPtcTable	eurdiv->MaxNoOfChannelsToStoreCableDigPtcTable()
#define eurdiv_MaxNoOfChannelsToStoreCableAnalogTable	eurdiv->MaxNoOfChannelsToStoreCableAnalogTable()
#define eurdiv_MaxNoOfMultiplexsToStoreCableFreqMapTable	eurdiv->MaxNoOfMultiplexsToStoreCableFreqMapTable()
#define eurdiv_IsDVBCSupported()	eurdiv->IsDVBCSupported()
#define eurdiv_QuickScan	IHsvEuropeDiversity2_QuickScan
#define eurdiv_FullScan	IHsvEuropeDiversity2_FullScan
#define eurdiv_GetDefaultScanMode(medium)	eurdiv->GetDefaultScanMode(medium)
#define eurdiv_ScanNone	IHsvEuropeDiversity2_ScanNone
#define eurdiv_ScanAnalog	IHsvEuropeDiversity2_ScanAnalog
#define eurdiv_ScanDVBT	IHsvEuropeDiversity2_ScanDVBT
#define eurdiv_ScanDVBC	IHsvEuropeDiversity2_ScanDVBC
#define eurdiv_ScanDVBS	IHsvEuropeDiversity2_ScanDVBS
#define eurdiv_ScanDVBTMpegOnly	IHsvEuropeDiversity2_ScanDVBTMpegOnly
#define eurdiv_ScanDVBCLite	IHsvEuropeDiversity2_ScanDVBCLite
#define eurdiv_GetScanPreference(medium,installationmode)	eurdiv->GetScanPreference(medium,installationmode)
#define eurdiv_GetNextScan(medium,installationmode,ScanPreference)	eurdiv->GetNextScan(medium,installationmode,ScanPreference)
#define eurdiv_GetDVBTMode()	eurdiv->GetDVBTMode()
#define eurdiv_GetDVBCMode()	eurdiv->GetDVBCMode()
#define eurdiv_NitNone	IHsvEuropeDiversity2_NitNone
#define eurdiv_NitActual	IHsvEuropeDiversity2_NitActual
#define eurdiv_NitOther	IHsvEuropeDiversity2_NitOther
#define eurdiv_GetNitPriority(medium)	eurdiv->GetNitPriority(medium)
#define eurdiv_IsServiceListDescriptorMandatory(medium)	eurdiv->IsServiceListDescriptorMandatory(medium)
#define eurdiv_PrimaryPreference	IHsvEuropeDiversity2_PrimaryPreference
#define eurdiv_SecondaryPreference	IHsvEuropeDiversity2_SecondaryPreference
#define eurdiv_GetAudioPreference()	eurdiv->GetAudioPreference()
#define eurdiv_GetSubtitlePreference()	eurdiv->GetSubtitlePreference()
#define eurdiv_UserPreferredAudioFormat()	eurdiv->UserPreferredAudioFormat()
#define eurdiv_IsFrequencyListStorageRequired()	eurdiv->IsFrequencyListStorageRequired()
#define eurdiv_GetDefaultAttributeValues(attrib,country,mode,length,values)	eurdiv->GetDefaultAttributeValues(attrib,country,mode,length,values)
#define eurdiv_HsvDVBCSettingsFilePath	eurdiv->HsvDVBCSettingsFilePath()
#define eurdiv_HsvCableDelSysDescFilePath	eurdiv->HsvCableDelSysDescFilePath()
#define eurdiv_HsvServiceListDescFilePath	eurdiv->HsvServiceListDescFilePath()
#define eurdiv_MaxLCNValue	eurdiv->MaxLCNValue()
#define eurdiv_IsBackgroundInstallRequired(medium)	eurdiv->IsBackgroundInstallRequired(medium)
#define eurdiv_SupportLCNVersion2(medium)	eurdiv->SupportLCNVersion2(medium)
#define eurdiv_ParseLCN(medium,installationmode)	eurdiv->ParseLCN(medium,installationmode)
#define eurdiv_IsPreScanSupported(medium)	eurdiv->IsPreScanSupported(medium)
#define eurdiv_SortNonLCNs(medium)	eurdiv->SortNonLCNs(medium)
#define eurdiv_SupportHDSLCN(medium)	eurdiv->SupportHDSLCN(medium)
#define eurdiv_IsServiceAttrbDescSupported(medium)	eurdiv->IsServiceAttrbDescSupported(medium)
#define eurdiv_IsTSRelocatedDescSupported(medium)	eurdiv->IsTSRelocatedDescSupported(medium)
#define eurdiv_SDTActual	IHsvEuropeDiversity2_SDTActual
#define eurdiv_SDTOther	IHsvEuropeDiversity2_SDTOther
#define eurdiv_SDTNone	IHsvEuropeDiversity2_SDTNone
#define eurdiv_GetAltSDTType(medium)	eurdiv->GetAltSDTType(medium)
#define eurdiv_AltHomingFrequency	IHsvEuropeDiversity2_AltHomingFrequency
#define eurdiv_AltTSRelocatedDesc	IHsvEuropeDiversity2_AltTSRelocatedDesc
#define eurdiv_AltNone	IHsvEuropeDiversity2_AltNone
#define eurdiv_GetAlternateTSLocation(medium)	eurdiv->GetAlternateTSLocation(medium)
#define eurdiv_GetAltFreqScanSupported(country)	eurdiv->GetAltFreqScanSupported(country)
#define eurdiv_FreqListDescriptorSupported(medium)	eurdiv->FreqListDescriptorSupported(medium)
#define eurdiv_IsAc3AudioSupported()	eurdiv->IsAc3AudioSupported()
#define eurdiv_GetDefaultAnalogInstallStatus(country)	eurdiv->GetDefaultAnalogInstallStatus(country)
#define eurdiv_StaticTable()	eurdiv->StaticTable()
#define eurdiv_GetDefaultDigitalInstallStatus(country)	eurdiv->GetDefaultDigitalInstallStatus(country)
#define eurdiv_IsMultifeedSupported()	eurdiv->IsMultifeedSupported()
#define eurdiv_IsZeroLCNHidden()	eurdiv->IsZeroLCNHidden()
#define eurdiv_GetViterbiBER()	eurdiv->GetViterbiBER()
#define eurdiv_DeltaViterbiBER()	eurdiv->DeltaViterbiBER()
#define eurdiv_GetShortInfoCacheSize()	eurdiv->GetShortInfoCacheSize()
#define eurdiv_GetDeltaSQI()	eurdiv->GetDeltaSQI()
#define eurdiv_GetDeltaSSI()	eurdiv->GetDeltaSSI()
#define eurdiv_AutomaticAnalogPresetAllocation()	eurdiv->AutomaticAnalogPresetAllocation()
#define eurdiv_AutomaticDigitalPresetAllocation()	eurdiv->AutomaticDigitalPresetAllocation()
#define eurdiv_AnalogStartPreset(country,medium,numRecords)	eurdiv->AnalogStartPreset(country,medium,numRecords)
#define eurdiv_AnalogEndPreset(country,medium)	eurdiv->AnalogEndPreset(country,medium)
#define eurdiv_NonRadioStartPreset(country,medium,numRecords)	eurdiv->NonRadioStartPreset(country,medium,numRecords)
#define eurdiv_NonRadioEndPreset(country,medium)	eurdiv->NonRadioEndPreset(country,medium)
#define eurdiv_RadioStartPreset(country,medium,numRecords)	eurdiv->RadioStartPreset(country,medium,numRecords)
#define eurdiv_RadioEndPreset(country,medium)	eurdiv->RadioEndPreset(country,medium)
#define eurdiv_IsHDSimulcastSupported()	eurdiv->IsHDSimulcastSupported()
#define eurdiv_IsDVBT2Supported()	eurdiv->IsDVBT2Supported()
#define eurdiv_MultipleLCNSupported()	eurdiv->MultipleLCNSupported()
#define eurdiv_SubtitlePidFallbackFirstPMT()	eurdiv->SubtitlePidFallbackFirstPMT()
#define eurdiv_DeleteTSNotIntransmission()	eurdiv->DeleteTSNotIntransmission()
#define eurdiv_ReapplyChildLockOnEventChange()	eurdiv->ReapplyChildLockOnEventChange()
#define eurdiv_DeleteServiceOnFly()	eurdiv->DeleteServiceOnFly()
#define idbooksort_iPresent() (idbooksort.Present())
#define idbooksort_Initialise()	idbooksort->Initialise()
#define idbooksort_AddAnalogPreset(adata)	idbooksort->AddAnalogPreset(adata)
#define idbooksort_AnalogPresetEntry()	idbooksort->AnalogPresetEntry()
#define idbooksort_AssignPresetsForCurrentCountry(CurrentOnwid,CheckLCN)	idbooksort->AssignPresetsForCurrentCountry(CurrentOnwid,CheckLCN)
#define idbooksort_AssignPresetsWithStaticTable(CurrentOnwid,Country)	idbooksort->AssignPresetsWithStaticTable(CurrentOnwid,Country)
#define idbooksort_AssignPresetsOfOtherCountries()	idbooksort->AssignPresetsOfOtherCountries()
#define idbooksort_AddDigitalPreset(svcdat)	idbooksort->AddDigitalPreset(svcdat)
#define idbooksort_AutoStoreManualInstallationValues()	idbooksort->AutoStoreManualInstallationValues()
#define idbooksort_RemoveDigitalPresets()	idbooksort->RemoveDigitalPresets()
#define idbooksort_GetNumberOfAnalogChannelsFound()	idbooksort->GetNumberOfAnalogChannelsFound()
#define idbooksort_UpdateDigitalPreset(svcdat)	idbooksort->UpdateDigitalPreset(svcdat)
#define idbooksort_DeleteAllDigitalChannels()	idbooksort->DeleteAllDigitalChannels()
#define idbooksort_UpdatingLCNDuringUpdateInstallation()	idbooksort->UpdatingLCNDuringUpdateInstallation()
#define idbooksort_DeleteInvalidPTCTable()	idbooksort->DeleteInvalidPTCTable()
#define idbooksort_GetOriginalNetworkId(CurrentCountry)	idbooksort->GetOriginalNetworkId(CurrentCountry)
#define idbooksort_IsPresetInstalled(frequency)	idbooksort->IsPresetInstalled(frequency)
#define idbooksort_AssignPresetsForCountry(ONID)	idbooksort->AssignPresetsForCountry(ONID)
#define idbooksort_SortAll()	idbooksort->SortAll()
#define idbooksort_AssignPresetsForCurrentCountryNonLCNs(CurrentOnwid,FillHoles)	idbooksort->AssignPresetsForCurrentCountryNonLCNs(CurrentOnwid,FillHoles)
#define idbooksort_AssignPresetsForCurrentCountryLowPrioLCN(CurrentOnwid)	idbooksort->AssignPresetsForCurrentCountryLowPrioLCN(CurrentOnwid)
#define idbooksort_GetInstalledWeakSignalChannel()	idbooksort->GetInstalledWeakSignalChannel()
#define idvbclitesort_iPresent() (idvbclitesort.Present())
#define idvbclitesort_Initialise()	idvbclitesort->Initialise()
#define idvbclitesort_AddAnalogPreset(adata)	idvbclitesort->AddAnalogPreset(adata)
#define idvbclitesort_AnalogPresetEntry()	idvbclitesort->AnalogPresetEntry()
#define idvbclitesort_AssignPresetsForCurrentCountry(CurrentOnwid,CheckLCN)	idvbclitesort->AssignPresetsForCurrentCountry(CurrentOnwid,CheckLCN)
#define idvbclitesort_AssignPresetsWithStaticTable(CurrentOnwid,Country)	idvbclitesort->AssignPresetsWithStaticTable(CurrentOnwid,Country)
#define idvbclitesort_AssignPresetsOfOtherCountries()	idvbclitesort->AssignPresetsOfOtherCountries()
#define idvbclitesort_AddDigitalPreset(svcdat)	idvbclitesort->AddDigitalPreset(svcdat)
#define idvbclitesort_AutoStoreManualInstallationValues()	idvbclitesort->AutoStoreManualInstallationValues()
#define idvbclitesort_RemoveDigitalPresets()	idvbclitesort->RemoveDigitalPresets()
#define idvbclitesort_GetNumberOfAnalogChannelsFound()	idvbclitesort->GetNumberOfAnalogChannelsFound()
#define idvbclitesort_UpdateDigitalPreset(svcdat)	idvbclitesort->UpdateDigitalPreset(svcdat)
#define idvbclitesort_DeleteAllDigitalChannels()	idvbclitesort->DeleteAllDigitalChannels()
#define idvbclitesort_UpdatingLCNDuringUpdateInstallation()	idvbclitesort->UpdatingLCNDuringUpdateInstallation()
#define idvbclitesort_DeleteInvalidPTCTable()	idvbclitesort->DeleteInvalidPTCTable()
#define idvbclitesort_GetOriginalNetworkId(CurrentCountry)	idvbclitesort->GetOriginalNetworkId(CurrentCountry)
#define idvbclitesort_IsPresetInstalled(frequency)	idvbclitesort->IsPresetInstalled(frequency)
#define idvbclitesort_AssignPresetsForCountry(ONID)	idvbclitesort->AssignPresetsForCountry(ONID)
#define idvbclitesort_SortAll()	idvbclitesort->SortAll()
#define idvbclitesort_AssignPresetsForCurrentCountryNonLCNs(CurrentOnwid,FillHoles)	idvbclitesort->AssignPresetsForCurrentCountryNonLCNs(CurrentOnwid,FillHoles)
#define idvbclitesort_AssignPresetsForCurrentCountryLowPrioLCN(CurrentOnwid)	idvbclitesort->AssignPresetsForCurrentCountryLowPrioLCN(CurrentOnwid)
#define idvbclitesort_GetInstalledWeakSignalChannel()	idvbclitesort->GetInstalledWeakSignalChannel()
#define idvbcsort_iPresent() (idvbcsort.Present())
#define idvbcsort_Initialise()	idvbcsort->Initialise()
#define idvbcsort_AddAnalogPreset(adata)	idvbcsort->AddAnalogPreset(adata)
#define idvbcsort_AnalogPresetEntry()	idvbcsort->AnalogPresetEntry()
#define idvbcsort_AssignPresetsForCurrentCountry(CurrentOnwid,CheckLCN)	idvbcsort->AssignPresetsForCurrentCountry(CurrentOnwid,CheckLCN)
#define idvbcsort_AssignPresetsWithStaticTable(CurrentOnwid,Country)	idvbcsort->AssignPresetsWithStaticTable(CurrentOnwid,Country)
#define idvbcsort_AssignPresetsOfOtherCountries()	idvbcsort->AssignPresetsOfOtherCountries()
#define idvbcsort_AddDigitalPreset(svcdat)	idvbcsort->AddDigitalPreset(svcdat)
#define idvbcsort_AutoStoreManualInstallationValues()	idvbcsort->AutoStoreManualInstallationValues()
#define idvbcsort_RemoveDigitalPresets()	idvbcsort->RemoveDigitalPresets()
#define idvbcsort_GetNumberOfAnalogChannelsFound()	idvbcsort->GetNumberOfAnalogChannelsFound()
#define idvbcsort_UpdateDigitalPreset(svcdat)	idvbcsort->UpdateDigitalPreset(svcdat)
#define idvbcsort_DeleteAllDigitalChannels()	idvbcsort->DeleteAllDigitalChannels()
#define idvbcsort_UpdatingLCNDuringUpdateInstallation()	idvbcsort->UpdatingLCNDuringUpdateInstallation()
#define idvbcsort_DeleteInvalidPTCTable()	idvbcsort->DeleteInvalidPTCTable()
#define idvbcsort_GetOriginalNetworkId(CurrentCountry)	idvbcsort->GetOriginalNetworkId(CurrentCountry)
#define idvbcsort_IsPresetInstalled(frequency)	idvbcsort->IsPresetInstalled(frequency)
#define idvbcsort_AssignPresetsForCountry(ONID)	idvbcsort->AssignPresetsForCountry(ONID)
#define idvbcsort_SortAll()	idvbcsort->SortAll()
#define idvbcsort_AssignPresetsForCurrentCountryNonLCNs(CurrentOnwid,FillHoles)	idvbcsort->AssignPresetsForCurrentCountryNonLCNs(CurrentOnwid,FillHoles)
#define idvbcsort_AssignPresetsForCurrentCountryLowPrioLCN(CurrentOnwid)	idvbcsort->AssignPresetsForCurrentCountryLowPrioLCN(CurrentOnwid)
#define idvbcsort_GetInstalledWeakSignalChannel()	idvbcsort->GetInstalledWeakSignalChannel()
#define iblizoosort_iPresent() (iblizoosort.Present())
#define iblizoosort_Initialise()	iblizoosort->Initialise()
#define iblizoosort_AddAnalogPreset(adata)	iblizoosort->AddAnalogPreset(adata)
#define iblizoosort_AnalogPresetEntry()	iblizoosort->AnalogPresetEntry()
#define iblizoosort_AssignPresetsForCurrentCountry(CurrentOnwid,CheckLCN)	iblizoosort->AssignPresetsForCurrentCountry(CurrentOnwid,CheckLCN)
#define iblizoosort_AssignPresetsWithStaticTable(CurrentOnwid,Country)	iblizoosort->AssignPresetsWithStaticTable(CurrentOnwid,Country)
#define iblizoosort_AssignPresetsOfOtherCountries()	iblizoosort->AssignPresetsOfOtherCountries()
#define iblizoosort_AddDigitalPreset(svcdat)	iblizoosort->AddDigitalPreset(svcdat)
#define iblizoosort_AutoStoreManualInstallationValues()	iblizoosort->AutoStoreManualInstallationValues()
#define iblizoosort_RemoveDigitalPresets()	iblizoosort->RemoveDigitalPresets()
#define iblizoosort_GetNumberOfAnalogChannelsFound()	iblizoosort->GetNumberOfAnalogChannelsFound()
#define iblizoosort_UpdateDigitalPreset(svcdat)	iblizoosort->UpdateDigitalPreset(svcdat)
#define iblizoosort_DeleteAllDigitalChannels()	iblizoosort->DeleteAllDigitalChannels()
#define iblizoosort_UpdatingLCNDuringUpdateInstallation()	iblizoosort->UpdatingLCNDuringUpdateInstallation()
#define iblizoosort_DeleteInvalidPTCTable()	iblizoosort->DeleteInvalidPTCTable()
#define iblizoosort_GetOriginalNetworkId(CurrentCountry)	iblizoosort->GetOriginalNetworkId(CurrentCountry)
#define iblizoosort_IsPresetInstalled(frequency)	iblizoosort->IsPresetInstalled(frequency)
#define iblizoosort_AssignPresetsForCountry(ONID)	iblizoosort->AssignPresetsForCountry(ONID)
#define iblizoosort_SortAll()	iblizoosort->SortAll()
#define iblizoosort_AssignPresetsForCurrentCountryNonLCNs(CurrentOnwid,FillHoles)	iblizoosort->AssignPresetsForCurrentCountryNonLCNs(CurrentOnwid,FillHoles)
#define iblizoosort_AssignPresetsForCurrentCountryLowPrioLCN(CurrentOnwid)	iblizoosort->AssignPresetsForCurrentCountryLowPrioLCN(CurrentOnwid)
#define iblizoosort_GetInstalledWeakSignalChannel()	iblizoosort->GetInstalledWeakSignalChannel()
#define idvbtlitesort_iPresent() (idvbtlitesort.Present())
#define idvbtlitesort_Initialise()	idvbtlitesort->Initialise()
#define idvbtlitesort_AddAnalogPreset(adata)	idvbtlitesort->AddAnalogPreset(adata)
#define idvbtlitesort_AnalogPresetEntry()	idvbtlitesort->AnalogPresetEntry()
#define idvbtlitesort_AssignPresetsForCurrentCountry(CurrentOnwid,CheckLCN)	idvbtlitesort->AssignPresetsForCurrentCountry(CurrentOnwid,CheckLCN)
#define idvbtlitesort_AssignPresetsWithStaticTable(CurrentOnwid,Country)	idvbtlitesort->AssignPresetsWithStaticTable(CurrentOnwid,Country)
#define idvbtlitesort_AssignPresetsOfOtherCountries()	idvbtlitesort->AssignPresetsOfOtherCountries()
#define idvbtlitesort_AddDigitalPreset(svcdat)	idvbtlitesort->AddDigitalPreset(svcdat)
#define idvbtlitesort_AutoStoreManualInstallationValues()	idvbtlitesort->AutoStoreManualInstallationValues()
#define idvbtlitesort_RemoveDigitalPresets()	idvbtlitesort->RemoveDigitalPresets()
#define idvbtlitesort_GetNumberOfAnalogChannelsFound()	idvbtlitesort->GetNumberOfAnalogChannelsFound()
#define idvbtlitesort_UpdateDigitalPreset(svcdat)	idvbtlitesort->UpdateDigitalPreset(svcdat)
#define idvbtlitesort_DeleteAllDigitalChannels()	idvbtlitesort->DeleteAllDigitalChannels()
#define idvbtlitesort_UpdatingLCNDuringUpdateInstallation()	idvbtlitesort->UpdatingLCNDuringUpdateInstallation()
#define idvbtlitesort_DeleteInvalidPTCTable()	idvbtlitesort->DeleteInvalidPTCTable()
#define idvbtlitesort_GetOriginalNetworkId(CurrentCountry)	idvbtlitesort->GetOriginalNetworkId(CurrentCountry)
#define idvbtlitesort_IsPresetInstalled(frequency)	idvbtlitesort->IsPresetInstalled(frequency)
#define idvbtlitesort_AssignPresetsForCountry(ONID)	idvbtlitesort->AssignPresetsForCountry(ONID)
#define idvbtlitesort_SortAll()	idvbtlitesort->SortAll()
#define idvbtlitesort_AssignPresetsForCurrentCountryNonLCNs(CurrentOnwid,FillHoles)	idvbtlitesort->AssignPresetsForCurrentCountryNonLCNs(CurrentOnwid,FillHoles)
#define idvbtlitesort_AssignPresetsForCurrentCountryLowPrioLCN(CurrentOnwid)	idvbtlitesort->AssignPresetsForCurrentCountryLowPrioLCN(CurrentOnwid)
#define idvbtlitesort_GetInstalledWeakSignalChannel()	idvbtlitesort->GetInstalledWeakSignalChannel()
#define idvbtsort_iPresent() (idvbtsort.Present())
#define idvbtsort_Initialise()	idvbtsort->Initialise()
#define idvbtsort_AddAnalogPreset(adata)	idvbtsort->AddAnalogPreset(adata)
#define idvbtsort_AnalogPresetEntry()	idvbtsort->AnalogPresetEntry()
#define idvbtsort_AssignPresetsForCurrentCountry(CurrentOnwid,CheckLCN)	idvbtsort->AssignPresetsForCurrentCountry(CurrentOnwid,CheckLCN)
#define idvbtsort_AssignPresetsWithStaticTable(CurrentOnwid,Country)	idvbtsort->AssignPresetsWithStaticTable(CurrentOnwid,Country)
#define idvbtsort_AssignPresetsOfOtherCountries()	idvbtsort->AssignPresetsOfOtherCountries()
#define idvbtsort_AddDigitalPreset(svcdat)	idvbtsort->AddDigitalPreset(svcdat)
#define idvbtsort_AutoStoreManualInstallationValues()	idvbtsort->AutoStoreManualInstallationValues()
#define idvbtsort_RemoveDigitalPresets()	idvbtsort->RemoveDigitalPresets()
#define idvbtsort_GetNumberOfAnalogChannelsFound()	idvbtsort->GetNumberOfAnalogChannelsFound()
#define idvbtsort_UpdateDigitalPreset(svcdat)	idvbtsort->UpdateDigitalPreset(svcdat)
#define idvbtsort_DeleteAllDigitalChannels()	idvbtsort->DeleteAllDigitalChannels()
#define idvbtsort_UpdatingLCNDuringUpdateInstallation()	idvbtsort->UpdatingLCNDuringUpdateInstallation()
#define idvbtsort_DeleteInvalidPTCTable()	idvbtsort->DeleteInvalidPTCTable()
#define idvbtsort_GetOriginalNetworkId(CurrentCountry)	idvbtsort->GetOriginalNetworkId(CurrentCountry)
#define idvbtsort_IsPresetInstalled(frequency)	idvbtsort->IsPresetInstalled(frequency)
#define idvbtsort_AssignPresetsForCountry(ONID)	idvbtsort->AssignPresetsForCountry(ONID)
#define idvbtsort_SortAll()	idvbtsort->SortAll()
#define idvbtsort_AssignPresetsForCurrentCountryNonLCNs(CurrentOnwid,FillHoles)	idvbtsort->AssignPresetsForCurrentCountryNonLCNs(CurrentOnwid,FillHoles)
#define idvbtsort_AssignPresetsForCurrentCountryLowPrioLCN(CurrentOnwid)	idvbtsort->AssignPresetsForCurrentCountryLowPrioLCN(CurrentOnwid)
#define idvbtsort_GetInstalledWeakSignalChannel()	idvbtsort->GetInstalledWeakSignalChannel()
#define ifinsort_iPresent() (ifinsort.Present())
#define ifinsort_Initialise()	ifinsort->Initialise()
#define ifinsort_AddAnalogPreset(adata)	ifinsort->AddAnalogPreset(adata)
#define ifinsort_AnalogPresetEntry()	ifinsort->AnalogPresetEntry()
#define ifinsort_AssignPresetsForCurrentCountry(CurrentOnwid,CheckLCN)	ifinsort->AssignPresetsForCurrentCountry(CurrentOnwid,CheckLCN)
#define ifinsort_AssignPresetsWithStaticTable(CurrentOnwid,Country)	ifinsort->AssignPresetsWithStaticTable(CurrentOnwid,Country)
#define ifinsort_AssignPresetsOfOtherCountries()	ifinsort->AssignPresetsOfOtherCountries()
#define ifinsort_AddDigitalPreset(svcdat)	ifinsort->AddDigitalPreset(svcdat)
#define ifinsort_AutoStoreManualInstallationValues()	ifinsort->AutoStoreManualInstallationValues()
#define ifinsort_RemoveDigitalPresets()	ifinsort->RemoveDigitalPresets()
#define ifinsort_GetNumberOfAnalogChannelsFound()	ifinsort->GetNumberOfAnalogChannelsFound()
#define ifinsort_UpdateDigitalPreset(svcdat)	ifinsort->UpdateDigitalPreset(svcdat)
#define ifinsort_DeleteAllDigitalChannels()	ifinsort->DeleteAllDigitalChannels()
#define ifinsort_UpdatingLCNDuringUpdateInstallation()	ifinsort->UpdatingLCNDuringUpdateInstallation()
#define ifinsort_DeleteInvalidPTCTable()	ifinsort->DeleteInvalidPTCTable()
#define ifinsort_GetOriginalNetworkId(CurrentCountry)	ifinsort->GetOriginalNetworkId(CurrentCountry)
#define ifinsort_IsPresetInstalled(frequency)	ifinsort->IsPresetInstalled(frequency)
#define ifinsort_AssignPresetsForCountry(ONID)	ifinsort->AssignPresetsForCountry(ONID)
#define ifinsort_SortAll()	ifinsort->SortAll()
#define ifinsort_AssignPresetsForCurrentCountryNonLCNs(CurrentOnwid,FillHoles)	ifinsort->AssignPresetsForCurrentCountryNonLCNs(CurrentOnwid,FillHoles)
#define ifinsort_AssignPresetsForCurrentCountryLowPrioLCN(CurrentOnwid)	ifinsort->AssignPresetsForCurrentCountryLowPrioLCN(CurrentOnwid)
#define ifinsort_GetInstalledWeakSignalChannel()	ifinsort->GetInstalledWeakSignalChannel()
#define inorsort_iPresent() (inorsort.Present())
#define inorsort_Initialise()	inorsort->Initialise()
#define inorsort_AddAnalogPreset(adata)	inorsort->AddAnalogPreset(adata)
#define inorsort_AnalogPresetEntry()	inorsort->AnalogPresetEntry()
#define inorsort_AssignPresetsForCurrentCountry(CurrentOnwid,CheckLCN)	inorsort->AssignPresetsForCurrentCountry(CurrentOnwid,CheckLCN)
#define inorsort_AssignPresetsWithStaticTable(CurrentOnwid,Country)	inorsort->AssignPresetsWithStaticTable(CurrentOnwid,Country)
#define inorsort_AssignPresetsOfOtherCountries()	inorsort->AssignPresetsOfOtherCountries()
#define inorsort_AddDigitalPreset(svcdat)	inorsort->AddDigitalPreset(svcdat)
#define inorsort_AutoStoreManualInstallationValues()	inorsort->AutoStoreManualInstallationValues()
#define inorsort_RemoveDigitalPresets()	inorsort->RemoveDigitalPresets()
#define inorsort_GetNumberOfAnalogChannelsFound()	inorsort->GetNumberOfAnalogChannelsFound()
#define inorsort_UpdateDigitalPreset(svcdat)	inorsort->UpdateDigitalPreset(svcdat)
#define inorsort_DeleteAllDigitalChannels()	inorsort->DeleteAllDigitalChannels()
#define inorsort_UpdatingLCNDuringUpdateInstallation()	inorsort->UpdatingLCNDuringUpdateInstallation()
#define inorsort_DeleteInvalidPTCTable()	inorsort->DeleteInvalidPTCTable()
#define inorsort_GetOriginalNetworkId(CurrentCountry)	inorsort->GetOriginalNetworkId(CurrentCountry)
#define inorsort_IsPresetInstalled(frequency)	inorsort->IsPresetInstalled(frequency)
#define inorsort_AssignPresetsForCountry(ONID)	inorsort->AssignPresetsForCountry(ONID)
#define inorsort_SortAll()	inorsort->SortAll()
#define inorsort_AssignPresetsForCurrentCountryNonLCNs(CurrentOnwid,FillHoles)	inorsort->AssignPresetsForCurrentCountryNonLCNs(CurrentOnwid,FillHoles)
#define inorsort_AssignPresetsForCurrentCountryLowPrioLCN(CurrentOnwid)	inorsort->AssignPresetsForCurrentCountryLowPrioLCN(CurrentOnwid)
#define inorsort_GetInstalledWeakSignalChannel()	inorsort->GetInstalledWeakSignalChannel()
#define itasort_iPresent() (itasort.Present())
#define itasort_Initialise()	itasort->Initialise()
#define itasort_AddAnalogPreset(adata)	itasort->AddAnalogPreset(adata)
#define itasort_AnalogPresetEntry()	itasort->AnalogPresetEntry()
#define itasort_AssignPresetsForCurrentCountry(CurrentOnwid,CheckLCN)	itasort->AssignPresetsForCurrentCountry(CurrentOnwid,CheckLCN)
#define itasort_AssignPresetsWithStaticTable(CurrentOnwid,Country)	itasort->AssignPresetsWithStaticTable(CurrentOnwid,Country)
#define itasort_AssignPresetsOfOtherCountries()	itasort->AssignPresetsOfOtherCountries()
#define itasort_AddDigitalPreset(svcdat)	itasort->AddDigitalPreset(svcdat)
#define itasort_AutoStoreManualInstallationValues()	itasort->AutoStoreManualInstallationValues()
#define itasort_RemoveDigitalPresets()	itasort->RemoveDigitalPresets()
#define itasort_GetNumberOfAnalogChannelsFound()	itasort->GetNumberOfAnalogChannelsFound()
#define itasort_UpdateDigitalPreset(svcdat)	itasort->UpdateDigitalPreset(svcdat)
#define itasort_DeleteAllDigitalChannels()	itasort->DeleteAllDigitalChannels()
#define itasort_UpdatingLCNDuringUpdateInstallation()	itasort->UpdatingLCNDuringUpdateInstallation()
#define itasort_DeleteInvalidPTCTable()	itasort->DeleteInvalidPTCTable()
#define itasort_GetOriginalNetworkId(CurrentCountry)	itasort->GetOriginalNetworkId(CurrentCountry)
#define itasort_IsPresetInstalled(frequency)	itasort->IsPresetInstalled(frequency)
#define itasort_AssignPresetsForCountry(ONID)	itasort->AssignPresetsForCountry(ONID)
#define itasort_SortAll()	itasort->SortAll()
#define itasort_AssignPresetsForCurrentCountryNonLCNs(CurrentOnwid,FillHoles)	itasort->AssignPresetsForCurrentCountryNonLCNs(CurrentOnwid,FillHoles)
#define itasort_AssignPresetsForCurrentCountryLowPrioLCN(CurrentOnwid)	itasort->AssignPresetsForCurrentCountryLowPrioLCN(CurrentOnwid)
#define itasort_GetInstalledWeakSignalChannel()	itasort->GetInstalledWeakSignalChannel()

#define idvbtapmeasort_iPresent() (idvbtapmeasort.Present())
#define idvbtapmeasort_Initialise()	idvbtapmeasort->Initialise()
#define idvbtapmeasort_AddAnalogPreset(adata)	idvbtapmeasort->AddAnalogPreset(adata)
#define idvbtapmeasort_AnalogPresetEntry()	idvbtapmeasort->AnalogPresetEntry()
#define idvbtapmeasort_AssignPresetsForCurrentCountry(CurrentOnwid,CheckLCN)	idvbtapmeasort->AssignPresetsForCurrentCountry(CurrentOnwid,CheckLCN)
#define idvbtapmeasort_AssignPresetsWithStaticTable(CurrentOnwid,Country)	idvbtapmeasort->AssignPresetsWithStaticTable(CurrentOnwid,Country)
#define idvbtapmeasort_AssignPresetsOfOtherCountries()	idvbtapmeasort->AssignPresetsOfOtherCountries()
#define idvbtapmeasort_AddDigitalPreset(svcdat)	idvbtapmeasort->AddDigitalPreset(svcdat)
#define idvbtapmeasort_AutoStoreManualInstallationValues()	idvbtapmeasort->AutoStoreManualInstallationValues()
#define idvbtapmeasort_RemoveDigitalPresets()	idvbtapmeasort->RemoveDigitalPresets()
#define idvbtapmeasort_GetNumberOfAnalogChannelsFound()	idvbtapmeasort->GetNumberOfAnalogChannelsFound()
#define idvbtapmeasort_UpdateDigitalPreset(svcdat)	idvbtapmeasort->UpdateDigitalPreset(svcdat)
#define idvbtapmeasort_DeleteAllDigitalChannels()	idvbtapmeasort->DeleteAllDigitalChannels()
#define idvbtapmeasort_UpdatingLCNDuringUpdateInstallation()	idvbtapmeasort->UpdatingLCNDuringUpdateInstallation()
#define idvbtapmeasort_DeleteInvalidPTCTable()	idvbtapmeasort->DeleteInvalidPTCTable()
#define idvbtapmeasort_GetOriginalNetworkId(CurrentCountry)	idvbtapmeasort->GetOriginalNetworkId(CurrentCountry)
#define idvbtapmeasort_IsPresetInstalled(frequency)	idvbtapmeasort->IsPresetInstalled(frequency)
#define idvbtapmeasort_AssignPresetsForCountry(ONID)	idvbtapmeasort->AssignPresetsForCountry(ONID)
#define idvbtapmeasort_SortAll()	idvbtapmeasort->SortAll()
#define idvbtapmeasort_AssignPresetsForCurrentCountryNonLCNs(CurrentOnwid,FillHoles)	idvbtapmeasort->AssignPresetsForCurrentCountryNonLCNs(CurrentOnwid,FillHoles)
#define idvbtapmeasort_AssignPresetsForCurrentCountryLowPrioLCN(CurrentOnwid)	idvbtapmeasort->AssignPresetsForCurrentCountryLowPrioLCN(CurrentOnwid)
#define idvbtapmeasort_GetInstalledWeakSignalChannel()	idvbtapmeasort->GetInstalledWeakSignalChannel()
#define idvbthungarysort_iPresent() (idvbthungarysort.Present())
#define idvbthungarysort_Initialise()	idvbthungarysort->Initialise()
#define idvbthungarysort_AddAnalogPreset(adata)	idvbthungarysort->AddAnalogPreset(adata)
#define idvbthungarysort_AnalogPresetEntry()	idvbthungarysort->AnalogPresetEntry()
#define idvbthungarysort_AssignPresetsForCurrentCountry(CurrentOnwid,CheckLCN)	idvbthungarysort->AssignPresetsForCurrentCountry(CurrentOnwid,CheckLCN)
#define idvbthungarysort_AssignPresetsWithStaticTable(CurrentOnwid,Country)	idvbthungarysort->AssignPresetsWithStaticTable(CurrentOnwid,Country)
#define idvbthungarysort_AssignPresetsOfOtherCountries()	idvbthungarysort->AssignPresetsOfOtherCountries()
#define idvbthungarysort_AddDigitalPreset(svcdat)	idvbthungarysort->AddDigitalPreset(svcdat)
#define idvbthungarysort_AutoStoreManualInstallationValues()	idvbthungarysort->AutoStoreManualInstallationValues()
#define idvbthungarysort_RemoveDigitalPresets()	idvbthungarysort->RemoveDigitalPresets()
#define idvbthungarysort_GetNumberOfAnalogChannelsFound()	idvbthungarysort->GetNumberOfAnalogChannelsFound()
#define idvbthungarysort_UpdateDigitalPreset(svcdat)	idvbthungarysort->UpdateDigitalPreset(svcdat)
#define idvbthungarysort_DeleteAllDigitalChannels()	idvbthungarysort->DeleteAllDigitalChannels()
#define idvbthungarysort_UpdatingLCNDuringUpdateInstallation()	idvbthungarysort->UpdatingLCNDuringUpdateInstallation()
#define idvbthungarysort_DeleteInvalidPTCTable()	idvbthungarysort->DeleteInvalidPTCTable()
#define idvbthungarysort_GetOriginalNetworkId(CurrentCountry)	idvbthungarysort->GetOriginalNetworkId(CurrentCountry)
#define idvbthungarysort_IsPresetInstalled(frequency)	idvbthungarysort->IsPresetInstalled(frequency)
#define idvbthungarysort_AssignPresetsForCountry(ONID)	idvbthungarysort->AssignPresetsForCountry(ONID)
#define idvbthungarysort_SortAll()	idvbthungarysort->SortAll()
#define idvbthungarysort_AssignPresetsForCurrentCountryNonLCNs(CurrentOnwid,FillHoles)	idvbthungarysort->AssignPresetsForCurrentCountryNonLCNs(CurrentOnwid,FillHoles)
#define idvbthungarysort_AssignPresetsForCurrentCountryLowPrioLCN(CurrentOnwid)	idvbthungarysort->AssignPresetsForCurrentCountryLowPrioLCN(CurrentOnwid)
#define idvbthungarysort_GetInstalledWeakSignalChannel()	idvbthungarysort->GetInstalledWeakSignalChannel()
#define rins_FullScan	IHsvInstallation2_FullScan
#define rins_Blizoo	IHsvInstallation2_Blizoo
#define rins_iPresent() (rins.Present())
#define rins_InvalidChannel	IHsvInstallation2_InvalidChannel
#define rins_InvalidFrequency	IHsvInstallation2_InvalidFrequency
#define rins_StIdle	IHsvInstallation2_StIdle
#define rins_StSourceSetupWait	IHsvInstallation2_StSourceSetupWait
#define rins_StDigital	IHsvInstallation2_StDigital
#define rins_StAnalog	IHsvInstallation2_StAnalog
#define rins_StPreSorting	IHsvInstallation2_StPreSorting
#define rins_StSorting	IHsvInstallation2_StSorting
#define rins_Terrestrial	IHsvInstallation2_Terrestrial
#define rins_Cable	IHsvInstallation2_Cable
#define rins_Satellite	IHsvInstallation2_Satellite
#define rins_InstallationInPassAnalog	IHsvInstallation2_InstallationInPassAnalog
#define rins_InstallationInDigitalPass	IHsvInstallation2_InstallationInDigitalPass
#define rins_InstallationStateScrambledSearch	IHsvInstallation2_InstallationStateScrambledSearch
#define rins_InstallationStateIdle	IHsvInstallation2_InstallationStateIdle
#define rins_InstallationStateInProgress	IHsvInstallation2_InstallationStateInProgress
#define rins_InstallationStatePaused	IHsvInstallation2_InstallationStatePaused
#define rins_InstallationModeNone	IHsvInstallation2_InstallationModeNone
#define rins_InstallationModeManual	IHsvInstallation2_InstallationModeManual
#define rins_InstallationModeAutomatic	IHsvInstallation2_InstallationModeAutomatic
#define rins_InstallationModeBackground	IHsvInstallation2_InstallationModeBackground
#define rins_InstallationModeImplicit	IHsvInstallation2_InstallationModeImplicit
#define rins_InstallationModeUpdate	IHsvInstallation2_InstallationModeUpdate
#define rins_InstallationModeWeakSignal	IHsvInstallation2_InstallationModeWeakSignal
#define rins_InstallationModeSingleChannel	IHsvInstallation2_InstallationModeSingleChannel
#define rins_InstallationModePreScan	IHsvInstallation2_InstallationModePreScan
#define rins_InstallationModeDtr	IHsvInstallation2_InstallationModeDtr
#define rins_InstallationModeCam	IHsvInstallation2_InstallationModeCam
#define rins_MaxChannel	IHsvInstallation2_MaxChannel
#define rins_ManualInstallationModeFrequency	IHsvInstallation2_ManualInstallationModeFrequency
#define rins_InsTvSystemBg	IHsvInstallation2_InsTvSystemBg
#define rins_InsTvSystemDk	IHsvInstallation2_InsTvSystemDk
#define rins_InsTvSystemI	IHsvInstallation2_InsTvSystemI
#define rins_InsTvSystemL	IHsvInstallation2_InsTvSystemL
#define rins_InsTvSystemN	IHsvInstallation2_InsTvSystemN
#define rins_InsTvSystemM	IHsvInstallation2_InsTvSystemM
#define rins_InsTvSystemAuto	IHsvInstallation2_InsTvSystemAuto
#define rins_InsColourSystemPal	IHsvInstallation2_InsColourSystemPal
#define rins_InsColurSystemSecam	IHsvInstallation2_InsColurSystemSecam
#define rins_InsColurSystemNtsc358	IHsvInstallation2_InsColurSystemNtsc358
#define rins_InsColurSystemNtsc443	IHsvInstallation2_InsColurSystemNtsc443
#define rins_InsColurSystemAuto	IHsvInstallation2_InsColurSystemAuto
#define rins_InsColurSystemInvalid	IHsvInstallation2_InsColurSystemInvalid
#define rins_InsColurSystemNtscUnknown	IHsvInstallation2_InsColurSystemNtscUnknown
#define rins_InsAssm	IHsvInstallation2_InsAssm
#define rins_InsVssm	IHsvInstallation2_InsVssm
#define rins_InsQssm	IHsvInstallation2_InsQssm
#define rins_InsSssm	IHsvInstallation2_InsSssm
#define rins_StartInstallation(source,ptc,mode)	rins->StartInstallation(source,ptc,mode)
#define rins_StopInstallation()	rins->StopInstallation()
#define rins_GetNumberOfAnalogChannelsFound()	rins->GetNumberOfAnalogChannelsFound()
#define rins_GetNumberOfDigitalChannelsFound()	rins->GetNumberOfDigitalChannelsFound()
#define rins_GetNumberOfDigitalChannelsRemoved()	rins->GetNumberOfDigitalChannelsRemoved()
#define rins_GetInstallationProgress()	rins->GetInstallationProgress()
#define rins_GetInstallationStatus()	rins->GetInstallationStatus()
#define rins_GetInstallationMode()	rins->GetInstallationMode()
#define rins_IsUpdateInstallationSupported()	rins->IsUpdateInstallationSupported()
#define rins_SetInstallCountry(country)	rins->SetInstallCountry(country)
#define rins_SetSystemCountry(country)	rins->SetSystemCountry(country)
#define rins_GetFirstIntalledDigitalChannel(channelno)	rins->GetFirstIntalledDigitalChannel(channelno)
#define rins_GetFirstIntalledAnalogueChannel(channelno)	rins->GetFirstIntalledAnalogueChannel(channelno)
#define rins_GetFirstIntalledRadioChannel(channelno)	rins->GetFirstIntalledRadioChannel(channelno)
#define rins_GetFirstInstalledChannel(channelno)	rins->GetFirstInstalledChannel(channelno)
#define rins_GetNetworkNameForNetworkID(networkID,NetworkName)	rins->GetNetworkNameForNetworkID(networkID,NetworkName)
#define rins_GetListOfNetworkIDs(NumberOfEntries,NetworkIDList)	rins->GetListOfNetworkIDs(NumberOfEntries,NetworkIDList)
#define rins_IsValidNetworkId(networkID)	rins->IsValidNetworkId(networkID)
#define rins_SetLowestNetworkId(networkID)	rins->SetLowestNetworkId(networkID)
#define rins_SetManualFrequency(frequency,offset,finetune)	rins->SetManualFrequency(frequency,offset,finetune)
#define rins_GetManualFrequency(frequency,offset,finetune)	rins->GetManualFrequency(frequency,offset,finetune)
#define rins_SetManualChannel(channel,finetune)	rins->SetManualChannel(channel,finetune)
#define rins_GetManualChannel(channel,finetune)	rins->GetManualChannel(channel,finetune)
#define rins_IsManualInstallationModeSupported(mode)	rins->IsManualInstallationModeSupported(mode)
#define rins_SetManualInstallationMode(mode)	rins->SetManualInstallationMode(mode)
#define rins_GetManualInstallationMode()	rins->GetManualInstallationMode()
#define rins_StoreManualInstallationValues(channel)	rins->StoreManualInstallationValues(channel)
#define rins_AutoStoreManualInstallationValues()	rins->AutoStoreManualInstallationValues()
#define rins_StartFrequencySearch()	rins->StartFrequencySearch()
#define rins_GetSigStrengthRange(measmode,min,max)	rins->GetSigStrengthRange(measmode,min,max)
#define rins_GetSignalstrength(measmode)	rins->GetSignalstrength(measmode)
#define rins_StoreWeakSignalInstallationChannel()	rins->StoreWeakSignalInstallationChannel()
#define rins_GetInstalledWeakSignalChannel()	rins->GetInstalledWeakSignalChannel()
#define rins_GetSignalQualityBer()	rins->GetSignalQualityBer()
#define rins_IsFrequencySearchDirectionSupported(searchup)	rins->IsFrequencySearchDirectionSupported(searchup)
#define rins_SetFrequencySearchDirection(searchup)	rins->SetFrequencySearchDirection(searchup)
#define rins_GetFrequencySearchDirection()	rins->GetFrequencySearchDirection()
#define rins_GetMinFrequency()	rins->GetMinFrequency()
#define rins_GetMaxFrequency()	rins->GetMaxFrequency()
#define rins_GetTunerFrequency()	rins->GetTunerFrequency()
#define rins_SetTunerFrequency(freq,fineTune)	rins->SetTunerFrequency(freq,fineTune)
#define rins_GetFrequency2Channel(chantbl,frequency)	rins->GetFrequency2Channel(chantbl,frequency)
#define rins_GetChannel2CarrierFrequency(chantbl,channel)	rins->GetChannel2CarrierFrequency(chantbl,channel)
#define rins_GetChannel2CentreFrequency(chantbl,channel)	rins->GetChannel2CentreFrequency(chantbl,channel)
#define rins_GetCurrentPass()	rins->GetCurrentPass()
#define rins_GetNoOfPass()	rins->GetNoOfPass()
#define rins_GetCurrentPassType()	rins->GetCurrentPassType()
#define rins_IsMediumSupported(medium)	rins->IsMediumSupported(medium)
#define rins_GetMedium()	rins->GetMedium()
#define rins_SetMedium(medium)	rins->SetMedium(medium)
#define rins_GetInstalledMedium()	rins->GetInstalledMedium()
#define rins_SetInstalledMedium(medium)	rins->SetInstalledMedium(medium)
#define rins_IsTvSystemSupported(tvsystem)	rins->IsTvSystemSupported(tvsystem)
#define rins_SetTvSystem(tvsystem)	rins->SetTvSystem(tvsystem)
#define rins_GetTvSystem()	rins->GetTvSystem()
#define rins_IsColorSystemSupported(colorsystem)	rins->IsColorSystemSupported(colorsystem)
#define rins_SetColorSystem(colorsystem)	rins->SetColorSystem(colorsystem)
#define rins_GetColorSystem()	rins->GetColorSystem()
#define rins_IsValidPTC(medium,PTC)	rins->IsValidPTC(medium,PTC)
#define rins_GetMinPTC(medium)	rins->GetMinPTC(medium)
#define rins_GetMaxPTC(medium)	rins->GetMaxPTC(medium)
#define rins_GetLastPTCFound()	rins->GetLastPTCFound()
#define rins_GetNumberOfPTCsFound()	rins->GetNumberOfPTCsFound()
#define rins_StartSigStrMeas(measmode)	rins->StartSigStrMeas(measmode)
#define rins_StopSigStrMeas(measmode)	rins->StopSigStrMeas(measmode)
#define rins_IsSignalStrengthMeasurementValid(measmode)	rins->IsSignalStrengthMeasurementValid(measmode)
#define rins_ScanNone	IHsvInstallation2_ScanNone
#define rins_ScanAnalog	IHsvInstallation2_ScanAnalog
#define rins_ScanDVBT	IHsvInstallation2_ScanDVBT
#define rins_ScanDVBC	IHsvInstallation2_ScanDVBC
#define rins_ScanDVBS	IHsvInstallation2_ScanDVBS
#define rins_AttributeScanMode	IHsvInstallation2_AttributeScanMode
#define rins_AttributeSymbolRate	IHsvInstallation2_AttributeSymbolRate
#define rins_AttributeNetworkId	IHsvInstallation2_AttributeNetworkId
#define rins_AttributeNetworkFreq	IHsvInstallation2_AttributeNetworkFreq
#define rins_AttributeModulation	IHsvInstallation2_AttributeModulation
#define rins_AttributeDigitalOption	IHsvInstallation2_AttributeDigitalOption
#define rins_AttributeFreqStepSize	IHsvInstallation2_AttributeFreqStepSize
#define rins_AttributeCity	IHsvInstallation2_AttributeCity
#define rins_AttributePrimaryRegion	IHsvInstallation2_AttributePrimaryRegion
#define rins_AttributeSecondaryRegion	IHsvInstallation2_AttributeSecondaryRegion
#define rins_AttributeTertiaryRegion	IHsvInstallation2_AttributeTertiaryRegion
#define rins_AttributeScrOrFTA	IHsvInstallation2_AttributeScrOrFTA
#define rins_AttributeNetworkOperator	IHsvInstallation2_AttributeNetworkOperator
#define rins_AttributeUpdateInstall	IHsvInstallation2_AttributeUpdateInstall
#define rins_AttributeAnalogEnabled	IHsvInstallation2_AttributeAnalogEnabled
#define rins_AttributePersistentFile	IHsvInstallation2_AttributePersistentFile
#define rins_AttributeLCNSorting	IHsvInstallation2_AttributeLCNSorting
#define rins_AttributeFavoriteChannelId	IHsvInstallation2_AttributeFavoriteChannelId
#define rins_QuickScan	IHsvInstallation2_QuickScan
#define rins_FullScan	IHsvInstallation2_FullScan
#define rins_GridScan	IHsvInstallation2_GridScan
#define rins_AutomaticValue	IHsvInstallation2_AutomaticValue
#define rins_ManualValue	IHsvInstallation2_ManualValue
#define rins_GetAttributeRange(installationmode,attribute,minValue,maxValue)	rins->GetAttributeRange(installationmode,attribute,minValue,maxValue)
#define rins_SetAttributeMode(installationmode,attribute,attributeMode)	rins->SetAttributeMode(installationmode,attribute,attributeMode)
#define rins_SetAttribute(installationmode,attribute,value)	rins->SetAttribute(installationmode,attribute,value)
#define rins_GetAttributeMode(installationmode,attribute)	rins->GetAttributeMode(installationmode,attribute)
#define rins_GetAttribute(installationmode,attribute)	rins->GetAttribute(installationmode,attribute)
#define rins_IsAvailable(installationmode,attribute)	rins->IsAvailable(installationmode,attribute)
#define rins_ResetAttributeToDefault(installationmode,attribute)	rins->ResetAttributeToDefault(installationmode,attribute)
#define rins_ResetAttributeToPersistent(installationmode,attribute)	rins->ResetAttributeToPersistent(installationmode,attribute)
#define rins_NitNone	IHsvInstallation2_NitNone
#define rins_NitActual	IHsvInstallation2_NitActual
#define rins_NitOther	IHsvInstallation2_NitOther
#define rins_GetTargetNitType(NetworkId)	rins->GetTargetNitType(NetworkId)
#define rins_IsNetworkUpdateDetected()	rins->IsNetworkUpdateDetected()
#define rins_DVBCStepSize1	IHsvInstallation2_DVBCStepSize1
#define rins_DVBCStepSize8	IHsvInstallation2_DVBCStepSize8
#define rins_Initialise()	rins->Initialise()
#define rins_SkipInstallationScans(ScanTypes)	rins->SkipInstallationScans(ScanTypes)
#define rins_GetAltTSValues(ONID,TSID)	rins->GetAltTSValues(ONID,TSID)
#define rins_SetUserSymbolRates(installationmode,values,len)	rins->SetUserSymbolRates(installationmode,values,len)
#define rins_GetUserSymbolRates(installationmode,values,len)	rins->GetUserSymbolRates(installationmode,values,len)
#define rins_GetPredefinedSymbolRates(installationmode,values,len)	rins->GetPredefinedSymbolRates(installationmode,values,len)
#define rins_GetNetworkIDList()	rins->GetNetworkIDList()
#define rins_GetNetworkIDName(index,NetworkName)	rins->GetNetworkIDName(index,NetworkName)
#define rins_GetChannelListIDName(index,ChannelistName)	rins->GetChannelListIDName(index,ChannelistName)
#define rins_SetFavouriteNetworkID(mode,attrib,index)	rins->SetFavouriteNetworkID(mode,attrib,index)
#define rins_GetNumberOfChannelListIds()	rins->GetNumberOfChannelListIds()
#define rins_GetChannelListIdByIndex(index)	rins->GetChannelListIdByIndex(index)
#define rins_SetFavouriteChannelListId(mode,attrib,index)	rins->SetFavouriteChannelListId(mode,attrib,index)
#define rins_SetFavouriteRegion(mode,index,RegionType)	rins->SetFavouriteRegion(mode,index,RegionType)
#define rins_None	IHsvInstallation2_None
#define rins_Ziggo	IHsvInstallation2_Ziggo
#define rins_UPC	IHsvInstallation2_UPC
#define rins_UnityMedia	IHsvInstallation2_UnityMedia
#define rins_Kdg	IHsvInstallation2_Kdg
#define rins_Telenet	IHsvInstallation2_Telenet
#define rins_RCSRDS	IHsvInstallation2_RCSRDS
#define rins_SetUserSelectConflictService(LcnIndex,SvcIndex)	rins->SetUserSelectConflictService(LcnIndex,SvcIndex)
#define rins_ConflictsSelectionDone(UserSelection)	rins->ConflictsSelectionDone(UserSelection)
#define rins_GetConflictServices(ConflictList,NumRecords)	rins->GetConflictServices(ConflictList,NumRecords)
#define rins_GetInstallationVersion()	rins->GetInstallationVersion()
#define rins_GetInstallationState()	rins->GetInstallationState()
#define rins_GetPLPIds(PLPIds)	rins->GetPLPIds(PLPIds)
#define rins_GetRegionList(RegionsData)	rins->GetRegionList(RegionsData)
#define rins_UserSelectionDone(UserSelection)	rins->UserSelectionDone(UserSelection)
#define rins_GetFavouriteRegion(mode,RegionType)	rins->GetFavouriteRegion(mode,RegionType)
#define rins_GetStreamPriority()	rins->GetStreamPriority()
#define rins_SetStreamPriority(prio)	rins->SetStreamPriority(prio)
#define rins_GetConstellation()	rins->GetConstellation()
#define rins_GetSymbolRate()	rins->GetSymbolRate()
#define rins_GetHierarchyMode()	rins->GetHierarchyMode()
#define rins_GetEpgBarkerMux(OnId,TsId)	rins->GetEpgBarkerMux(OnId,TsId)
#define rins_ZiggoNetworkDataSet(ActionValue)	rins->ZiggoNetworkDataSet(ActionValue)
#define rins_ClearPersistent()	rins->ClearPersistent()
#define rins_GetActiveMedium()	rins->GetActiveMedium()
#define sysset_iPresent() (sysset.Present())
#define sysset_AudioFormatStandard	IHsvTcSystemSettings_AudioFormatStandard
#define sysset_AudioFormatAdvanced	IHsvTcSystemSettings_AudioFormatAdvanced
#define sysset_SetSystemLanguage(lang)	sysset->SetSystemLanguage(lang)
#define sysset_GetSystemLanguage()	sysset->GetSystemLanguage()
#define sysset_SetPreferredPrimaryAudioLanguage(lang)	sysset->SetPreferredPrimaryAudioLanguage(lang)
#define sysset_GetPreferredPrimaryAudioLanguage()	sysset->GetPreferredPrimaryAudioLanguage()
#define sysset_GetPreferredSecondarySubtitleLanguage()	sysset->GetPreferredSecondarySubtitleLanguage()
#define sysset_SetPreferredSecondarySubtitleLanguage(lang)	sysset->SetPreferredSecondarySubtitleLanguage(lang)
#define sysset_GetPreferredSecondaryAudioLanguage()	sysset->GetPreferredSecondaryAudioLanguage()
#define sysset_SetPreferredSecondaryAudioLanguage(lang)	sysset->SetPreferredSecondaryAudioLanguage(lang)
#define sysset_SetPreferredPrimarySubtitleLanguage(lang)	sysset->SetPreferredPrimarySubtitleLanguage(lang)
#define sysset_GetPreferredPrimarySubtitleLanguage()	sysset->GetPreferredPrimarySubtitleLanguage()
#define sysset_SetPreferredAudioFormat(format)	sysset->SetPreferredAudioFormat(format)
#define sysset_GetPreferredAudioFormat()	sysset->GetPreferredAudioFormat()
#define sysset_SetPreferredPrimaryTxtLanguage(lang)	sysset->SetPreferredPrimaryTxtLanguage(lang)
#define sysset_GetPreferredPrimaryTxtLanguage()	sysset->GetPreferredPrimaryTxtLanguage()
#define sysset_SetPreferredSecondaryTxtLanguage(lang)	sysset->SetPreferredSecondaryTxtLanguage(lang)
#define sysset_GetPreferredSecondaryTxtLanguage()	sysset->GetPreferredSecondaryTxtLanguage()
#define sysset_SetSystemCountry(country)	sysset->SetSystemCountry(country)
#define sysset_GetSystemCountry()	sysset->GetSystemCountry()
#define sysset_SetInstallCountry(country)	sysset->SetInstallCountry(country)
#define sysset_GetInstallCountry()	sysset->GetInstallCountry()
#define sysset_SetInstallCity(city)	sysset->SetInstallCity(city)
#define sysset_SetSystemCity(city)	sysset->SetSystemCity(city)
#define sysset_GetInstallCity()	sysset->GetInstallCity()
#define sysset_GetSystemCity()	sysset->GetSystemCity()
#define isortroute_stubsort	IHsvSortRoute_stubsort
#define isortroute_dvbtsort	IHsvSortRoute_dvbtsort
#define isortroute_dvbcsort	IHsvSortRoute_dvbcsort
#define isortroute_blizoosort	IHsvSortRoute_blizoosort
#define isortroute_blizoosort	IHsvSortRoute_blizoosort
#define isortroute_norsort	IHsvSortRoute_norsort
#define isortroute_dvbclitesort	IHsvSortRoute_dvbclitesort
#define isortroute_dvbtlitesort	IHsvSortRoute_dvbtlitesort
#define isortroute_italysort	IHsvSortRoute_italysort
#define isortroute_dvbt2sort	IHsvSortRoute_dvbt2sort
#define isortroute_finsort	IHsvSortRoute_finsort
#define isortroute_apmeasort	IHsvSortRoute_apmeasort
#define isortroute_hungarysort	IHsvSortRoute_hungarysort
#else //GENERATE__LEGACY__DEFINES
#ifdef CLASSSCOPE
#undef CLASSSCOPE
#endif
#ifdef FPCALL
#undef FPCALL
#endif
#ifdef NOCLASS
#undef NOCLASS
#endif
#define LOCAL_UNDEFINES
#include "locals_mSortRoute.h"
#undef LOCAL_UNDEFINES
#endif //GENERATE__LEGACY__DEFINES
#endif

