#ifndef  _CHSVUTIL_GPIMWCHAR_PRIV_H
#define  _CHSVUTIL_GPIMWCHAR_PRIV_H 

#include <InfraGlobals.h>
#include <provreq.h>
#include <IAppApiMultiLingualStringConversion.h>
#include <CS2MwBase.h>
class CHsvUtil_gpimwchar_Priv;
#define CLASSSCOPE CHsvUtil_gpimwchar_Priv::
#include "locals_gpimwchar.h"

class CHsvUtil_gpimwchar_Priv : public CS2MwBase
{
public:
virtual ~CHsvUtil_gpimwchar_Priv();

private:
void params__init(void);
private:
#define MEMBERVARS
#include "locals_gpimwchar.h"
#undef MEMBERVARS
//Provided interfaces
private:
IAppApiMultiLingualStringConversionImpl(CHsvUtil_gpimwchar_Priv,ling);
public:
ProvidesInterface<IAppApiMultiLingualStringConversion>	ling;


public:
CHsvUtil_gpimwchar_Priv():i__ling(this)
{
ling	=	&i__ling;
module__init();
params__init();
}

};

#ifdef GENERATE__LEGACY__DEFINES
#define ling_RESULT_OK	IAppApiMultiLingualStringConversion_RESULT_OK
#define ling_RESULT_ERROR_INVALID_TABLE	IAppApiMultiLingualStringConversion_RESULT_ERROR_INVALID_TABLE
#define ling_RESULT_DESTINATION_TOO_SMALL	IAppApiMultiLingualStringConversion_RESULT_DESTINATION_TOO_SMALL
#define ling_RESULT_NON_EVEN_SIZE	IAppApiMultiLingualStringConversion_RESULT_NON_EVEN_SIZE
#define ling_TableDefault	IAppApiMultiLingualStringConversion_TableDefault
#define ling_TableLatin1	IAppApiMultiLingualStringConversion_TableLatin1
#define ling_TableISO8859_1	IAppApiMultiLingualStringConversion_TableISO8859_1
#define ling_TableLatin2	IAppApiMultiLingualStringConversion_TableLatin2
#define ling_TableISO8859_2	IAppApiMultiLingualStringConversion_TableISO8859_2
#define ling_TableLatin3	IAppApiMultiLingualStringConversion_TableLatin3
#define ling_TableISO8859_3	IAppApiMultiLingualStringConversion_TableISO8859_3
#define ling_TableLatin4	IAppApiMultiLingualStringConversion_TableLatin4
#define ling_TableISO8859_4	IAppApiMultiLingualStringConversion_TableISO8859_4
#define ling_TableCyrillic	IAppApiMultiLingualStringConversion_TableCyrillic
#define ling_TableISO8859_5	IAppApiMultiLingualStringConversion_TableISO8859_5
#define ling_TableArabic	IAppApiMultiLingualStringConversion_TableArabic
#define ling_TableISO8859_6	IAppApiMultiLingualStringConversion_TableISO8859_6
#define ling_TableGreek	IAppApiMultiLingualStringConversion_TableGreek
#define ling_TableISO8859_7	IAppApiMultiLingualStringConversion_TableISO8859_7
#define ling_TableHebrew	IAppApiMultiLingualStringConversion_TableHebrew
#define ling_TableISO8859_8	IAppApiMultiLingualStringConversion_TableISO8859_8
#define ling_TableLatin5	IAppApiMultiLingualStringConversion_TableLatin5
#define ling_TableISO8859_9	IAppApiMultiLingualStringConversion_TableISO8859_9
#define ling_TableLatin6	IAppApiMultiLingualStringConversion_TableLatin6
#define ling_TableISO8859_10	IAppApiMultiLingualStringConversion_TableISO8859_10
#define ling_TableThai	IAppApiMultiLingualStringConversion_TableThai
#define ling_TableISO8859_11	IAppApiMultiLingualStringConversion_TableISO8859_11
#define ling_TableLatin7	IAppApiMultiLingualStringConversion_TableLatin7
#define ling_TableISO8859_13	IAppApiMultiLingualStringConversion_TableISO8859_13
#define ling_TableLatin8	IAppApiMultiLingualStringConversion_TableLatin8
#define ling_TableISO8859_14	IAppApiMultiLingualStringConversion_TableISO8859_14
#define ling_TableLatin9	IAppApiMultiLingualStringConversion_TableLatin9
#define ling_TableISO8859_15	IAppApiMultiLingualStringConversion_TableISO8859_15
#define ling_TableLatin10	IAppApiMultiLingualStringConversion_TableLatin10
#define ling_TableISO8859_16	IAppApiMultiLingualStringConversion_TableISO8859_16
#define ling_TableLegacyCyrillic	IAppApiMultiLingualStringConversion_TableLegacyCyrillic
#define ling_TableLegacyArabic	IAppApiMultiLingualStringConversion_TableLegacyArabic
#define ling_TableLegacyGreek	IAppApiMultiLingualStringConversion_TableLegacyGreek
#define ling_TableLegacyHebrew	IAppApiMultiLingualStringConversion_TableLegacyHebrew
#define ling_TableLegacyLatin5	IAppApiMultiLingualStringConversion_TableLegacyLatin5
#define ling_TableLegacyLatin2	IAppApiMultiLingualStringConversion_TableLegacyLatin2
#define ling_TableUcs2	IAppApiMultiLingualStringConversion_TableUcs2
#define ling_TableChinese	IAppApiMultiLingualStringConversion_TableChinese
#define ling_TableUtf8	IAppApiMultiLingualStringConversion_TableUtf8
#define ling_TableWindows1250	IAppApiMultiLingualStringConversion_TableWindows1250
#define ling_TableWindows1251	IAppApiMultiLingualStringConversion_TableWindows1251
#define ling_TableWindows1252	IAppApiMultiLingualStringConversion_TableWindows1252
#define ling_TableWindows1253	IAppApiMultiLingualStringConversion_TableWindows1253
#define ling_TableWindows1254	IAppApiMultiLingualStringConversion_TableWindows1254
#else //GENERATE__LEGACY__DEFINES
#ifdef CLASSSCOPE
#undef CLASSSCOPE
#endif
#ifdef FPCALL
#undef FPCALL
#endif
#ifdef NOCLASS
#undef NOCLASS
#endif
#define LOCAL_UNDEFINES
#include "locals_gpimwchar.h"
#undef LOCAL_UNDEFINES
#endif //GENERATE__LEGACY__DEFINES
#endif

