/******************************************************************************* 
*              Copyright(c) 2004 Philips Innovation Campus. 
*           All rights reserved. Reproduction in whole or in part is 
*        prohibited without the written consent of the copyright holder. 
* 
*              Project: PEARS 
*               Source: Include File   
*             Filename: GermanyKDGRankingList.h 
*        Creation date: Mon Mar 16 13:09:28 2009 
*               Author: pavangs 
*       %date_modified: Mon Mar 16 13:09:51 2009 % 
*          %created_by: nareshj % 
*             %version: TVG_tv550r4dev1_2 % 
* 
* Description : 
* 
*******************************************************************************/ 

/* Sorting for KDG Network should be in the following order 
   ServiceName is not used basically but mentioned here for understanding purpose :) */	

            /*	ServiceName				    ServiceId */

		
/* Radio Services */
				
SVC_ITEM	(	Antenne_Brandenburg,		0x6F26	),
SVC_ITEM	(	Bayern_1,					0x6EF0	),
SVC_ITEM	(	Bayern_2,					0x6EF1	),
SVC_ITEM	(	Bayern_3,					0x6EF2	),
SVC_ITEM	(	Bayern_4_Klassik,			0x6EF3	),
SVC_ITEM	(	DLF,						0x6D6D	),
SVC_ITEM	(	HR_1,						0x6F03	),
SVC_ITEM	(	HR_2,						0x6F04	),
SVC_ITEM	(	HR_3,						0x6F05	),
SVC_ITEM	(	HR_4,						0x6F06	),
SVC_ITEM	(	MDR_1_S_Anhalt,			    0x6F0D	),
SVC_ITEM	(	MDR_1_Sachsen,				0x6F0C	),
SVC_ITEM	(	MDR_1_Thuringen,			0x6F0E	),
SVC_ITEM	(	NDR_1_Niedersachsen,		0x6F1C	),
SVC_ITEM	(	NDR_1_Radio_MV,			    0x6F1B	),
SVC_ITEM	(	NDR_1_Welle_Nord,			0x6F1A	),
SVC_ITEM	(	NDR_2,						0x6F15	),
SVC_ITEM	(	SR_1,						0x6F2D	),
SVC_ITEM	(	SR_2,						0x6F2E	),
SVC_ITEM	(	SR_3,						0x6F2F	),
SVC_ITEM	(	SWR1_BW,					0x6F31	),
SVC_ITEM	(	SWR1_RP,					0x6F32	),
SVC_ITEM	(	SWR_2,						0x6F33	),
SVC_ITEM	(	SWR_3,						0x6F34	),
SVC_ITEM	(	SWR_4_BW,					0x6F35	),
SVC_ITEM	(	SWR_4_RP,					0x6F36	),
SVC_ITEM	(	WDR_2,						0x6F3C	),
SVC_ITEM	(	WDR_3,						0x6F3D	),
SVC_ITEM	(	WDR_4,						0x6F3E	),
SVC_ITEM	(	WDR_5,						0x6F3F	),

/* TV Services */

SVC_ITEM	(	Das_Erste_HD,               0x2B5C	),
SVC_ITEM	(	ZDF_HD,                     0x2B66	),
SVC_ITEM	(	NDR_FS_HH,                  0x6E41	),
SVC_ITEM	(	SAT_1,                      0xD17A	),
SVC_ITEM	(	RTL_Television,             0xD161	),
SVC_ITEM	(	RTL_II,                     0xD163	),
SVC_ITEM	(	Super_RTL,                  0xD162	),
SVC_ITEM	(	Pro_Sieben,                 0xD175	),
SVC_ITEM	(	Kabel_Eins,                 0xD176	),
SVC_ITEM	(	VOX,                        0xD164	),
SVC_ITEM	(	Das_Vierte,                 0xD168	),
SVC_ITEM	(	Arte,                       0x7034	),
SVC_ITEM	(	3SAT,                       0x6D67	),
SVC_ITEM	(	Eins_Extra,                 0x7031	),
SVC_ITEM	(	Eins_Plus,                  0x7033	),
SVC_ITEM	(	EinsFestival,               0x7032	),
SVC_ITEM	(	Phoenix,                    0x7035	),
SVC_ITEM	(	ZDF_Neo_,                   0x6D6E	),
SVC_ITEM	(	ZDF_Infokanal,              0x6D6B	),
SVC_ITEM	(	ZDF_Theaterkanal,           0x6D70	),
SVC_ITEM	(	KiKa,                       0x6D68	),
SVC_ITEM	(	NICK,                       0xCF0E	),
SVC_ITEM	(	EuroNews,                   0xD179	),
SVC_ITEM	(	N_TV,                       0xD166	),
SVC_ITEM	(	N_24,                       0xD17B	),
SVC_ITEM	(	Sport_1,                    0xD178	),
SVC_ITEM	(	Eurosport,                  0xD167	),
SVC_ITEM	(	DMAX,                       0xD171	),
SVC_ITEM	(	Channel_21,                 0xD10A	),
SVC_ITEM	(	QVC,                        0xD170	),
SVC_ITEM	(	HSE_24,                     0xD17E	),
SVC_ITEM	(	Juwelo_TV,                  0xD173	),
SVC_ITEM	(	WDR_Köln,                   0x6DCF	),
SVC_ITEM	(	HR_Fernsehen,               0x6DCC	),
SVC_ITEM	(	NDR_FS_MV,                  0x6E40	),
SVC_ITEM	(	NDR_FS_NDS,                 0x6E42	),
SVC_ITEM	(	NDR_FS_SH,                  0x6E43	),
SVC_ITEM	(	MDR_Sachsen,                0x6E44	),
SVC_ITEM	(	MDR_S_Anhalt,               0x6E45	),
SVC_ITEM	(	MDR_Thüringen,              0x6E46	),
SVC_ITEM	(	SWR_Fernsehen_RP,           0x6E47	),
SVC_ITEM	(	SWR_Fernsehen_BW,           0x6DD1	),
SVC_ITEM	(	BR_alpha,                   0x6F47	),
SVC_ITEM	(	Bayerisches_FS_Nord,        0x6DCE	),
SVC_ITEM	(	Bayerisches_FS_Süd,         0x6DCB	),
SVC_ITEM	(	Rbb_Berlin,                 0x6E2E	),
SVC_ITEM	(	Rbb_Brandenburg,            0x6E2D	),
SVC_ITEM	(	Radio_Bremen_TV,            0xCB22	),
SVC_ITEM	(	SR_Fernsehen,               0x6F46	),
SVC_ITEM	(	VIVA,                       0xD169	),
SVC_ITEM	(	Deluxe_Music,               0xCF76	),
SVC_ITEM	(	iMusic_1,                   0xD172	),
SVC_ITEM	(	Annixe_SD,                  0xCF77	),
SVC_ITEM	(	Tele_5,                     0xCF0A	),
SVC_ITEM	(	ERF_eins,                   0xD10B	),
SVC_ITEM	(	Sonnenklar_TV,              0xD16F	),
SVC_ITEM	(	Bibel_TV,                   0xD09B	),
SVC_ITEM	(	9Live,                      0xD177	),
SVC_ITEM	(	Astro_TV,                   0xD16C	),
SVC_ITEM	(	Kabel_Digital_Info,         0xCF17	),
SVC_ITEM	(	redXClub_Infokanal,         0xC499	),
SVC_ITEM	(	Select_Kino_Infokanal,      0xC490	),
SVC_ITEM	(	Sky_Cinema_HD,              0x0083	),
SVC_ITEM	(	Sky_Cinema,                 0x000A	),
SVC_ITEM	(	Sky_Cinema_1,               0x000B	),
SVC_ITEM	(	Sky_Cinema_24,              0x002B	),
SVC_ITEM	(	Sky_Action,                 0x0009	),
SVC_ITEM	(	Sky_Comedy,                 0x0008	),
SVC_ITEM	(	Sky_Emotion,                0x0014	),
SVC_ITEM	(	Sky_Nostalgie,              0x0204	),
SVC_ITEM	(	Sky_Cinema_Hits,            0x0029	),
SVC_ITEM	(	Disney_Cinemagic_HD,        0x007E	),
SVC_ITEM	(	Disney_Cinemagic,           0x0019	),
SVC_ITEM	(	MGM,                        0x0203	),
SVC_ITEM	(	Sky_Sport_Info,             0x0011	),
SVC_ITEM	(	Sky_Sport_1,                0x00DD	),
SVC_ITEM	(	Sky_Sport_2,                0x00DE	),
SVC_ITEM	(	Sky_Bundesliga,             0x00DF	),
SVC_ITEM	(	Sky_Sport_HD_1,             0x0081	),
SVC_ITEM	(	Eurosport_HD,               0x0084	),
SVC_ITEM	(	Sky_Select,                 0x0012	),
SVC_ITEM	(	Blue_Movie,                 0x0201	),
SVC_ITEM	(	Discovery_HD,               0x0082	),
SVC_ITEM	(	Discovery_Channel,          0x000E	),
SVC_ITEM	(	National_Geographic,        0x000D	),
SVC_ITEM	(	Nat_Geo_HD,                 0x007F	),
SVC_ITEM	(	NatGeo_Wild,                0x000C	),
SVC_ITEM	(	History_HD,                 0x0080	),
SVC_ITEM	(	Spiegel_Geschichte,         0x0034	),
SVC_ITEM	(	Motorvision_TV,             0x00A8	),
SVC_ITEM	(	Sky_Krimi,                  0x0017	),
SVC_ITEM	(	13th_Street,                0x002A	),
SVC_ITEM	(	RTL_Crime,                  0x001B	),
SVC_ITEM	(	RTL_Passion,                0x001D	),
SVC_ITEM	(	Fox_Serie,                  0x0010	),
SVC_ITEM	(	TNT_Serie,                  0x0032	),
SVC_ITEM	(	Syfy,                       0x0024	),
SVC_ITEM	(	Beate_UhseTV,               0x0015	),
SVC_ITEM	(	Heimatkanal,                0x0016	),
SVC_ITEM	(	Goldstar_TV,                0x0206	),
SVC_ITEM	(	Classica,                   0x0018	),
SVC_ITEM	(	Disney_Channel,             0x0022	),
SVC_ITEM	(	Disney_XD,                  0x001C	),
SVC_ITEM	(	Playhouse_Disney,           0x001A	),
SVC_ITEM	(	Junior,                     0x0013	),
SVC_ITEM	(	Al_Jazeera_int_engl,        0xD16E	),
SVC_ITEM	(	ANN_arab,                   0xD04A	),
SVC_ITEM	(	BBC_World_engl,             0xCF09	),
SVC_ITEM	(	Bebe_TV,                    0xC760	),
SVC_ITEM	(	Bloomberg_TV_engl,          0xCF0C	),
SVC_ITEM	(	BVN_dutch,                  0xD046	),
SVC_ITEM	(	CaspioNet_russ,             0xC75F	),
SVC_ITEM	(	CNBC_Europe_engl,           0xC616	),
SVC_ITEM	(	CNN_international_engl,     0xD16D	),
SVC_ITEM	(	Daystar_TV_engl,            0xD165	),
SVC_ITEM	(	EuroNews_frz,               0xCFDB	),
SVC_ITEM	(	France_2_frz,               0xD10D	),
SVC_ITEM	(	France_3_frz,               0xD10E	),
SVC_ITEM	(	France_24_frz,              0xC759	),
SVC_ITEM	(	GOD_TV_engl,                0xC75D	),
SVC_ITEM	(	Iran_Music_PDF_chan_pers,   0xD047	),
SVC_ITEM	(	LTV_World_lit,              0xC762	),
SVC_ITEM	(	Phoenix_CNE_chin,           0xC75B	),
SVC_ITEM	(	Press_TV_engl,              0xC3B5	),
SVC_ITEM	(	Pro_TV_TVR_Intl_rom,        0xD03A	),
SVC_ITEM	(	RTVi_Info_russ,             0xCFD1	),
SVC_ITEM	(	Russia_Today_engl,          0xCF7F	),
SVC_ITEM	(	Sky_News_engl,              0xD049	),
SVC_ITEM	(	The_Poker_Channel_engl,     0xD03B	),
SVC_ITEM	(	TRTi_türk,                  0xCFE3	),
SVC_ITEM	(	TV5_MONDE_frz,              0xCF0F	),
SVC_ITEM	(	TV_Canarias_esp,            0xD04C	),
SVC_ITEM	(	TV_record_port,             0xC763	)

