/*TV Services*/			

SVC_ITEM ( Das Erste HD,	0x2B5C),		
SVC_ITEM ( ZDF HD,	0x2B66),		
SVC_ITEM ( NDR FS HH HD,	0x2859),		
SVC_ITEM ( SAT.1,	0xD17A),		
SVC_ITEM ( RTL,	0xD161),		
SVC_ITEM ( RTL II,	0xD163),		
SVC_ITEM ( ProSieben,	0xD175),		
SVC_ITEM ( ARTE HD,	0x2B70),		
SVC_ITEM ( VOX,	0xD164),		
SVC_ITEM ( TELE 5,	0xCF0A),		
SVC_ITEM ( ProSieben Maxx,	0xCF11),		
SVC_ITEM ( ServusTV,	0xD174),		
SVC_ITEM ( SAT.1 Gold,	0xD04C),		
SVC_ITEM ( Bibel TV,	0xD09B),		
SVC_ITEM ( sixx,	0xC60C),		
SVC_ITEM ( kabel eins,	0xD176),		
SVC_ITEM ( SUPER RTL,	0xD162),		
SVC_ITEM ( QVC,	0xD170),		
SVC_ITEM ( HSE24,	0xD17E),		
SVC_ITEM ( Juwelo TV,	0xD173),		
SVC_ITEM ( Channel21,	0xD10A),		
SVC_ITEM ( 3sat HD,	0x2B8E),		
SVC_ITEM ( EinsPlus,	0x7033),		
SVC_ITEM ( zdf_neo HD,	0x2B7A),		
SVC_ITEM ( EinsFestival,	0x7032),		
SVC_ITEM ( ZDFinfokanal,	0x6D6B),		
SVC_ITEM ( QVC PLUS,	0xC61A),		
SVC_ITEM ( HSE24 EXTRA,	0xC756),		
SVC_ITEM ( Rock TV,	0xCF73),		
SVC_ITEM ( zdf.kultur,	0x6D70),		
SVC_ITEM ( Deutsches Musik Fernsehen,	0xCF14),		
SVC_ITEM ( Folx.TV,	0xCF75),		
SVC_ITEM ( KiKA HD,	0x2B98),		
SVC_ITEM ( PhoCNE/,	0xC75B),		
SVC_ITEM ( tagesschau24,	0x7031),		
SVC_ITEM ( PHOENIX HD,	0x285B),		
SVC_ITEM ( euronews,	0xD179),		
SVC_ITEM ( n-tv,	0xD166),		
SVC_ITEM ( N24,	0xD17B),		
SVC_ITEM ( Bloomberg (eng),	0xCF0C),		
SVC_ITEM ( SR Fernsehen,	0x6F46),		
SVC_ITEM ( ARD-alpha,	0x6F47),		
SVC_ITEM ( Bayerisches Fernsehen Süd HD,	0x2855),		
SVC_ITEM ( hr-fernsehen HD,	0x2873),		
SVC_ITEM ( MDR Sachsen HD,	0x2870),		
SVC_ITEM ( SWR BW HD,	0x283F),		
SVC_ITEM ( rbb Berlin HD,	0x286F),		
SVC_ITEM ( WDR Köln HD,	0x6EA5),		
SVC_ITEM ( SPORT1,	0xD178),		
SVC_ITEM ( Eurosport,	0xD167),		
SVC_ITEM ( DMAX,	0xD171),		
SVC_ITEM ( RTL NITRO,	0xCF76),		
SVC_ITEM ( Comedy Central / VIVA,	0xD169),		
SVC_ITEM ( Deluxe Music,	0xD04B),		
SVC_ITEM ( CNBC Europe (eng),	0xD049),		
SVC_ITEM ( BBC World News (eng),	0xCF09),		
SVC_ITEM ( Romance TV,	0xD0A5),		
SVC_ITEM ( NDR FS MV HD,	0x2858),		
SVC_ITEM ( NDR FS NDS HD,	0x2857),		
SVC_ITEM ( NDR FS SH HD,	0x285A),		
SVC_ITEM ( rbb Brandenburg HD,	0x286E),		
SVC_ITEM ( SWR Fernsehen RP HD,	0x2840),		
SVC_ITEM ( MDR Thüringen HD,	0x2872),		
SVC_ITEM ( MDR S-Anhalt HD,	0x2871),		
SVC_ITEM ( Bayerisches Fernsehen Nord HD,	0x2856),		
SVC_ITEM ( i24 news (eng),	0xC760),		
SVC_ITEM ( ANIXE SD,	0xCF77),		
SVC_ITEM ( TLC,	0xCFE4),		
SVC_ITEM ( Welt der Wunder TV,	0xC757),		
SVC_ITEM ( DRF1,	0xCF1A),		
SVC_ITEM ( BVN (dut),	0xD046),		
SVC_ITEM ( Pro TV/,	0xD03A),		
SVC_ITEM ( 1-2-3.tv,	0xC3BE),		
SVC_ITEM ( Duna TV (hun),	0xC75F),		
SVC_ITEM ( sonnenklar.TV,	0xD16F),		
SVC_ITEM ( tv8 (tur),	0xD106),		
SVC_ITEM ( Russia Today (eng),	0xCF7F),		
SVC_ITEM ( GOD TV (eng),	0xC75D),		
SVC_ITEM ( GINX TV (lit/eng),	0xD03B),		
SVC_ITEM ( Al Jazeera Int (eng),	0xD16E),		
SVC_ITEM ( Astro TV,	0xD16C),		
SVC_ITEM ( Arirang TV/,	0xC75C),		
SVC_ITEM ( TV 5 Monde (fre),	0xCF0F),		
SVC_ITEM ( France24 (fre),	0xC759),		
SVC_ITEM ( France 2 (fre),	0xC762),		
SVC_ITEM ( France 3 (fre),	0xD10E),		
SVC_ITEM ( France 5 (fre),	0xC764),		
SVC_ITEM ( euronews (fre),	0xCFDB),		
SVC_ITEM ( euronews (eng),	0xCFDD),		
SVC_ITEM ( euronews (por),	0xCFE1),		
SVC_ITEM ( euronews (rus),	0xCFE2),		
SVC_ITEM ( euronews (spa),	0xCFE0),		
SVC_ITEM ( euronews (ita),	0xCFDF),		
SVC_ITEM ( Kabel Digital Info,	0xCF17),		
SVC_ITEM ( SPIEGEL TV WISSEN HD,	0xC366),		
SVC_ITEM ( Sony Entertainment TV HD,	0xC36E),		
SVC_ITEM ( NatGeo HD (KD),	0xC356),		
SVC_ITEM ( Bon Gusto,	0xD036),		
SVC_ITEM ( Boomerang ,	0xD09C),		
SVC_ITEM ( Sky Action HD,	0x74),		
SVC_ITEM ( Sky Atlantic HD,	0x6E),		
SVC_ITEM ( Sky Bundesliga HD 1,	0x69),		
SVC_ITEM ( Sky Bundesliga HD 2,	0x10B),		
SVC_ITEM ( Sky Bundesliga HD 3,	0x115),		
SVC_ITEM ( Sky Bundesliga HD 4,	0x11F),		
SVC_ITEM ( Sky Cinema HD,	0x83),		
SVC_ITEM ( Sky Sport HD 1,	0x81),		
SVC_ITEM ( Sky Sport HD 2,	0x72),		
SVC_ITEM ( Sky Sport HD 3,	0x10C),		
SVC_ITEM ( Sky Sport HD 4,	0x116),		
SVC_ITEM ( Sky Sport HD 5,	0x120),		
SVC_ITEM ( Sky Sport News HD,	0x6C),		
SVC_ITEM ( Sky Hits HD,	0x6B),		
SVC_ITEM ( 13th Street HD,	0xC354),		
SVC_ITEM ( Discovery HD,	0x82),		
SVC_ITEM ( Disney Cinemagic HD,	0x6F),		
SVC_ITEM ( Disney Jr.HD,	0xC384),		
SVC_ITEM ( Disney XD HD,	0xC383),		
SVC_ITEM ( Eurosport HD,	0x84),		
SVC_ITEM ( FOX HD,	0x7C),		
SVC_ITEM ( HISTORY HD,	0xC371),		
SVC_ITEM ( Nat Geo Wild HD,	0x76),		
SVC_ITEM ( NatGeo HD,	0x70),		
SVC_ITEM ( NatGeo People HD,	0xC370),		
SVC_ITEM ( SPORT1 US HD,	0xCF16),		
SVC_ITEM ( SPORT1+ HD,	0xC355),		
SVC_ITEM ( Syfy HD,	0xC358),		
SVC_ITEM ( TNT Glitz HD,	0xC361),		
SVC_ITEM ( TNT Serie HD,	0xC351),		
SVC_ITEM ( Universal Channel HD,	0xC373),		
SVC_ITEM ( Sky Select,	0x12),		
SVC_ITEM ( Sky Action,	0x9),		
SVC_ITEM ( Sky Atlantic,	0x22),		
SVC_ITEM ( Sky Bundesliga 1,	0xDF),		
SVC_ITEM ( Sky Cinema,	0xA),		
SVC_ITEM ( Sky Cinema +1,	0xB),		
SVC_ITEM ( Sky Cinema +24,	0x2B),		
SVC_ITEM ( Sky Comedy,	0x8),		
SVC_ITEM ( Sky Emotion,	0x14),		
SVC_ITEM ( Sky Hits,	0x29),		
SVC_ITEM ( Sky Krimi,	0x17),		
SVC_ITEM ( Sky Nostalgie,	0x204),		
SVC_ITEM ( Sky Sport 1,	0xDD),		
SVC_ITEM ( Sky Sport 2,	0xDE),		
SVC_ITEM ( Sky Sport News,	0x11),		
SVC_ITEM ( 13th Street,	0x2A),		
SVC_ITEM ( Beate-Uhse.TV,	0x15),		
SVC_ITEM ( Classica,	0x18),		
SVC_ITEM ( CNBC Europe (eng),	0xD049),		
SVC_ITEM ( Discovery Channel SKY,	0xE),		
SVC_ITEM ( Disney Cinemagic,	0x19),		
SVC_ITEM ( Disney Junior SKY,	0x1A),		
SVC_ITEM ( Disney Junior (eng),	0xD109),		
SVC_ITEM ( Disney XD SKY,	0x1C),		
SVC_ITEM ( Disney XD (eng),	0xCF74),		
SVC_ITEM ( FOX,	0xD0A1),		
SVC_ITEM ( Goldstar TV,	0x206),		
SVC_ITEM ( Heimatkanal,	0x16),		
SVC_ITEM ( History,	0xD035),		
SVC_ITEM ( JUKEBOX,	0xCF70),		
SVC_ITEM ( Junior,	0x13),		
SVC_ITEM ( MGM,	0x203),		
SVC_ITEM ( Motorvision TV,	0xA8),		
SVC_ITEM ( Nat Geo Wild,	0xC),		
SVC_ITEM ( NatGeo,	0xC614),		
SVC_ITEM ( NatGeo (eng),	0xCFD8),		
SVC_ITEM ( National Geographic,	0xD),		
SVC_ITEM ( RTL Crime,	0x1B),		
SVC_ITEM ( Spiegel Geschichte,	0x34),		
SVC_ITEM ( Syfy,	0x24),		
SVC_ITEM ( TNT Glitz,	0xD0A2),		
SVC_ITEM ( TNT Serie,	0x32),		
SVC_ITEM ( TNT Serie (eng),	0xD048),		
SVC_ITEM ( Sky Bundesliga 1,	0xDF),		
SVC_ITEM ( Sky Bundesliga 2,	0x106),		
SVC_ITEM ( Sky Bundesliga 3,	0x110),		
SVC_ITEM ( Sky Bundesliga 4,	0x11A),		
SVC_ITEM ( Sky Bundesliga 5,	0x124),		
SVC_ITEM ( Sky Bundesliga 6,	0x12E),		
SVC_ITEM ( Sky Bundesliga 7,	0x138),		
SVC_ITEM ( Sky Bundesliga 8,	0x142),		
SVC_ITEM ( Sky Bundesliga 9,	0x14C),		
SVC_ITEM ( Sky Bundesliga 10,	0xFC),		
			
/*Radio Services*/			
			
SVC_ITEM ( Antenne Brandenburg,         	0x6F26)    ,		
SVC_ITEM ( Bayern 1,         	0x6EF0)    ,		
SVC_ITEM ( Bayern 2,         	0x6EF1)    ,		
SVC_ITEM ( Bayern 3,         	0x6EF2)    ,		
SVC_ITEM ( Bayern 4 Klassik,         	0x6EF3)    ,		
SVC_ITEM ( DLF,         	0x6D6D)    ,		
SVC_ITEM ( HR 1,         	0x6F03)    ,		
SVC_ITEM ( HR 2,         	0x6F04)    ,		
SVC_ITEM ( HR 3,         	0x6F05)    ,		
SVC_ITEM ( HR 4,         	0x6F06)    ,		
SVC_ITEM ( MDR 1 S-Anhalt,         	0x6F0D)    ,		
SVC_ITEM ( MDR 1 Sachsen,         	0x6F0C)    ,		
SVC_ITEM ( MDR 1 Thüringen,         	0x6F0E)    ,		
SVC_ITEM ( NDR 1 Niedersachsen,         	0x6F1C)    ,		
SVC_ITEM ( NDR 1 Radio MV,         	0x6F1B)    ,		
SVC_ITEM ( NDR 1 Welle Nord,         	0x6F1A)    ,		
SVC_ITEM ( NDR 2,         	0x6F15)    ,		
SVC_ITEM ( SR 1,         	0x6F2D)    ,		
SVC_ITEM ( SR 2,         	0x6F2E)    ,		
SVC_ITEM ( SR 3,         	0x6F2F)    ,		
SVC_ITEM ( SWR1 BW,         	0x6F31)    ,		
SVC_ITEM ( SWR1 RP,         	0x6F32)    ,		
SVC_ITEM ( SWR 2,         	0x6F33)    ,		
SVC_ITEM ( SWR 3,         	0x6F34)    ,		
SVC_ITEM ( SWR 4 BW,         	0x6F35)    ,		
SVC_ITEM ( SWR 4 RP,         	0x6F36)    ,		
SVC_ITEM ( WDR 2,         	0x6F3C)    ,		
SVC_ITEM ( WDR 3,         	0x6F3D)    ,		
SVC_ITEM ( WDR 4,         	0x6F3E)    ,		
SVC_ITEM ( WDR 5,         	0x6F3F)		
