/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_droidtv_euinstallertc_model_mwapi_EuInstallerTC */

#ifndef _Included_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
#define _Included_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    CreateInstance
 * Signature: (ILorg/droidtv/euinstallertc/model/mwapi/EuInstallerTC;)I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_CreateInstance
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    DeleteInstance
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_DeleteInstance
  (JNIEnv *, jobject);
  
/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    StartInstallation
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_StartInstallation
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    StopInstallation
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_StopInstallation
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    SetManualFrequency
 * Signature: (IIZ)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_SetManualFrequency
  (JNIEnv *, jobject, jint, jint, jboolean);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetManualFrequency
 * Signature: ()Lorg/droidtv/euinstallertc/model/mwapi/MwDataTypes/ManFreqValues;
 */
JNIEXPORT jobject JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetManualFrequency
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    IsManualInstallationModeSupported
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_IsManualInstallationModeSupported
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    SetManualInstallationMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_SetManualInstallationMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetManualInstallationMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetManualInstallationMode
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    StoreManualInstallationValues
 * Signature: (Lorg/droidtv/euinstallertc/model/mwapi/HsvChannel;)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_StoreManualInstallationValues
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    AutoStoreManualInstallationValues
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_AutoStoreManualInstallationValues
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    StartFrequencySearch
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_StartFrequencySearch
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetTunerFrequency
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetTunerFrequency
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    SetTunerFrequency
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_SetTunerFrequency
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetNumberOfAnalogChannelsFound
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetNumberOfAnalogChannelsFound
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetNumberOfDigitalChannelsFound
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetNumberOfDigitalChannelsFound
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetNumberOfDigitalChannelsRemoved
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetNumberOfDigitalChannelsRemoved
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetInstallationStatus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetInstallationStatus
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetInstallationMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetInstallationMode
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    IsUpdateInstallationSupported
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_IsUpdateInstallationSupported
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    SetManualChannel
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_SetManualChannel
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetManualChannel
 * Signature: ()Lorg/droidtv/euinstallertc/model/mwapi/ManChanInfo;
 */
JNIEXPORT jobject JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetManualChannel
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetSigStrengthRange
 * Signature: (I)Lorg/droidtv/euinstallertc/model/mwapi/SigStrengthRange;
 */
JNIEXPORT jobject JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetSigStrengthRange
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    StoreWeakSignalInstallationChannel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_StoreWeakSignalInstallationChannel
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetInstalledWeakSignalChannel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetInstalledWeakSignalChannel
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    IsFrequencySearchDirectionSupported
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_IsFrequencySearchDirectionSupported
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    SetFrequencySearchDirection
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_SetFrequencySearchDirection
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetFrequencySearchDirection
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetFrequencySearchDirection
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetMinFrequency
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetMinFrequency
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetMaxFrequency
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetMaxFrequency
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetCurrentPass
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetCurrentPass
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetNoOfPass
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetNoOfPass
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetCurrentPassType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetCurrentPassType
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    IsMediumSupported
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_IsMediumSupported
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetMedium
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetMedium
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    SetMedium
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_SetMedium
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    SetInstalledMedium
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_SetInstalledMedium
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    IsTvSystemSupported
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_IsTvSystemSupported
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    SetTvSystem
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_SetTvSystem
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetTvSystem
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetTvSystem
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    IsColorSystemSupported
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_IsColorSystemSupported
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    SetColorSystem
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_SetColorSystem
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetColorSystem
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetColorSystem
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    IsValidPTC
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_IsValidPTC
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetMinPTC
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetMinPTC
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetMaxPTC
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetMaxPTC
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetLastPTCFound
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetLastPTCFound
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetNumberOfPTCsFound
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetNumberOfPTCsFound
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    StartSigStrMeas
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_StartSigStrMeas
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    StopSigStrMeas
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_StopSigStrMeas
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    IsSignalStrengthMeasurementValid
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_IsSignalStrengthMeasurementValid
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetAttributeRange
 * Signature: (II)Lorg/droidtv/euinstallertc/model/mwapi/AttributeRange;
 */
JNIEXPORT jobject JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetAttributeRange
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    SetAttributeMode
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_SetAttributeMode
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    SetAttribute
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_SetAttribute
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetAttributeMode
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetAttributeMode
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetAttribute
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetAttribute
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    IsAvailable
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_IsAvailable
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    ResetAttributeToDefault
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_ResetAttributeToDefault
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    ResetAttributeToPersistent
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_ResetAttributeToPersistent
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetTargetNitType
 * Signature: ()Lorg/droidtv/euinstallertc/model/mwapi/NitType;
 */
JNIEXPORT jobject JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetTargetNitType
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    IsNetworkUpdateDetected
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_IsNetworkUpdateDetected
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    Initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_Initialise
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    SkipInstallationScans
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_SkipInstallationScans
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetAltTSValues
 * Signature: ()Lorg/droidtv/euinstallertc/model/mwapi/TsValues;
 */
JNIEXPORT jobject JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetAltTSValues
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    SetUserSymbolRates
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_SetUserSymbolRates
  (JNIEnv *, jobject, jint, jintArray, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetUserSymbolRates
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetUserSymbolRates
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetPredefinedSymbolRates
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetPredefinedSymbolRates
  (JNIEnv *, jobject, jint);


/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetNumOfChannelList
 * Signature: ()[I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetNumberOfChannelListIds
(JNIEnv *, jobject);
/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetChannelListIdByIndex
 * Signature: ()[I
 */JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetChannelListIdByIndex
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    SetFavoriteChannelListId
 * Signature: (III)[I
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_SetFavouriteChannelListId
(JNIEnv *env, jobject obj, jint mode, jint attrib, jint index);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetChannelListIDName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetChannelListIDName
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetNetworkIDList
 * Signature: ()[I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetNetworkIDList
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetNetworkIDName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetNetworkIDName
  (JNIEnv *, jobject, jint);

  /*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    SetFavouriteNetworkID
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_SetFavouriteNetworkID
  (JNIEnv *env, jobject obj, jint mode, jint attrib, jint index);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    SetFavouriteRegion
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_SetFavouriteRegion
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    SetUserSelectConflictService
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_SetUserSelectConflictService
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    ConflictsSelectionDone
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_ConflictsSelectionDone
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetConflictServices
 * Signature: ()Lorg/droidtv/euinstallertc/model/mwapi/MwDataTypes/HsvConflictServicesData;
 */
JNIEXPORT jobject JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetConflictServices
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetInstallationVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetInstallationVersion
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetInstallationState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetInstallationState
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetPLPIds
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetPLPIds
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    UserSelectionDone
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_UserSelectionDone
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetFavouriteRegion
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetFavouriteRegion
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    ZiggoNetworkDataSet
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_ZiggoNetworkDataSet
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    ClearPersistent
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_ClearPersistent
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    onScanAborted_CallNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_onScanAborted_1CallNative
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    onScanEnded_CallNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_onScanEnded_1CallNative
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    onScanningStandardDetected_CallNative
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_onScanningStandardDetected_1CallNative
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    onTvSystemDetected_CallNative
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_onTvSystemDetected_1CallNative
  (JNIEnv *, jobject, jint);
  
  
  
/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    onTuned_CallNative
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_onTuned_1CallNative
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    SetInstallCountry
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_SetInstallCountry
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    SetSystemCountry
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_SetSystemCountry
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    SetRfSetting
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_SetRfSetting
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    SetLCNSortingControl
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_SetLCNSortingControl
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    SetPbsMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_SetPbsMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    PrepareChNameUpdate
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_PrepareChNameUpdate
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetUpdatedChannelName
 * Signature: ()[S
 */
JNIEXPORT jstring JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetUpdatedChannelName
(JNIEnv *env, jobject obj);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetUpdatedONID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetUpdatedONID
(JNIEnv *env, jobject obj);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetUpdatedTsID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetUpdatedTsID
(JNIEnv *env, jobject obj);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    SetIsDVBT2Scan
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_SetIsDVBT2Scan
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    SetFocusedPlpId
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_SetFocusedPlpId
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    SetExtractScanResult
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_SetExtractScanResult
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetUpdatedSymbolRate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetUpdatedSymbolRate
(JNIEnv *env, jobject obj);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    setDigitalOrAnalaog
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_setDigitalOrAnalaog
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    getDigitalOrAnalaog
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_getDigitalOrAnalaog
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    getPogressStatus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_getPogressStatus
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetFirstIntalledAnalogueChannel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetFirstIntalledAnalogueChannel
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetFirstIntalledDigitalChannel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetFirstIntalledDigitalChannel
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetFirstIntalledRadioChannel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetFirstIntalledRadioChannel
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetFirstInstalledChannel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetFirstInstalledChannel
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetLastAnalogPresetNumber
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetLastAnalogPresetNumber
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    ifValidNetworkFreqEntered
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_ifValidNetworkFreqEntered
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetDigitalChannelOnOrOff
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetDigitalChannelOnOrOff
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    getNetworkName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_getNetworkName
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    getNIDsFound
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_getNIDsFound
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    getDefaultNetworkID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_getDefaultNetworkID
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    ifValidNetworkIDEntered
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_ifValidNetworkIDEntered
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    getFavNetworkList
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_getFavNetworkList
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    SetConflictSelectinDone
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_SetConflictSelectinDone
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    skipNetworkFreq
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_skipNetworkFreq
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    skipNetworkID
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_skipNetworkID
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    getRegionList
 * Signature: (IIII)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_getRegionList
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    setRegionList
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_setRegionList
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    setLowestNetworkID
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_setLowestNetworkID
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    getConflictingChannelNumbers
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_getConflictingChannelNumbers
  (JNIEnv *, jobject);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    getConflictingChannelNames
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_getConflictingChannelNames
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    setSymbolRatesOneTwo
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_setSymbolRatesOneTwo
  (JNIEnv *, jobject, jint, jint, jint);
  
/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    OnSourceSetupApplied
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_OnSourceSetupApplied
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    SetStreamPriority
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_SetStreamPriority
  (JNIEnv *, jobject, jint);
  /*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    OnOpSearchStatus
 * Signature: (jObject)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_OnOpSearchStatus
  (JNIEnv *env, jobject, jobject );
  
/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    OnOpStatusInfo
 * Signature: (jObject)V
 */

JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_OnOpStatusInfo
  (JNIEnv *env, jobject, jobject );
  
/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    OnOpNIT
 * Signature: (jObject)V
 */

JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_OnOpNIT
  (JNIEnv *env, jobject, jobject);

  /*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    OnOpTune
 * Signature: (jObject)V
 */

JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_OnOpTune
  (JNIEnv *env, jobject, jobject);
  
  
/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    StartPageDisplay
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_StartPageDisplay
  (JNIEnv *env, jobject obj);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetNoOfMtpItems
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetNoOfMtpItems
  (JNIEnv *env, jobject obj);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    SetCursor
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_SetCursor
  (JNIEnv *env, jobject obj, jint index);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    RemoveCursor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_RemoveCursor
  (JNIEnv *env, jobject obj);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    SelectIndex
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_SelectIndex
  (JNIEnv *env, jobject obj, jint index);

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    SetGfxHandle
 * Signature: (jObject)V
 */

JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_SetGfxHandle
  (JNIEnv *env, jobject obj, jobject objGfxHandle);  

/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetNumberOfDatabaseRecords
 * Signature: (I)I
 */

JNIEXPORT jint JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetNumberOfDatabaseRecords
  (JNIEnv *env, jobject obj, jint TSDataOnly);  


/*
 * Class:     org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:    GetTvProviderBlobDataByIndex
 * Signature: (II)Lorg/droidtv/euinstallertc/model/mwapi/TcInstallerTvProviderData
 */

JNIEXPORT jobject JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_GetTvProviderBlobDataByIndex
  (JNIEnv *env, jobject obj, jint Index,jint TSDataOnly); 

/*
 * Class:	  org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:	  PopulateMW
 * Signature: (jObject)V
 */

JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_PopulateMW
  (JNIEnv *env, jobject obj, jobject objTvpData, jint Clear);


/*
 * Class:	  org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:	  syncUniqueIdToMW
 * Signature: (jObject)V
 */

JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_syncUniqueIdToMW
  (JNIEnv *env, jobject obj, jobject objTvpData);

/* Class:	  Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:	  setDemuxHandle
 * Signature: (J)V

 * * */

JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_setDemuxHandle
(JNIEnv *env, jobject , jlong);

/* Class:	  Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC
 * Method:	  setVbiHandle
 * Signature: (J)V

 * * */

JNIEXPORT void JNICALL Java_org_droidtv_euinstallertc_model_mwapi_EuInstallerTC_setVbiHandle
(JNIEnv *env, jobject , jlong);



#ifdef __cplusplus
}
#endif
#endif
