#ifndef  _CHSVDVBSINSTALLATION_MROUTE_PRIV_H
#define  _CHSVDVBSINSTALLATION_MROUTE_PRIV_H 

#include <InfraGlobals.h>
#include <provreq.h>
#include <IHsvSatelliteBackgroundInstallation.h>
#include <IHsvSdmControlNotifyEx.h>
#include <IHsvSatellitePackageInstallation.h>
#include <IHsvSatelliteFrontEndNotify.h>
#include <IHsvPower.h>
#include <IHsvPackageRoute.h>
#include <IHsvSorting.h>
#include <IHsvStreamNotify.h>
#include <IHsvErrorCodeEx.h>
#include <IHsvPackageParser.h>
#include <IHsvSatelliteInstallation.h>
#include<IHsvSatelliteSettings.h>
#include <CS2MwBase.h>
class CHsvDvbsInstallation_mroute_Priv;
#define CLASSSCOPE CHsvDvbsInstallation_mroute_Priv::
#include "locals_mroute.h"

class CHsvDvbsInstallation_mroute_Priv : public CS2MwBase
{
public:
virtual ~CHsvDvbsInstallation_mroute_Priv();

private:
void params__init(void);
private:
#define MEMBERVARS
#include "locals_mroute.h"
#undef MEMBERVARS
//Provided interfaces
private:
IHsvSatelliteBackgroundInstallationImpl(CHsvDvbsInstallation_mroute_Priv,ibckInstall);
IHsvSdmControlNotifyExImpl(CHsvDvbsInstallation_mroute_Priv,ibckctrlN);
IHsvSdmControlNotifyExImpl(CHsvDvbsInstallation_mroute_Priv,ipackagectrlN);
IHsvSatellitePackageInstallationImpl(CHsvDvbsInstallation_mroute_Priv,ipackageins);
IHsvSatelliteFrontEndNotifyImpl(CHsvDvbsInstallation_mroute_Priv,ipackageplfApidvbsN);
IHsvPowerImpl(CHsvDvbsInstallation_mroute_Priv,ipackagepow);
IHsvPackageRouteImpl(CHsvDvbsInstallation_mroute_Priv,ipackageroute);
IHsvSortingImpl(CHsvDvbsInstallation_mroute_Priv,ipackagesort);
IHsvStreamNotifyImpl(CHsvDvbsInstallation_mroute_Priv,istrapiN);
ICesOperatorProfileNotifyImpl(CHsvDvbsInstallation_mroute_Priv,ipackageopinsN);
public:
ProvidesInterface<IHsvSatelliteBackgroundInstallation>	ibckInstall;

ProvidesInterface<IHsvSdmControlNotifyEx>	ibckctrlN;

ProvidesInterface<IHsvSdmControlNotifyEx>	ipackagectrlN;

ProvidesInterface<IHsvSatellitePackageInstallation>	ipackageins;

ProvidesInterface<IHsvSatelliteFrontEndNotify>	ipackageplfApidvbsN;

ProvidesInterface<IHsvPower>	ipackagepow;

ProvidesInterface<IHsvPackageRoute>	ipackageroute;

ProvidesInterface<IHsvSorting>	ipackagesort;

ProvidesInterface<IHsvStreamNotify>	istrapiN;

ProvidesInterface<ICesOperatorProfileNotify>	ipackageopinsN;

//Required interfaces
public:
RequiresInterface<IHsvErrorCodeEx>	err;
RequiresInterface<IHsvSdmControlNotifyEx>	hsvdvbscanal_ctrlN;
RequiresInterface<IHsvSatellitePackageInstallation>	hsvdvbscanal_ins;
RequiresInterface<IHsvSatelliteFrontEndNotify>	hsvdvbscanal_plfApidvbsN;
RequiresInterface<IHsvPower>	hsvdvbscanal_pow;
RequiresInterface<IHsvSorting>	hsvdvbscanal_sort;
RequiresInterface<IHsvSdmControlNotifyEx>	hsvdvbsopprofile_ctrlN;
RequiresInterface<IHsvSatellitePackageInstallation>	hsvdvbsopprofile_ins;
RequiresInterface<IHsvSatelliteFrontEndNotify>	hsvdvbsopprofile_plfApidvbsN;
RequiresInterface<IHsvPower>	hsvdvbsopprofile_pow;
RequiresInterface<IHsvSorting>	hsvdvbsopprofile_sort;
RequiresInterface<IHsvStreamNotify>	hsvdvbsopprofile_strapiN;
RequiresInterface<ICesOperatorProfileNotify>	hsvdvbsopprofile_opinsN;
RequiresInterface<IHsvSdmControlNotifyEx>	hsvdvbsdigiturk_ctrlN;
RequiresInterface<IHsvSatellitePackageInstallation>	hsvdvbsdigiturk_ins;
RequiresInterface<IHsvSatelliteFrontEndNotify>	hsvdvbsdigiturk_plfApidvbsN;
RequiresInterface<IHsvPower>	hsvdvbsdigiturk_pow;
RequiresInterface<IHsvSorting>	hsvdvbsdigiturk_sort;
RequiresInterface<IHsvSatelliteBackgroundInstallation>	hsvdvbsfransat_bckInstall;
RequiresInterface<IHsvSdmControlNotifyEx>	hsvdvbsfransat_bckctrlN;
RequiresInterface<IHsvSdmControlNotifyEx>	hsvdvbsfransat_ctrlN;
RequiresInterface<IHsvSatellitePackageInstallation>	hsvdvbsfransat_ins;
RequiresInterface<IHsvSatelliteFrontEndNotify>	hsvdvbsfransat_plfApidvbsN;
RequiresInterface<IHsvPower>	hsvdvbsfransat_pow;
RequiresInterface<IHsvSorting>	hsvdvbsfransat_sort;
RequiresInterface<IHsvStreamNotify>	hsvdvbsfransat_strapiN;
RequiresInterface<IHsvSatelliteBackgroundInstallation>	hsvdvbsgeneric_bckInstall;
RequiresInterface<IHsvSdmControlNotifyEx>	hsvdvbsgeneric_bckctrlN;
RequiresInterface<IHsvSdmControlNotifyEx>	hsvdvbsgeneric_ctrlN;
RequiresInterface<IHsvSatellitePackageInstallation>	hsvdvbsgeneric_ins;
RequiresInterface<IHsvSatelliteFrontEndNotify>	hsvdvbsgeneric_plfApidvbsN;
RequiresInterface<IHsvPower>	hsvdvbsgeneric_pow;
RequiresInterface<IHsvSorting>	hsvdvbsgeneric_sort;
RequiresInterface<IHsvStreamNotify>	hsvdvbsgeneric_strapiN;
RequiresInterface<IHsvSdmControlNotifyEx>	hsvdvbsm7_ctrlN;
RequiresInterface<IHsvSatellitePackageInstallation>	hsvdvbsm7_ins;
RequiresInterface<IHsvSatelliteFrontEndNotify>	hsvdvbsm7_plfApidvbsN;
RequiresInterface<IHsvPower>	hsvdvbsm7_pow;
RequiresInterface<IHsvSorting>	hsvdvbsm7_sort;
RequiresInterface<IHsvSdmControlNotifyEx>	hsvdvbsn_ctrlN;
RequiresInterface<IHsvSatellitePackageInstallation>	hsvdvbsn_ins;
RequiresInterface<IHsvSatelliteFrontEndNotify>	hsvdvbsn_plfApidvbsN;
RequiresInterface<IHsvPower>	hsvdvbsn_pow;
RequiresInterface<IHsvSorting>	hsvdvbsn_sort;
RequiresInterface<IHsvSdmControlNotifyEx>	hsvdvbspol_ctrlN;
RequiresInterface<IHsvSatellitePackageInstallation>	hsvdvbspol_ins;
RequiresInterface<IHsvSatelliteFrontEndNotify>	hsvdvbspol_plfApidvbsN;
RequiresInterface<IHsvPower>	hsvdvbspol_pow;
RequiresInterface<IHsvSorting>	hsvdvbspol_sort;
RequiresInterface<IHsvSdmControlNotifyEx>	hsvdvbsrussia_ctrlN;
RequiresInterface<IHsvSatellitePackageInstallation>	hsvdvbsrussia_ins;
RequiresInterface<IHsvSatelliteFrontEndNotify>	hsvdvbsrussia_plfApidvbsN;
RequiresInterface<IHsvPower>	hsvdvbsrussia_pow;
RequiresInterface<IHsvSorting>	hsvdvbsrussia_sort;
RequiresInterface<IHsvSdmControlNotifyEx>	hsvdvbstricolor_ctrlN;
RequiresInterface<IHsvSatellitePackageInstallation>	hsvdvbstricolor_ins;
RequiresInterface<IHsvSatelliteFrontEndNotify>	hsvdvbstricolor_plfApidvbsN;
RequiresInterface<IHsvPower>	hsvdvbstricolor_pow;
RequiresInterface<IHsvSorting>	hsvdvbstricolor_sort;
RequiresInterface<IHsvStreamNotify>	hsvdvbstricolor_strapiN;

RequiresInterface<IHsvSdmControlNotifyEx>	hsvdvbsfreesat_ctrlN;
RequiresInterface<IHsvSatellitePackageInstallation>	hsvdvbsfreesat_ins;
RequiresInterface<IHsvSatelliteFrontEndNotify>	hsvdvbsfreesat_plfApidvbsN;
RequiresInterface<IHsvPower>	hsvdvbsfreesat_pow;
RequiresInterface<IHsvSorting>	hsvdvbsfreesat_sort;
RequiresInterface<IHsvSatelliteSettings>	hsvdvbsfreesat_settings;
RequiresInterface<IHsvStreamNotify> hsvdvbsfreesat_strapiN;
RequiresInterface<IHsvSatelliteBackgroundInstallation>hsvdvbsfreesat_ibckInstall;
RequiresInterface<IHsvPackageParser>	ipackage;
RequiresInterface<IHsvSatelliteInstallation>	pins;
RequiresInterface<IHsvSdmControlNotifyEx>	hsvdvbsastra_ctrlN;
RequiresInterface<IHsvSatellitePackageInstallation>	hsvdvbsastra_ins;
RequiresInterface<IHsvSatelliteFrontEndNotify>	hsvdvbsastra_plfApidvbsN;
RequiresInterface<IHsvPower>	hsvdvbsastra_pow;
RequiresInterface<IHsvSorting>	hsvdvbsastra_sort;
RequiresInterface<IHsvStreamNotify>	hsvdvbsastra_strapiN;
RequiresInterface<IHsvSatelliteBackgroundInstallation>	hsvdvbsastra_bckInstall;



public:
CHsvDvbsInstallation_mroute_Priv():i__ibckInstall(this),i__ibckctrlN(this),i__ipackagectrlN(this),i__ipackageins(this),i__ipackageplfApidvbsN(this),i__ipackagepow(this),i__ipackageroute(this),i__ipackagesort(this),i__istrapiN(this),i__ipackageopinsN(this)
{
ibckInstall	=	&i__ibckInstall;
ibckctrlN	=	&i__ibckctrlN;
ipackagectrlN	=	&i__ipackagectrlN;
ipackageins	=	&i__ipackageins;
ipackageplfApidvbsN	=	&i__ipackageplfApidvbsN;
ipackagepow	=	&i__ipackagepow;
ipackageroute	=	&i__ipackageroute;
ipackagesort	=	&i__ipackagesort;
istrapiN	=	&i__istrapiN;
ipackageopinsN	=	&i__ipackageopinsN;
module__init();
params__init();
}

};

#ifdef GENERATE__LEGACY__DEFINES
#define err_iPresent() (err.Present())
#define err_Ok	IHsvErrorCodeEx_Ok
#define err_BadParameter	IHsvErrorCodeEx_BadParameter
#define err_ChannelNotInstalled	IHsvErrorCodeEx_ChannelNotInstalled
#define err_SelectionRequestNotHonored	IHsvErrorCodeEx_SelectionRequestNotHonored
#define err_ChannelAlreadySelected	IHsvErrorCodeEx_ChannelAlreadySelected
#define err_ValidSelectionRequest	IHsvErrorCodeEx_ValidSelectionRequest
#define err_InvalidSelectionRequest	IHsvErrorCodeEx_InvalidSelectionRequest
#define err_ChannelTableEmpty	IHsvErrorCodeEx_ChannelTableEmpty
#define err_ChannelTableExhausted	IHsvErrorCodeEx_ChannelTableExhausted
#define err_InvalidChannel	IHsvErrorCodeEx_InvalidChannel
#define err_FileError	IHsvErrorCodeEx_FileError
#define err_ChannelTableVersionError	IHsvErrorCodeEx_ChannelTableVersionError
#define err_ChannelTableCrcError	IHsvErrorCodeEx_ChannelTableCrcError
#define err_NotSupported	IHsvErrorCodeEx_NotSupported
#define err_InstallationModeNotSupported	IHsvErrorCodeEx_InstallationModeNotSupported
#define err_InstallationCommandNotAllowed	IHsvErrorCodeEx_InstallationCommandNotAllowed
#define err_InstallationNotInProgress	IHsvErrorCodeEx_InstallationNotInProgress
#define err_InvalidPTC	IHsvErrorCodeEx_InvalidPTC
#define err_InvalidMajorChannel	IHsvErrorCodeEx_InvalidMajorChannel
#define err_InvalidMinorChannel	IHsvErrorCodeEx_InvalidMinorChannel
#define err_NoNextMinorChannel	IHsvErrorCodeEx_NoNextMinorChannel
#define err_NoPreviousMinorChannel	IHsvErrorCodeEx_NoPreviousMinorChannel
#define err_InvalidSource	IHsvErrorCodeEx_InvalidSource
#define err_NoNextsource	IHsvErrorCodeEx_NoNextsource
#define err_NoPreviousSource	IHsvErrorCodeEx_NoPreviousSource
#define err_InvalidMode	IHsvErrorCodeEx_InvalidMode
#define err_InstallationStoreFailed	IHsvErrorCodeEx_InstallationStoreFailed
#define err_InvalidDestination	IHsvErrorCodeEx_InvalidDestination
#define err_EmptyPreset	IHsvErrorCodeEx_EmptyPreset
#define err_InvalidTypeOfSelection	IHsvErrorCodeEx_InvalidTypeOfSelection
#define err_ControlledSelectionNotAllowed	IHsvErrorCodeEx_ControlledSelectionNotAllowed
#define err_InvalidAttribute	IHsvErrorCodeEx_InvalidAttribute
#define err_AudioLanguageNotAvailable	IHsvErrorCodeEx_AudioLanguageNotAvailable
#define err_InvalidInterface	IHsvErrorCodeEx_InvalidInterface
#define err_DiseqcError	IHsvErrorCodeEx_DiseqcError
#define err_TunerError	IHsvErrorCodeEx_TunerError
#define err_UsbPathNotFound	IHsvErrorCodeEx_UsbPathNotFound
#define hsvdvbscanal_ctrlN_iPresent() (hsvdvbscanal_ctrlN.Present())
#define hsvdvbscanal_ctrlN_DataNotAvailable	IHsvSdmControlNotifyEx_DataNotAvailable
#define hsvdvbscanal_ctrlN_OnlyPsiDataAvailable	IHsvSdmControlNotifyEx_OnlyPsiDataAvailable
#define hsvdvbscanal_ctrlN_SiDataAvailable	IHsvSdmControlNotifyEx_SiDataAvailable
#define hsvdvbscanal_ctrlN_StartedCollection	IHsvSdmControlNotifyEx_StartedCollection
#define hsvdvbscanal_ctrlN_StoppedCollection	IHsvSdmControlNotifyEx_StoppedCollection
#define hsvdvbscanal_ctrlN_DataAvailable	IHsvSdmControlNotifyEx_DataAvailable
#define hsvdvbscanal_ctrlN_SDT	IHsvSdmControlNotifyEx_SDT
#define hsvdvbscanal_ctrlN_NIT	IHsvSdmControlNotifyEx_NIT
#define hsvdvbscanal_ctrlN_EIT	IHsvSdmControlNotifyEx_EIT
#define hsvdvbscanal_ctrlN_TOT	IHsvSdmControlNotifyEx_TOT
#define hsvdvbscanal_ctrlN_TDT	IHsvSdmControlNotifyEx_TDT
#define hsvdvbscanal_ctrlN_PMT	IHsvSdmControlNotifyEx_PMT
#define hsvdvbscanal_ctrlN_PAT	IHsvSdmControlNotifyEx_PAT
#define hsvdvbscanal_ctrlN_CAT	IHsvSdmControlNotifyEx_CAT
#define hsvdvbscanal_ctrlN_UNT	IHsvSdmControlNotifyEx_UNT
#define hsvdvbscanal_ctrlN_SIMPLEPAT	IHsvSdmControlNotifyEx_SIMPLEPAT
#define hsvdvbscanal_ctrlN_SIMPLEPMT	IHsvSdmControlNotifyEx_SIMPLEPMT
#define hsvdvbscanal_ctrlN_BAT	IHsvSdmControlNotifyEx_BAT
#define hsvdvbscanal_ctrlN_FNT	IHsvSdmControlNotifyEx_FNT
#define hsvdvbscanal_ctrlN_FST	IHsvSdmControlNotifyEx_FST
#define hsvdvbscanal_ctrlN_OnEvent(dmx,eventid,value)	hsvdvbscanal_ctrlN->OnEvent(dmx,eventid,value)
#define hsvdvbscanal_ins_iPresent() (hsvdvbscanal_ins.Present())
#define hsvdvbscanal_ins_ManualInstallLnb	IHsvSatellitePackageInstallation_ManualInstallLnb
#define hsvdvbscanal_ins_ManualInstallFreq	IHsvSatellitePackageInstallation_ManualInstallFreq
#define hsvdvbscanal_ins_ManualInstallPolaraization	IHsvSatellitePackageInstallation_ManualInstallPolaraization
#define hsvdvbscanal_ins_ManualInstallSymRate	IHsvSatellitePackageInstallation_ManualInstallSymRate
#define hsvdvbscanal_ins_ManualInstallSymRateMode	IHsvSatellitePackageInstallation_ManualInstallSymRateMode
#define hsvdvbscanal_ins_ManualInstallModulation	IHsvSatellitePackageInstallation_ManualInstallModulation
#define hsvdvbscanal_ins_GetCurrentInstallationState(mode,state)	hsvdvbscanal_ins->GetCurrentInstallationState(mode,state)
#define hsvdvbscanal_ins_StartInstallation(Source,Lnb,Mode)	hsvdvbscanal_ins->StartInstallation(Source,Lnb,Mode)
#define hsvdvbscanal_ins_StopInstallation()	hsvdvbscanal_ins->StopInstallation()
#define hsvdvbscanal_ins_WriteBarkerMuxData()	hsvdvbscanal_ins->WriteBarkerMuxData()
#define hsvdvbscanal_ins_GetNumberOfTvChannelsFound(Mode,Lnb)	hsvdvbscanal_ins->GetNumberOfTvChannelsFound(Mode,Lnb)
#define hsvdvbscanal_ins_GetNumberofRadioChannelsFound(Mode,Lnb)	hsvdvbscanal_ins->GetNumberofRadioChannelsFound(Mode,Lnb)
#define hsvdvbscanal_ins_GetNumberOfTvChannelsRemoved(Mode,Lnb)	hsvdvbscanal_ins->GetNumberOfTvChannelsRemoved(Mode,Lnb)
#define hsvdvbscanal_ins_GetNumberofRadioChannelsRemoved(Mode,Lnb)	hsvdvbscanal_ins->GetNumberofRadioChannelsRemoved(Mode,Lnb)
#define hsvdvbscanal_ins_GetNumberOfDigitalChannelsAdded()	hsvdvbscanal_ins->GetNumberOfDigitalChannelsAdded()
#define hsvdvbscanal_ins_GetNumberOfDigitalChannelsRemoved()	hsvdvbscanal_ins->GetNumberOfDigitalChannelsRemoved()
#define hsvdvbscanal_ins_GetNumberOfDigitalChannelsMoved()	hsvdvbscanal_ins->GetNumberOfDigitalChannelsMoved()
#define hsvdvbscanal_ins_LoadManualInstallationDefaultValues()	hsvdvbscanal_ins->LoadManualInstallationDefaultValues()
#define hsvdvbscanal_ins_StoreManualInstallationValues()	hsvdvbscanal_ins->StoreManualInstallationValues()
#define hsvdvbscanal_ins_SetManualInstallationAttributes(AttributeId,Value)	hsvdvbscanal_ins->SetManualInstallationAttributes(AttributeId,Value)
#define hsvdvbscanal_ins_GetAttribute(Mode,AttributeId)	hsvdvbscanal_ins->GetAttribute(Mode,AttributeId)
#define hsvdvbscanal_ins_GetScanProgressStatus(Mode)	hsvdvbscanal_ins->GetScanProgressStatus(Mode)
#define hsvdvbscanal_ins_GetSIDetails(SiValues)	hsvdvbscanal_ins->GetSIDetails(SiValues)
#define hsvdvbscanal_plfApidvbsN_iPresent() (hsvdvbscanal_plfApidvbsN.Present())
#define hsvdvbscanal_plfApidvbsN_OnLockChanged(LockState)	hsvdvbscanal_plfApidvbsN->OnLockChanged(LockState)
#define hsvdvbscanal_plfApidvbsN_OnBlindScanEnd()	hsvdvbscanal_plfApidvbsN->OnBlindScanEnd()
#define hsvdvbscanal_pow_iPresent() (hsvdvbscanal_pow.Present())
#define hsvdvbscanal_pow_Init()	hsvdvbscanal_pow->Init()
#define hsvdvbscanal_pow_TurnOn()	hsvdvbscanal_pow->TurnOn()
#define hsvdvbscanal_pow_TurnOff()	hsvdvbscanal_pow->TurnOff()
#define hsvdvbscanal_sort_iPresent() (hsvdvbscanal_sort.Present())
#define hsvdvbscanal_sort_Sort(PackageIndex)	hsvdvbscanal_sort->Sort(PackageIndex)
#define hsvdvbsopprofile_ctrlN_iPresent() (hsvdvbsopprofile_ctrlN.Present())
#define hsvdvbsopprofile_ctrlN_DataNotAvailable	IHsvSdmControlNotifyEx_DataNotAvailable
#define hsvdvbsopprofile_ctrlN_OnlyPsiDataAvailable	IHsvSdmControlNotifyEx_OnlyPsiDataAvailable
#define hsvdvbsopprofile_ctrlN_SiDataAvailable	IHsvSdmControlNotifyEx_SiDataAvailable
#define hsvdvbsopprofile_ctrlN_StartedCollection	IHsvSdmControlNotifyEx_StartedCollection
#define hsvdvbsopprofile_ctrlN_StoppedCollection	IHsvSdmControlNotifyEx_StoppedCollection
#define hsvdvbsopprofile_ctrlN_DataAvailable	IHsvSdmControlNotifyEx_DataAvailable
#define hsvdvbsopprofile_ctrlN_SDT	IHsvSdmControlNotifyEx_SDT
#define hsvdvbsopprofile_ctrlN_NIT	IHsvSdmControlNotifyEx_NIT
#define hsvdvbsopprofile_ctrlN_EIT	IHsvSdmControlNotifyEx_EIT
#define hsvdvbsopprofile_ctrlN_TOT	IHsvSdmControlNotifyEx_TOT
#define hsvdvbsopprofile_ctrlN_TDT	IHsvSdmControlNotifyEx_TDT
#define hsvdvbsopprofile_ctrlN_PMT	IHsvSdmControlNotifyEx_PMT
#define hsvdvbsopprofile_ctrlN_PAT	IHsvSdmControlNotifyEx_PAT
#define hsvdvbsopprofile_ctrlN_CAT	IHsvSdmControlNotifyEx_CAT
#define hsvdvbsopprofile_ctrlN_UNT	IHsvSdmControlNotifyEx_UNT
#define hsvdvbsopprofile_ctrlN_SIMPLEPAT	IHsvSdmControlNotifyEx_SIMPLEPAT
#define hsvdvbsopprofile_ctrlN_SIMPLEPMT	IHsvSdmControlNotifyEx_SIMPLEPMT
#define hsvdvbsopprofile_ctrlN_BAT	IHsvSdmControlNotifyEx_BAT
#define hsvdvbsopprofile_ctrlN_FNT	IHsvSdmControlNotifyEx_FNT
#define hsvdvbsopprofile_ctrlN_FST	IHsvSdmControlNotifyEx_FST
#define hsvdvbsopprofile_ctrlN_OnEvent(dmx,eventid,value)	hsvdvbsopprofile_ctrlN->OnEvent(dmx,eventid,value)
#define hsvdvbsopprofile_ins_iPresent() (hsvdvbsopprofile_ins.Present())
#define hsvdvbsopprofile_ins_ManualInstallLnb	IHsvSatellitePackageInstallation_ManualInstallLnb
#define hsvdvbsopprofile_ins_ManualInstallFreq	IHsvSatellitePackageInstallation_ManualInstallFreq
#define hsvdvbsopprofile_ins_ManualInstallPolaraization	IHsvSatellitePackageInstallation_ManualInstallPolaraization
#define hsvdvbsopprofile_ins_ManualInstallSymRate	IHsvSatellitePackageInstallation_ManualInstallSymRate
#define hsvdvbsopprofile_ins_ManualInstallSymRateMode	IHsvSatellitePackageInstallation_ManualInstallSymRateMode
#define hsvdvbsopprofile_ins_ManualInstallModulation	IHsvSatellitePackageInstallation_ManualInstallModulation
#define hsvdvbsopprofile_ins_GetCurrentInstallationState(mode,state)	hsvdvbsopprofile_ins->GetCurrentInstallationState(mode,state)
#define hsvdvbsopprofile_ins_StartInstallation(Source,Lnb,Mode)	hsvdvbsopprofile_ins->StartInstallation(Source,Lnb,Mode)
#define hsvdvbsopprofile_ins_StopInstallation()	hsvdvbsopprofile_ins->StopInstallation()
#define hsvdvbsopprofile_ins_WriteBarkerMuxData()	hsvdvbsopprofile_ins->WriteBarkerMuxData()
#define hsvdvbsopprofile_ins_GetNumberOfTvChannelsFound(Mode,Lnb)	hsvdvbsopprofile_ins->GetNumberOfTvChannelsFound(Mode,Lnb)
#define hsvdvbsopprofile_ins_GetNumberofRadioChannelsFound(Mode,Lnb)	hsvdvbsopprofile_ins->GetNumberofRadioChannelsFound(Mode,Lnb)
#define hsvdvbsopprofile_ins_GetNumberOfTvChannelsRemoved(Mode,Lnb)	hsvdvbsopprofile_ins->GetNumberOfTvChannelsRemoved(Mode,Lnb)
#define hsvdvbsopprofile_ins_GetNumberofRadioChannelsRemoved(Mode,Lnb)	hsvdvbsopprofile_ins->GetNumberofRadioChannelsRemoved(Mode,Lnb)
#define hsvdvbsopprofile_ins_GetNumberOfDigitalChannelsAdded()	hsvdvbsopprofile_ins->GetNumberOfDigitalChannelsAdded()
#define hsvdvbsopprofile_ins_GetNumberOfDigitalChannelsRemoved()	hsvdvbsopprofile_ins->GetNumberOfDigitalChannelsRemoved()
#define hsvdvbsopprofile_ins_GetNumberOfDigitalChannelsMoved()	hsvdvbsopprofile_ins->GetNumberOfDigitalChannelsMoved()
#define hsvdvbsopprofile_ins_LoadManualInstallationDefaultValues()	hsvdvbsopprofile_ins->LoadManualInstallationDefaultValues()
#define hsvdvbsopprofile_ins_StoreManualInstallationValues()	hsvdvbsopprofile_ins->StoreManualInstallationValues()
#define hsvdvbsopprofile_ins_SetManualInstallationAttributes(AttributeId,Value)	hsvdvbsopprofile_ins->SetManualInstallationAttributes(AttributeId,Value)
#define hsvdvbsopprofile_ins_GetAttribute(Mode,AttributeId)	hsvdvbsopprofile_ins->GetAttribute(Mode,AttributeId)
#define hsvdvbsopprofile_ins_GetScanProgressStatus(Mode)	hsvdvbsopprofile_ins->GetScanProgressStatus(Mode)
#define hsvdvbsopprofile_ins_GetSIDetails(SiValues)	hsvdvbsopprofile_ins->GetSIDetails(SiValues)
#define hsvdvbsopprofile_plfApidvbsN_iPresent() (hsvdvbsopprofile_plfApidvbsN.Present())
#define hsvdvbsopprofile_plfApidvbsN_OnLockChanged(LockState)	hsvdvbsopprofile_plfApidvbsN->OnLockChanged(LockState)
#define hsvdvbsopprofile_plfApidvbsN_OnBlindScanEnd()	hsvdvbsopprofile_plfApidvbsN->OnBlindScanEnd()
#define hsvdvbsopprofile_pow_iPresent() (hsvdvbsopprofile_pow.Present())
#define hsvdvbsopprofile_pow_Init()	hsvdvbsopprofile_pow->Init()
#define hsvdvbsopprofile_pow_TurnOn()	hsvdvbsopprofile_pow->TurnOn()
#define hsvdvbsopprofile_pow_TurnOff()	hsvdvbsopprofile_pow->TurnOff()
#define hsvdvbsopprofile_sort_iPresent() (hsvdvbsopprofile_sort.Present())
#define hsvdvbsopprofile_sort_Sort(PackageIndex)	hsvdvbsopprofile_sort->Sort(PackageIndex)
#define hsvdvbsopprofile_strapiN_iPresent() (hsvdvbsopprofile_strapiN.Present())
#define hsvdvbsopprofile_strapiN_OnCompleted(dest,spid)	hsvdvbsopprofile_strapiN->OnCompleted(dest,spid)
#define hsvdvbsopprofile_strapiN_OnAdded(dest,spid,key1,key2,key3)	hsvdvbsopprofile_strapiN->OnAdded(dest,spid,key1,key2,key3)
#define hsvdvbsopprofile_strapiN_OnChanged(dest,spid,key1,key2,key3,eventid)	hsvdvbsopprofile_strapiN->OnChanged(dest,spid,key1,key2,key3,eventid)
#define hsvdvbsopprofile_strapiN_OnRemoved(dest,spid,key1,key2,key3)	hsvdvbsopprofile_strapiN->OnRemoved(dest,spid,key1,key2,key3)
#define hsvdvbsopprofile_opinsN_OnOpSearchStatus(opStatus)		hsvdvbsopprofile_opinsN->OnOpSearchStatus(opStatus)
#define hsvdvbsopprofile_opinsN_OnOpStatusInfo(statusInfo)		hsvdvbsopprofile_opinsN->OnOpStatusInfo(statusInfo)
#define hsvdvbsopprofile_opinsN_OnOpNIT(nitData)					hsvdvbsopprofile_opinsN->OnOpNIT(nitData)	
#define hsvdvbsopprofile_opinsN_OnOpTune(tuneData)				hsvdvbsopprofile_opinsN->OnOpTune(tuneData)
#define hsvdvbsdigiturk_ctrlN_iPresent() (hsvdvbsdigiturk_ctrlN.Present())
#define hsvdvbsdigiturk_ctrlN_DataNotAvailable	IHsvSdmControlNotifyEx_DataNotAvailable
#define hsvdvbsdigiturk_ctrlN_OnlyPsiDataAvailable	IHsvSdmControlNotifyEx_OnlyPsiDataAvailable
#define hsvdvbsdigiturk_ctrlN_SiDataAvailable	IHsvSdmControlNotifyEx_SiDataAvailable
#define hsvdvbsdigiturk_ctrlN_StartedCollection	IHsvSdmControlNotifyEx_StartedCollection
#define hsvdvbsdigiturk_ctrlN_StoppedCollection	IHsvSdmControlNotifyEx_StoppedCollection
#define hsvdvbsdigiturk_ctrlN_DataAvailable	IHsvSdmControlNotifyEx_DataAvailable
#define hsvdvbsdigiturk_ctrlN_SDT	IHsvSdmControlNotifyEx_SDT
#define hsvdvbsdigiturk_ctrlN_NIT	IHsvSdmControlNotifyEx_NIT
#define hsvdvbsdigiturk_ctrlN_EIT	IHsvSdmControlNotifyEx_EIT
#define hsvdvbsdigiturk_ctrlN_TOT	IHsvSdmControlNotifyEx_TOT
#define hsvdvbsdigiturk_ctrlN_TDT	IHsvSdmControlNotifyEx_TDT
#define hsvdvbsdigiturk_ctrlN_PMT	IHsvSdmControlNotifyEx_PMT
#define hsvdvbsdigiturk_ctrlN_PAT	IHsvSdmControlNotifyEx_PAT
#define hsvdvbsdigiturk_ctrlN_CAT	IHsvSdmControlNotifyEx_CAT
#define hsvdvbsdigiturk_ctrlN_UNT	IHsvSdmControlNotifyEx_UNT
#define hsvdvbsdigiturk_ctrlN_SIMPLEPAT	IHsvSdmControlNotifyEx_SIMPLEPAT
#define hsvdvbsdigiturk_ctrlN_SIMPLEPMT	IHsvSdmControlNotifyEx_SIMPLEPMT
#define hsvdvbsdigiturk_ctrlN_BAT	IHsvSdmControlNotifyEx_BAT
#define hsvdvbsdigiturk_ctrlN_FNT	IHsvSdmControlNotifyEx_FNT
#define hsvdvbsdigiturk_ctrlN_FST	IHsvSdmControlNotifyEx_FST
#define hsvdvbsdigiturk_ctrlN_OnEvent(dmx,eventid,value)	hsvdvbsdigiturk_ctrlN->OnEvent(dmx,eventid,value)
#define hsvdvbsdigiturk_ins_iPresent() (hsvdvbsdigiturk_ins.Present())
#define hsvdvbsdigiturk_ins_ManualInstallLnb	IHsvSatellitePackageInstallation_ManualInstallLnb
#define hsvdvbsdigiturk_ins_ManualInstallFreq	IHsvSatellitePackageInstallation_ManualInstallFreq
#define hsvdvbsdigiturk_ins_ManualInstallPolaraization	IHsvSatellitePackageInstallation_ManualInstallPolaraization
#define hsvdvbsdigiturk_ins_ManualInstallSymRate	IHsvSatellitePackageInstallation_ManualInstallSymRate
#define hsvdvbsdigiturk_ins_ManualInstallSymRateMode	IHsvSatellitePackageInstallation_ManualInstallSymRateMode
#define hsvdvbsdigiturk_ins_ManualInstallModulation	IHsvSatellitePackageInstallation_ManualInstallModulation
#define hsvdvbsdigiturk_ins_GetCurrentInstallationState(mode,state)	hsvdvbsdigiturk_ins->GetCurrentInstallationState(mode,state)
#define hsvdvbsdigiturk_ins_StartInstallation(Source,Lnb,Mode)	hsvdvbsdigiturk_ins->StartInstallation(Source,Lnb,Mode)
#define hsvdvbsdigiturk_ins_StopInstallation()	hsvdvbsdigiturk_ins->StopInstallation()
#define hsvdvbsdigiturk_ins_WriteBarkerMuxData()	hsvdvbsdigiturk_ins->WriteBarkerMuxData()
#define hsvdvbsdigiturk_ins_GetNumberOfTvChannelsFound(Mode,Lnb)	hsvdvbsdigiturk_ins->GetNumberOfTvChannelsFound(Mode,Lnb)
#define hsvdvbsdigiturk_ins_GetNumberofRadioChannelsFound(Mode,Lnb)	hsvdvbsdigiturk_ins->GetNumberofRadioChannelsFound(Mode,Lnb)
#define hsvdvbsdigiturk_ins_GetNumberOfTvChannelsRemoved(Mode,Lnb)	hsvdvbsdigiturk_ins->GetNumberOfTvChannelsRemoved(Mode,Lnb)
#define hsvdvbsdigiturk_ins_GetNumberofRadioChannelsRemoved(Mode,Lnb)	hsvdvbsdigiturk_ins->GetNumberofRadioChannelsRemoved(Mode,Lnb)
#define hsvdvbsdigiturk_ins_GetNumberOfDigitalChannelsAdded()	hsvdvbsdigiturk_ins->GetNumberOfDigitalChannelsAdded()
#define hsvdvbsdigiturk_ins_GetNumberOfDigitalChannelsRemoved()	hsvdvbsdigiturk_ins->GetNumberOfDigitalChannelsRemoved()
#define hsvdvbsdigiturk_ins_GetNumberOfDigitalChannelsMoved()	hsvdvbsdigiturk_ins->GetNumberOfDigitalChannelsMoved()
#define hsvdvbsdigiturk_ins_LoadManualInstallationDefaultValues()	hsvdvbsdigiturk_ins->LoadManualInstallationDefaultValues()
#define hsvdvbsdigiturk_ins_StoreManualInstallationValues()	hsvdvbsdigiturk_ins->StoreManualInstallationValues()
#define hsvdvbsdigiturk_ins_SetManualInstallationAttributes(AttributeId,Value)	hsvdvbsdigiturk_ins->SetManualInstallationAttributes(AttributeId,Value)
#define hsvdvbsdigiturk_ins_GetAttribute(Mode,AttributeId)	hsvdvbsdigiturk_ins->GetAttribute(Mode,AttributeId)
#define hsvdvbsdigiturk_ins_GetScanProgressStatus(Mode)	hsvdvbsdigiturk_ins->GetScanProgressStatus(Mode)
#define hsvdvbsdigiturk_ins_GetSIDetails(SiValues)	hsvdvbsdigiturk_ins->GetSIDetails(SiValues)
#define hsvdvbsdigiturk_plfApidvbsN_iPresent() (hsvdvbsdigiturk_plfApidvbsN.Present())
#define hsvdvbsdigiturk_plfApidvbsN_OnLockChanged(LockState)	hsvdvbsdigiturk_plfApidvbsN->OnLockChanged(LockState)
#define hsvdvbsdigiturk_plfApidvbsN_OnBlindScanEnd()	hsvdvbsdigiturk_plfApidvbsN->OnBlindScanEnd()
#define hsvdvbsdigiturk_pow_iPresent() (hsvdvbsdigiturk_pow.Present())
#define hsvdvbsdigiturk_pow_Init()	hsvdvbsdigiturk_pow->Init()
#define hsvdvbsdigiturk_pow_TurnOn()	hsvdvbsdigiturk_pow->TurnOn()
#define hsvdvbsdigiturk_pow_TurnOff()	hsvdvbsdigiturk_pow->TurnOff()
#define hsvdvbsdigiturk_sort_iPresent() (hsvdvbsdigiturk_sort.Present())
#define hsvdvbsdigiturk_sort_Sort(PackageIndex)	hsvdvbsdigiturk_sort->Sort(PackageIndex)
#define hsvdvbsfransat_bckInstall_iPresent() (hsvdvbsfransat_bckInstall.Present())
#define hsvdvbsfransat_bckInstall_EnableBackgroundInstallation()	hsvdvbsfransat_bckInstall->EnableBackgroundInstallation()
#define hsvdvbsfransat_bckInstall_DisableBackgroundInstallation()	hsvdvbsfransat_bckInstall->DisableBackgroundInstallation()
#define hsvdvbsfransat_bckctrlN_iPresent() (hsvdvbsfransat_bckctrlN.Present())
#define hsvdvbsfransat_bckctrlN_DataNotAvailable	IHsvSdmControlNotifyEx_DataNotAvailable
#define hsvdvbsfransat_bckctrlN_OnlyPsiDataAvailable	IHsvSdmControlNotifyEx_OnlyPsiDataAvailable
#define hsvdvbsfransat_bckctrlN_SiDataAvailable	IHsvSdmControlNotifyEx_SiDataAvailable
#define hsvdvbsfransat_bckctrlN_StartedCollection	IHsvSdmControlNotifyEx_StartedCollection
#define hsvdvbsfransat_bckctrlN_StoppedCollection	IHsvSdmControlNotifyEx_StoppedCollection
#define hsvdvbsfransat_bckctrlN_DataAvailable	IHsvSdmControlNotifyEx_DataAvailable
#define hsvdvbsfransat_bckctrlN_SDT	IHsvSdmControlNotifyEx_SDT
#define hsvdvbsfransat_bckctrlN_NIT	IHsvSdmControlNotifyEx_NIT
#define hsvdvbsfransat_bckctrlN_EIT	IHsvSdmControlNotifyEx_EIT
#define hsvdvbsfransat_bckctrlN_TOT	IHsvSdmControlNotifyEx_TOT
#define hsvdvbsfransat_bckctrlN_TDT	IHsvSdmControlNotifyEx_TDT
#define hsvdvbsfransat_bckctrlN_PMT	IHsvSdmControlNotifyEx_PMT
#define hsvdvbsfransat_bckctrlN_PAT	IHsvSdmControlNotifyEx_PAT
#define hsvdvbsfransat_bckctrlN_CAT	IHsvSdmControlNotifyEx_CAT
#define hsvdvbsfransat_bckctrlN_UNT	IHsvSdmControlNotifyEx_UNT
#define hsvdvbsfransat_bckctrlN_SIMPLEPAT	IHsvSdmControlNotifyEx_SIMPLEPAT
#define hsvdvbsfransat_bckctrlN_SIMPLEPMT	IHsvSdmControlNotifyEx_SIMPLEPMT
#define hsvdvbsfransat_bckctrlN_BAT	IHsvSdmControlNotifyEx_BAT
#define hsvdvbsfransat_bckctrlN_FNT	IHsvSdmControlNotifyEx_FNT
#define hsvdvbsfransat_bckctrlN_FST	IHsvSdmControlNotifyEx_FST
#define hsvdvbsfransat_bckctrlN_OnEvent(dmx,eventid,value)	hsvdvbsfransat_bckctrlN->OnEvent(dmx,eventid,value)
#define hsvdvbsfransat_ctrlN_iPresent() (hsvdvbsfransat_ctrlN.Present())
#define hsvdvbsfransat_ctrlN_DataNotAvailable	IHsvSdmControlNotifyEx_DataNotAvailable
#define hsvdvbsfransat_ctrlN_OnlyPsiDataAvailable	IHsvSdmControlNotifyEx_OnlyPsiDataAvailable
#define hsvdvbsfransat_ctrlN_SiDataAvailable	IHsvSdmControlNotifyEx_SiDataAvailable
#define hsvdvbsfransat_ctrlN_StartedCollection	IHsvSdmControlNotifyEx_StartedCollection
#define hsvdvbsfransat_ctrlN_StoppedCollection	IHsvSdmControlNotifyEx_StoppedCollection
#define hsvdvbsfransat_ctrlN_DataAvailable	IHsvSdmControlNotifyEx_DataAvailable
#define hsvdvbsfransat_ctrlN_SDT	IHsvSdmControlNotifyEx_SDT
#define hsvdvbsfransat_ctrlN_NIT	IHsvSdmControlNotifyEx_NIT
#define hsvdvbsfransat_ctrlN_EIT	IHsvSdmControlNotifyEx_EIT
#define hsvdvbsfransat_ctrlN_TOT	IHsvSdmControlNotifyEx_TOT
#define hsvdvbsfransat_ctrlN_TDT	IHsvSdmControlNotifyEx_TDT
#define hsvdvbsfransat_ctrlN_PMT	IHsvSdmControlNotifyEx_PMT
#define hsvdvbsfransat_ctrlN_PAT	IHsvSdmControlNotifyEx_PAT
#define hsvdvbsfransat_ctrlN_CAT	IHsvSdmControlNotifyEx_CAT
#define hsvdvbsfransat_ctrlN_UNT	IHsvSdmControlNotifyEx_UNT
#define hsvdvbsfransat_ctrlN_SIMPLEPAT	IHsvSdmControlNotifyEx_SIMPLEPAT
#define hsvdvbsfransat_ctrlN_SIMPLEPMT	IHsvSdmControlNotifyEx_SIMPLEPMT
#define hsvdvbsfransat_ctrlN_BAT	IHsvSdmControlNotifyEx_BAT
#define hsvdvbsfransat_ctrlN_FNT	IHsvSdmControlNotifyEx_FNT
#define hsvdvbsfransat_ctrlN_FST	IHsvSdmControlNotifyEx_FST
#define hsvdvbsfransat_ctrlN_OnEvent(dmx,eventid,value)	hsvdvbsfransat_ctrlN->OnEvent(dmx,eventid,value)
#define hsvdvbsfransat_ins_iPresent() (hsvdvbsfransat_ins.Present())
#define hsvdvbsfransat_ins_ManualInstallLnb	IHsvSatellitePackageInstallation_ManualInstallLnb
#define hsvdvbsfransat_ins_ManualInstallFreq	IHsvSatellitePackageInstallation_ManualInstallFreq
#define hsvdvbsfransat_ins_ManualInstallPolaraization	IHsvSatellitePackageInstallation_ManualInstallPolaraization
#define hsvdvbsfransat_ins_ManualInstallSymRate	IHsvSatellitePackageInstallation_ManualInstallSymRate
#define hsvdvbsfransat_ins_ManualInstallSymRateMode	IHsvSatellitePackageInstallation_ManualInstallSymRateMode
#define hsvdvbsfransat_ins_ManualInstallModulation	IHsvSatellitePackageInstallation_ManualInstallModulation
#define hsvdvbsfransat_ins_GetCurrentInstallationState(mode,state)	hsvdvbsfransat_ins->GetCurrentInstallationState(mode,state)
#define hsvdvbsfransat_ins_StartInstallation(Source,Lnb,Mode)	hsvdvbsfransat_ins->StartInstallation(Source,Lnb,Mode)
#define hsvdvbsfransat_ins_StopInstallation()	hsvdvbsfransat_ins->StopInstallation()
#define hsvdvbsfransat_ins_WriteBarkerMuxData()	hsvdvbsfransat_ins->WriteBarkerMuxData()
#define hsvdvbsfransat_ins_GetNumberOfTvChannelsFound(Mode,Lnb)	hsvdvbsfransat_ins->GetNumberOfTvChannelsFound(Mode,Lnb)
#define hsvdvbsfransat_ins_GetNumberofRadioChannelsFound(Mode,Lnb)	hsvdvbsfransat_ins->GetNumberofRadioChannelsFound(Mode,Lnb)
#define hsvdvbsfransat_ins_GetNumberOfTvChannelsRemoved(Mode,Lnb)	hsvdvbsfransat_ins->GetNumberOfTvChannelsRemoved(Mode,Lnb)
#define hsvdvbsfransat_ins_GetNumberofRadioChannelsRemoved(Mode,Lnb)	hsvdvbsfransat_ins->GetNumberofRadioChannelsRemoved(Mode,Lnb)
#define hsvdvbsfransat_ins_GetNumberOfDigitalChannelsAdded()	hsvdvbsfransat_ins->GetNumberOfDigitalChannelsAdded()
#define hsvdvbsfransat_ins_GetNumberOfDigitalChannelsRemoved()	hsvdvbsfransat_ins->GetNumberOfDigitalChannelsRemoved()
#define hsvdvbsfransat_ins_GetNumberOfDigitalChannelsMoved()	hsvdvbsfransat_ins->GetNumberOfDigitalChannelsMoved()
#define hsvdvbsfransat_ins_LoadManualInstallationDefaultValues()	hsvdvbsfransat_ins->LoadManualInstallationDefaultValues()
#define hsvdvbsfransat_ins_StoreManualInstallationValues()	hsvdvbsfransat_ins->StoreManualInstallationValues()
#define hsvdvbsfransat_ins_SetManualInstallationAttributes(AttributeId,Value)	hsvdvbsfransat_ins->SetManualInstallationAttributes(AttributeId,Value)
#define hsvdvbsfransat_ins_GetAttribute(Mode,AttributeId)	hsvdvbsfransat_ins->GetAttribute(Mode,AttributeId)
#define hsvdvbsfransat_ins_GetScanProgressStatus(Mode)	hsvdvbsfransat_ins->GetScanProgressStatus(Mode)
#define hsvdvbsfransat_ins_GetSIDetails(SiValues)	hsvdvbsfransat_ins->GetSIDetails(SiValues)
#define hsvdvbsfransat_plfApidvbsN_iPresent() (hsvdvbsfransat_plfApidvbsN.Present())
#define hsvdvbsfransat_plfApidvbsN_OnLockChanged(LockState)	hsvdvbsfransat_plfApidvbsN->OnLockChanged(LockState)
#define hsvdvbsfransat_plfApidvbsN_OnBlindScanEnd()	hsvdvbsfransat_plfApidvbsN->OnBlindScanEnd()
#define hsvdvbsfransat_pow_iPresent() (hsvdvbsfransat_pow.Present())
#define hsvdvbsfransat_pow_Init()	hsvdvbsfransat_pow->Init()
#define hsvdvbsfransat_pow_TurnOn()	hsvdvbsfransat_pow->TurnOn()
#define hsvdvbsfransat_pow_TurnOff()	hsvdvbsfransat_pow->TurnOff()
#define hsvdvbsfransat_sort_iPresent() (hsvdvbsfransat_sort.Present())
#define hsvdvbsfransat_sort_Sort(PackageIndex)	hsvdvbsfransat_sort->Sort(PackageIndex)
#define hsvdvbsfransat_strapiN_iPresent() (hsvdvbsfransat_strapiN.Present())
#define hsvdvbsfransat_strapiN_OnCompleted(dest,spid)	hsvdvbsfransat_strapiN->OnCompleted(dest,spid)
#define hsvdvbsfransat_strapiN_OnAdded(dest,spid,key1,key2,key3)	hsvdvbsfransat_strapiN->OnAdded(dest,spid,key1,key2,key3)
#define hsvdvbsfransat_strapiN_OnChanged(dest,spid,key1,key2,key3,eventid)	hsvdvbsfransat_strapiN->OnChanged(dest,spid,key1,key2,key3,eventid)
#define hsvdvbsfransat_strapiN_OnRemoved(dest,spid,key1,key2,key3)	hsvdvbsfransat_strapiN->OnRemoved(dest,spid,key1,key2,key3)
#define hsvdvbsgeneric_bckInstall_iPresent() (hsvdvbsgeneric_bckInstall.Present())
#define hsvdvbsgeneric_bckInstall_EnableBackgroundInstallation()	hsvdvbsgeneric_bckInstall->EnableBackgroundInstallation()
#define hsvdvbsgeneric_bckInstall_DisableBackgroundInstallation()	hsvdvbsgeneric_bckInstall->DisableBackgroundInstallation()
#define hsvdvbsgeneric_bckctrlN_iPresent() (hsvdvbsgeneric_bckctrlN.Present())
#define hsvdvbsgeneric_bckctrlN_DataNotAvailable	IHsvSdmControlNotifyEx_DataNotAvailable
#define hsvdvbsgeneric_bckctrlN_OnlyPsiDataAvailable	IHsvSdmControlNotifyEx_OnlyPsiDataAvailable
#define hsvdvbsgeneric_bckctrlN_SiDataAvailable	IHsvSdmControlNotifyEx_SiDataAvailable
#define hsvdvbsgeneric_bckctrlN_StartedCollection	IHsvSdmControlNotifyEx_StartedCollection
#define hsvdvbsgeneric_bckctrlN_StoppedCollection	IHsvSdmControlNotifyEx_StoppedCollection
#define hsvdvbsgeneric_bckctrlN_DataAvailable	IHsvSdmControlNotifyEx_DataAvailable
#define hsvdvbsgeneric_bckctrlN_SDT	IHsvSdmControlNotifyEx_SDT
#define hsvdvbsgeneric_bckctrlN_NIT	IHsvSdmControlNotifyEx_NIT
#define hsvdvbsgeneric_bckctrlN_EIT	IHsvSdmControlNotifyEx_EIT
#define hsvdvbsgeneric_bckctrlN_TOT	IHsvSdmControlNotifyEx_TOT
#define hsvdvbsgeneric_bckctrlN_TDT	IHsvSdmControlNotifyEx_TDT
#define hsvdvbsgeneric_bckctrlN_PMT	IHsvSdmControlNotifyEx_PMT
#define hsvdvbsgeneric_bckctrlN_PAT	IHsvSdmControlNotifyEx_PAT
#define hsvdvbsgeneric_bckctrlN_CAT	IHsvSdmControlNotifyEx_CAT
#define hsvdvbsgeneric_bckctrlN_UNT	IHsvSdmControlNotifyEx_UNT
#define hsvdvbsgeneric_bckctrlN_SIMPLEPAT	IHsvSdmControlNotifyEx_SIMPLEPAT
#define hsvdvbsgeneric_bckctrlN_SIMPLEPMT	IHsvSdmControlNotifyEx_SIMPLEPMT
#define hsvdvbsgeneric_bckctrlN_BAT	IHsvSdmControlNotifyEx_BAT
#define hsvdvbsgeneric_bckctrlN_FNT	IHsvSdmControlNotifyEx_FNT
#define hsvdvbsgeneric_bckctrlN_FST	IHsvSdmControlNotifyEx_FST
#define hsvdvbsgeneric_bckctrlN_OnEvent(dmx,eventid,value)	hsvdvbsgeneric_bckctrlN->OnEvent(dmx,eventid,value)
#define hsvdvbsgeneric_ctrlN_iPresent() (hsvdvbsgeneric_ctrlN.Present())
#define hsvdvbsgeneric_ctrlN_DataNotAvailable	IHsvSdmControlNotifyEx_DataNotAvailable
#define hsvdvbsgeneric_ctrlN_OnlyPsiDataAvailable	IHsvSdmControlNotifyEx_OnlyPsiDataAvailable
#define hsvdvbsgeneric_ctrlN_SiDataAvailable	IHsvSdmControlNotifyEx_SiDataAvailable
#define hsvdvbsgeneric_ctrlN_StartedCollection	IHsvSdmControlNotifyEx_StartedCollection
#define hsvdvbsgeneric_ctrlN_StoppedCollection	IHsvSdmControlNotifyEx_StoppedCollection
#define hsvdvbsgeneric_ctrlN_DataAvailable	IHsvSdmControlNotifyEx_DataAvailable
#define hsvdvbsgeneric_ctrlN_SDT	IHsvSdmControlNotifyEx_SDT
#define hsvdvbsgeneric_ctrlN_NIT	IHsvSdmControlNotifyEx_NIT
#define hsvdvbsgeneric_ctrlN_EIT	IHsvSdmControlNotifyEx_EIT
#define hsvdvbsgeneric_ctrlN_TOT	IHsvSdmControlNotifyEx_TOT
#define hsvdvbsgeneric_ctrlN_TDT	IHsvSdmControlNotifyEx_TDT
#define hsvdvbsgeneric_ctrlN_PMT	IHsvSdmControlNotifyEx_PMT
#define hsvdvbsgeneric_ctrlN_PAT	IHsvSdmControlNotifyEx_PAT
#define hsvdvbsgeneric_ctrlN_CAT	IHsvSdmControlNotifyEx_CAT
#define hsvdvbsgeneric_ctrlN_UNT	IHsvSdmControlNotifyEx_UNT
#define hsvdvbsgeneric_ctrlN_SIMPLEPAT	IHsvSdmControlNotifyEx_SIMPLEPAT
#define hsvdvbsgeneric_ctrlN_SIMPLEPMT	IHsvSdmControlNotifyEx_SIMPLEPMT
#define hsvdvbsgeneric_ctrlN_BAT	IHsvSdmControlNotifyEx_BAT
#define hsvdvbsgeneric_ctrlN_FNT	IHsvSdmControlNotifyEx_FNT
#define hsvdvbsgeneric_ctrlN_FST	IHsvSdmControlNotifyEx_FST
#define hsvdvbsgeneric_ctrlN_OnEvent(dmx,eventid,value)	hsvdvbsgeneric_ctrlN->OnEvent(dmx,eventid,value)
#define hsvdvbsgeneric_ins_iPresent() (hsvdvbsgeneric_ins.Present())
#define hsvdvbsgeneric_ins_ManualInstallLnb	IHsvSatellitePackageInstallation_ManualInstallLnb
#define hsvdvbsgeneric_ins_ManualInstallFreq	IHsvSatellitePackageInstallation_ManualInstallFreq
#define hsvdvbsgeneric_ins_ManualInstallPolaraization	IHsvSatellitePackageInstallation_ManualInstallPolaraization
#define hsvdvbsgeneric_ins_ManualInstallSymRate	IHsvSatellitePackageInstallation_ManualInstallSymRate
#define hsvdvbsgeneric_ins_ManualInstallSymRateMode	IHsvSatellitePackageInstallation_ManualInstallSymRateMode
#define hsvdvbsgeneric_ins_ManualInstallModulation	IHsvSatellitePackageInstallation_ManualInstallModulation
#define hsvdvbsgeneric_ins_GetCurrentInstallationState(mode,state)	hsvdvbsgeneric_ins->GetCurrentInstallationState(mode,state)
#define hsvdvbsgeneric_ins_StartInstallation(Source,Lnb,Mode)	hsvdvbsgeneric_ins->StartInstallation(Source,Lnb,Mode)
#define hsvdvbsgeneric_ins_StopInstallation()	hsvdvbsgeneric_ins->StopInstallation()
#define hsvdvbsgeneric_ins_WriteBarkerMuxData()	hsvdvbsgeneric_ins->WriteBarkerMuxData()
#define hsvdvbsgeneric_ins_GetNumberOfTvChannelsFound(Mode,Lnb)	hsvdvbsgeneric_ins->GetNumberOfTvChannelsFound(Mode,Lnb)
#define hsvdvbsgeneric_ins_GetNumberofRadioChannelsFound(Mode,Lnb)	hsvdvbsgeneric_ins->GetNumberofRadioChannelsFound(Mode,Lnb)
#define hsvdvbsgeneric_ins_GetNumberOfTvChannelsRemoved(Mode,Lnb)	hsvdvbsgeneric_ins->GetNumberOfTvChannelsRemoved(Mode,Lnb)
#define hsvdvbsgeneric_ins_GetNumberofRadioChannelsRemoved(Mode,Lnb)	hsvdvbsgeneric_ins->GetNumberofRadioChannelsRemoved(Mode,Lnb)
#define hsvdvbsgeneric_ins_GetNumberOfDigitalChannelsAdded()	hsvdvbsgeneric_ins->GetNumberOfDigitalChannelsAdded()
#define hsvdvbsgeneric_ins_GetNumberOfDigitalChannelsRemoved()	hsvdvbsgeneric_ins->GetNumberOfDigitalChannelsRemoved()
#define hsvdvbsgeneric_ins_GetNumberOfDigitalChannelsMoved()	hsvdvbsgeneric_ins->GetNumberOfDigitalChannelsMoved()
#define hsvdvbsgeneric_ins_LoadManualInstallationDefaultValues()	hsvdvbsgeneric_ins->LoadManualInstallationDefaultValues()
#define hsvdvbsgeneric_ins_StoreManualInstallationValues()	hsvdvbsgeneric_ins->StoreManualInstallationValues()
#define hsvdvbsgeneric_ins_SetManualInstallationAttributes(AttributeId,Value)	hsvdvbsgeneric_ins->SetManualInstallationAttributes(AttributeId,Value)
#define hsvdvbsgeneric_ins_GetAttribute(Mode,AttributeId)	hsvdvbsgeneric_ins->GetAttribute(Mode,AttributeId)
#define hsvdvbsgeneric_ins_GetScanProgressStatus(Mode)	hsvdvbsgeneric_ins->GetScanProgressStatus(Mode)
#define hsvdvbsgeneric_ins_GetSIDetails(SiValues)	hsvdvbsgeneric_ins->GetSIDetails(SiValues)
#define hsvdvbsgeneric_plfApidvbsN_iPresent() (hsvdvbsgeneric_plfApidvbsN.Present())
#define hsvdvbsgeneric_plfApidvbsN_OnLockChanged(LockState)	hsvdvbsgeneric_plfApidvbsN->OnLockChanged(LockState)
#define hsvdvbsgeneric_plfApidvbsN_OnBlindScanEnd()	hsvdvbsgeneric_plfApidvbsN->OnBlindScanEnd()
#define hsvdvbsgeneric_pow_iPresent() (hsvdvbsgeneric_pow.Present())
#define hsvdvbsgeneric_pow_Init()	hsvdvbsgeneric_pow->Init()
#define hsvdvbsgeneric_pow_TurnOn()	hsvdvbsgeneric_pow->TurnOn()
#define hsvdvbsgeneric_pow_TurnOff()	hsvdvbsgeneric_pow->TurnOff()
#define hsvdvbsgeneric_sort_iPresent() (hsvdvbsgeneric_sort.Present())
#define hsvdvbsgeneric_sort_Sort(PackageIndex)	hsvdvbsgeneric_sort->Sort(PackageIndex)
#define hsvdvbsgeneric_strapiN_iPresent() (hsvdvbsgeneric_strapiN.Present())
#define hsvdvbsgeneric_strapiN_OnCompleted(dest,spid)	hsvdvbsgeneric_strapiN->OnCompleted(dest,spid)
#define hsvdvbsgeneric_strapiN_OnAdded(dest,spid,key1,key2,key3)	hsvdvbsgeneric_strapiN->OnAdded(dest,spid,key1,key2,key3)
#define hsvdvbsgeneric_strapiN_OnChanged(dest,spid,key1,key2,key3,eventid)	hsvdvbsgeneric_strapiN->OnChanged(dest,spid,key1,key2,key3,eventid)
#define hsvdvbsgeneric_strapiN_OnRemoved(dest,spid,key1,key2,key3)	hsvdvbsgeneric_strapiN->OnRemoved(dest,spid,key1,key2,key3)
#define hsvdvbsm7_ctrlN_iPresent() (hsvdvbsm7_ctrlN.Present())
#define hsvdvbsm7_ctrlN_DataNotAvailable	IHsvSdmControlNotifyEx_DataNotAvailable
#define hsvdvbsm7_ctrlN_OnlyPsiDataAvailable	IHsvSdmControlNotifyEx_OnlyPsiDataAvailable
#define hsvdvbsm7_ctrlN_SiDataAvailable	IHsvSdmControlNotifyEx_SiDataAvailable
#define hsvdvbsm7_ctrlN_StartedCollection	IHsvSdmControlNotifyEx_StartedCollection
#define hsvdvbsm7_ctrlN_StoppedCollection	IHsvSdmControlNotifyEx_StoppedCollection
#define hsvdvbsm7_ctrlN_DataAvailable	IHsvSdmControlNotifyEx_DataAvailable
#define hsvdvbsm7_ctrlN_SDT	IHsvSdmControlNotifyEx_SDT
#define hsvdvbsm7_ctrlN_NIT	IHsvSdmControlNotifyEx_NIT
#define hsvdvbsm7_ctrlN_EIT	IHsvSdmControlNotifyEx_EIT
#define hsvdvbsm7_ctrlN_TOT	IHsvSdmControlNotifyEx_TOT
#define hsvdvbsm7_ctrlN_TDT	IHsvSdmControlNotifyEx_TDT
#define hsvdvbsm7_ctrlN_PMT	IHsvSdmControlNotifyEx_PMT
#define hsvdvbsm7_ctrlN_PAT	IHsvSdmControlNotifyEx_PAT
#define hsvdvbsm7_ctrlN_CAT	IHsvSdmControlNotifyEx_CAT
#define hsvdvbsm7_ctrlN_UNT	IHsvSdmControlNotifyEx_UNT
#define hsvdvbsm7_ctrlN_SIMPLEPAT	IHsvSdmControlNotifyEx_SIMPLEPAT
#define hsvdvbsm7_ctrlN_SIMPLEPMT	IHsvSdmControlNotifyEx_SIMPLEPMT
#define hsvdvbsm7_ctrlN_BAT	IHsvSdmControlNotifyEx_BAT
#define hsvdvbsm7_ctrlN_FNT	IHsvSdmControlNotifyEx_FNT
#define hsvdvbsm7_ctrlN_FST	IHsvSdmControlNotifyEx_FST
#define hsvdvbsm7_ctrlN_OnEvent(dmx,eventid,value)	hsvdvbsm7_ctrlN->OnEvent(dmx,eventid,value)
#define hsvdvbsm7_ins_iPresent() (hsvdvbsm7_ins.Present())
#define hsvdvbsm7_ins_ManualInstallLnb	IHsvSatellitePackageInstallation_ManualInstallLnb
#define hsvdvbsm7_ins_ManualInstallFreq	IHsvSatellitePackageInstallation_ManualInstallFreq
#define hsvdvbsm7_ins_ManualInstallPolaraization	IHsvSatellitePackageInstallation_ManualInstallPolaraization
#define hsvdvbsm7_ins_ManualInstallSymRate	IHsvSatellitePackageInstallation_ManualInstallSymRate
#define hsvdvbsm7_ins_ManualInstallSymRateMode	IHsvSatellitePackageInstallation_ManualInstallSymRateMode
#define hsvdvbsm7_ins_ManualInstallModulation	IHsvSatellitePackageInstallation_ManualInstallModulation
#define hsvdvbsm7_ins_GetCurrentInstallationState(mode,state)	hsvdvbsm7_ins->GetCurrentInstallationState(mode,state)
#define hsvdvbsm7_ins_StartInstallation(Source,Lnb,Mode)	hsvdvbsm7_ins->StartInstallation(Source,Lnb,Mode)
#define hsvdvbsm7_ins_StopInstallation()	hsvdvbsm7_ins->StopInstallation()
#define hsvdvbsm7_ins_WriteBarkerMuxData()	hsvdvbsm7_ins->WriteBarkerMuxData()
#define hsvdvbsm7_ins_GetNumberOfTvChannelsFound(Mode,Lnb)	hsvdvbsm7_ins->GetNumberOfTvChannelsFound(Mode,Lnb)
#define hsvdvbsm7_ins_GetNumberofRadioChannelsFound(Mode,Lnb)	hsvdvbsm7_ins->GetNumberofRadioChannelsFound(Mode,Lnb)
#define hsvdvbsm7_ins_GetNumberOfTvChannelsRemoved(Mode,Lnb)	hsvdvbsm7_ins->GetNumberOfTvChannelsRemoved(Mode,Lnb)
#define hsvdvbsm7_ins_GetNumberofRadioChannelsRemoved(Mode,Lnb)	hsvdvbsm7_ins->GetNumberofRadioChannelsRemoved(Mode,Lnb)
#define hsvdvbsm7_ins_GetNumberOfDigitalChannelsAdded()	hsvdvbsm7_ins->GetNumberOfDigitalChannelsAdded()
#define hsvdvbsm7_ins_GetNumberOfDigitalChannelsRemoved()	hsvdvbsm7_ins->GetNumberOfDigitalChannelsRemoved()
#define hsvdvbsm7_ins_GetNumberOfDigitalChannelsMoved()	hsvdvbsm7_ins->GetNumberOfDigitalChannelsMoved()
#define hsvdvbsm7_ins_LoadManualInstallationDefaultValues()	hsvdvbsm7_ins->LoadManualInstallationDefaultValues()
#define hsvdvbsm7_ins_StoreManualInstallationValues()	hsvdvbsm7_ins->StoreManualInstallationValues()
#define hsvdvbsm7_ins_SetManualInstallationAttributes(AttributeId,Value)	hsvdvbsm7_ins->SetManualInstallationAttributes(AttributeId,Value)
#define hsvdvbsm7_ins_GetAttribute(Mode,AttributeId)	hsvdvbsm7_ins->GetAttribute(Mode,AttributeId)
#define hsvdvbsm7_ins_GetScanProgressStatus(Mode)	hsvdvbsm7_ins->GetScanProgressStatus(Mode)
#define hsvdvbsm7_ins_GetSIDetails(SiValues)	hsvdvbsm7_ins->GetSIDetails(SiValues)
#define hsvdvbsm7_plfApidvbsN_iPresent() (hsvdvbsm7_plfApidvbsN.Present())
#define hsvdvbsm7_plfApidvbsN_OnLockChanged(LockState)	hsvdvbsm7_plfApidvbsN->OnLockChanged(LockState)
#define hsvdvbsm7_plfApidvbsN_OnBlindScanEnd()	hsvdvbsm7_plfApidvbsN->OnBlindScanEnd()
#define hsvdvbsm7_pow_iPresent() (hsvdvbsm7_pow.Present())
#define hsvdvbsm7_pow_Init()	hsvdvbsm7_pow->Init()
#define hsvdvbsm7_pow_TurnOn()	hsvdvbsm7_pow->TurnOn()
#define hsvdvbsm7_pow_TurnOff()	hsvdvbsm7_pow->TurnOff()
#define hsvdvbsm7_sort_iPresent() (hsvdvbsm7_sort.Present())
#define hsvdvbsm7_sort_Sort(PackageIndex)	hsvdvbsm7_sort->Sort(PackageIndex)
#define hsvdvbsn_ctrlN_iPresent() (hsvdvbsn_ctrlN.Present())
#define hsvdvbsn_ctrlN_DataNotAvailable	IHsvSdmControlNotifyEx_DataNotAvailable
#define hsvdvbsn_ctrlN_OnlyPsiDataAvailable	IHsvSdmControlNotifyEx_OnlyPsiDataAvailable
#define hsvdvbsn_ctrlN_SiDataAvailable	IHsvSdmControlNotifyEx_SiDataAvailable
#define hsvdvbsn_ctrlN_StartedCollection	IHsvSdmControlNotifyEx_StartedCollection
#define hsvdvbsn_ctrlN_StoppedCollection	IHsvSdmControlNotifyEx_StoppedCollection
#define hsvdvbsn_ctrlN_DataAvailable	IHsvSdmControlNotifyEx_DataAvailable
#define hsvdvbsn_ctrlN_SDT	IHsvSdmControlNotifyEx_SDT
#define hsvdvbsn_ctrlN_NIT	IHsvSdmControlNotifyEx_NIT
#define hsvdvbsn_ctrlN_EIT	IHsvSdmControlNotifyEx_EIT
#define hsvdvbsn_ctrlN_TOT	IHsvSdmControlNotifyEx_TOT
#define hsvdvbsn_ctrlN_TDT	IHsvSdmControlNotifyEx_TDT
#define hsvdvbsn_ctrlN_PMT	IHsvSdmControlNotifyEx_PMT
#define hsvdvbsn_ctrlN_PAT	IHsvSdmControlNotifyEx_PAT
#define hsvdvbsn_ctrlN_CAT	IHsvSdmControlNotifyEx_CAT
#define hsvdvbsn_ctrlN_UNT	IHsvSdmControlNotifyEx_UNT
#define hsvdvbsn_ctrlN_SIMPLEPAT	IHsvSdmControlNotifyEx_SIMPLEPAT
#define hsvdvbsn_ctrlN_SIMPLEPMT	IHsvSdmControlNotifyEx_SIMPLEPMT
#define hsvdvbsn_ctrlN_BAT	IHsvSdmControlNotifyEx_BAT
#define hsvdvbsn_ctrlN_FNT	IHsvSdmControlNotifyEx_FNT
#define hsvdvbsn_ctrlN_FST	IHsvSdmControlNotifyEx_FST
#define hsvdvbsn_ctrlN_OnEvent(dmx,eventid,value)	hsvdvbsn_ctrlN->OnEvent(dmx,eventid,value)
#define hsvdvbsn_ins_iPresent() (hsvdvbsn_ins.Present())
#define hsvdvbsn_ins_ManualInstallLnb	IHsvSatellitePackageInstallation_ManualInstallLnb
#define hsvdvbsn_ins_ManualInstallFreq	IHsvSatellitePackageInstallation_ManualInstallFreq
#define hsvdvbsn_ins_ManualInstallPolaraization	IHsvSatellitePackageInstallation_ManualInstallPolaraization
#define hsvdvbsn_ins_ManualInstallSymRate	IHsvSatellitePackageInstallation_ManualInstallSymRate
#define hsvdvbsn_ins_ManualInstallSymRateMode	IHsvSatellitePackageInstallation_ManualInstallSymRateMode
#define hsvdvbsn_ins_ManualInstallModulation	IHsvSatellitePackageInstallation_ManualInstallModulation
#define hsvdvbsn_ins_GetCurrentInstallationState(mode,state)	hsvdvbsn_ins->GetCurrentInstallationState(mode,state)
#define hsvdvbsn_ins_StartInstallation(Source,Lnb,Mode)	hsvdvbsn_ins->StartInstallation(Source,Lnb,Mode)
#define hsvdvbsn_ins_StopInstallation()	hsvdvbsn_ins->StopInstallation()
#define hsvdvbsn_ins_WriteBarkerMuxData()	hsvdvbsn_ins->WriteBarkerMuxData()
#define hsvdvbsn_ins_GetNumberOfTvChannelsFound(Mode,Lnb)	hsvdvbsn_ins->GetNumberOfTvChannelsFound(Mode,Lnb)
#define hsvdvbsn_ins_GetNumberofRadioChannelsFound(Mode,Lnb)	hsvdvbsn_ins->GetNumberofRadioChannelsFound(Mode,Lnb)
#define hsvdvbsn_ins_GetNumberOfTvChannelsRemoved(Mode,Lnb)	hsvdvbsn_ins->GetNumberOfTvChannelsRemoved(Mode,Lnb)
#define hsvdvbsn_ins_GetNumberofRadioChannelsRemoved(Mode,Lnb)	hsvdvbsn_ins->GetNumberofRadioChannelsRemoved(Mode,Lnb)
#define hsvdvbsn_ins_GetNumberOfDigitalChannelsAdded()	hsvdvbsn_ins->GetNumberOfDigitalChannelsAdded()
#define hsvdvbsn_ins_GetNumberOfDigitalChannelsRemoved()	hsvdvbsn_ins->GetNumberOfDigitalChannelsRemoved()
#define hsvdvbsn_ins_GetNumberOfDigitalChannelsMoved()	hsvdvbsn_ins->GetNumberOfDigitalChannelsMoved()
#define hsvdvbsn_ins_LoadManualInstallationDefaultValues()	hsvdvbsn_ins->LoadManualInstallationDefaultValues()
#define hsvdvbsn_ins_StoreManualInstallationValues()	hsvdvbsn_ins->StoreManualInstallationValues()
#define hsvdvbsn_ins_SetManualInstallationAttributes(AttributeId,Value)	hsvdvbsn_ins->SetManualInstallationAttributes(AttributeId,Value)
#define hsvdvbsn_ins_GetAttribute(Mode,AttributeId)	hsvdvbsn_ins->GetAttribute(Mode,AttributeId)
#define hsvdvbsn_ins_GetScanProgressStatus(Mode)	hsvdvbsn_ins->GetScanProgressStatus(Mode)
#define hsvdvbsn_ins_GetSIDetails(SiValues)	hsvdvbsn_ins->GetSIDetails(SiValues)
#define hsvdvbsn_plfApidvbsN_iPresent() (hsvdvbsn_plfApidvbsN.Present())
#define hsvdvbsn_plfApidvbsN_OnLockChanged(LockState)	hsvdvbsn_plfApidvbsN->OnLockChanged(LockState)
#define hsvdvbsn_plfApidvbsN_OnBlindScanEnd()	hsvdvbsn_plfApidvbsN->OnBlindScanEnd()
#define hsvdvbsn_pow_iPresent() (hsvdvbsn_pow.Present())
#define hsvdvbsn_pow_Init()	hsvdvbsn_pow->Init()
#define hsvdvbsn_pow_TurnOn()	hsvdvbsn_pow->TurnOn()
#define hsvdvbsn_pow_TurnOff()	hsvdvbsn_pow->TurnOff()
#define hsvdvbsn_sort_iPresent() (hsvdvbsn_sort.Present())
#define hsvdvbsn_sort_Sort(PackageIndex)	hsvdvbsn_sort->Sort(PackageIndex)
#define hsvdvbspol_ctrlN_iPresent() (hsvdvbspol_ctrlN.Present())
#define hsvdvbspol_ctrlN_DataNotAvailable	IHsvSdmControlNotifyEx_DataNotAvailable
#define hsvdvbspol_ctrlN_OnlyPsiDataAvailable	IHsvSdmControlNotifyEx_OnlyPsiDataAvailable
#define hsvdvbspol_ctrlN_SiDataAvailable	IHsvSdmControlNotifyEx_SiDataAvailable
#define hsvdvbspol_ctrlN_StartedCollection	IHsvSdmControlNotifyEx_StartedCollection
#define hsvdvbspol_ctrlN_StoppedCollection	IHsvSdmControlNotifyEx_StoppedCollection
#define hsvdvbspol_ctrlN_DataAvailable	IHsvSdmControlNotifyEx_DataAvailable
#define hsvdvbspol_ctrlN_SDT	IHsvSdmControlNotifyEx_SDT
#define hsvdvbspol_ctrlN_NIT	IHsvSdmControlNotifyEx_NIT
#define hsvdvbspol_ctrlN_EIT	IHsvSdmControlNotifyEx_EIT
#define hsvdvbspol_ctrlN_TOT	IHsvSdmControlNotifyEx_TOT
#define hsvdvbspol_ctrlN_TDT	IHsvSdmControlNotifyEx_TDT
#define hsvdvbspol_ctrlN_PMT	IHsvSdmControlNotifyEx_PMT
#define hsvdvbspol_ctrlN_PAT	IHsvSdmControlNotifyEx_PAT
#define hsvdvbspol_ctrlN_CAT	IHsvSdmControlNotifyEx_CAT
#define hsvdvbspol_ctrlN_UNT	IHsvSdmControlNotifyEx_UNT
#define hsvdvbspol_ctrlN_SIMPLEPAT	IHsvSdmControlNotifyEx_SIMPLEPAT
#define hsvdvbspol_ctrlN_SIMPLEPMT	IHsvSdmControlNotifyEx_SIMPLEPMT
#define hsvdvbspol_ctrlN_BAT	IHsvSdmControlNotifyEx_BAT
#define hsvdvbspol_ctrlN_FNT	IHsvSdmControlNotifyEx_FNT
#define hsvdvbspol_ctrlN_FST	IHsvSdmControlNotifyEx_FST
#define hsvdvbspol_ctrlN_OnEvent(dmx,eventid,value)	hsvdvbspol_ctrlN->OnEvent(dmx,eventid,value)
#define hsvdvbspol_ins_iPresent() (hsvdvbspol_ins.Present())
#define hsvdvbspol_ins_ManualInstallLnb	IHsvSatellitePackageInstallation_ManualInstallLnb
#define hsvdvbspol_ins_ManualInstallFreq	IHsvSatellitePackageInstallation_ManualInstallFreq
#define hsvdvbspol_ins_ManualInstallPolaraization	IHsvSatellitePackageInstallation_ManualInstallPolaraization
#define hsvdvbspol_ins_ManualInstallSymRate	IHsvSatellitePackageInstallation_ManualInstallSymRate
#define hsvdvbspol_ins_ManualInstallSymRateMode	IHsvSatellitePackageInstallation_ManualInstallSymRateMode
#define hsvdvbspol_ins_ManualInstallModulation	IHsvSatellitePackageInstallation_ManualInstallModulation
#define hsvdvbspol_ins_GetCurrentInstallationState(mode,state)	hsvdvbspol_ins->GetCurrentInstallationState(mode,state)
#define hsvdvbspol_ins_StartInstallation(Source,Lnb,Mode)	hsvdvbspol_ins->StartInstallation(Source,Lnb,Mode)
#define hsvdvbspol_ins_StopInstallation()	hsvdvbspol_ins->StopInstallation()
#define hsvdvbspol_ins_WriteBarkerMuxData()	hsvdvbspol_ins->WriteBarkerMuxData()
#define hsvdvbspol_ins_GetNumberOfTvChannelsFound(Mode,Lnb)	hsvdvbspol_ins->GetNumberOfTvChannelsFound(Mode,Lnb)
#define hsvdvbspol_ins_GetNumberofRadioChannelsFound(Mode,Lnb)	hsvdvbspol_ins->GetNumberofRadioChannelsFound(Mode,Lnb)
#define hsvdvbspol_ins_GetNumberOfTvChannelsRemoved(Mode,Lnb)	hsvdvbspol_ins->GetNumberOfTvChannelsRemoved(Mode,Lnb)
#define hsvdvbspol_ins_GetNumberofRadioChannelsRemoved(Mode,Lnb)	hsvdvbspol_ins->GetNumberofRadioChannelsRemoved(Mode,Lnb)
#define hsvdvbspol_ins_GetNumberOfDigitalChannelsAdded()	hsvdvbspol_ins->GetNumberOfDigitalChannelsAdded()
#define hsvdvbspol_ins_GetNumberOfDigitalChannelsRemoved()	hsvdvbspol_ins->GetNumberOfDigitalChannelsRemoved()
#define hsvdvbspol_ins_GetNumberOfDigitalChannelsMoved()	hsvdvbspol_ins->GetNumberOfDigitalChannelsMoved()
#define hsvdvbspol_ins_LoadManualInstallationDefaultValues()	hsvdvbspol_ins->LoadManualInstallationDefaultValues()
#define hsvdvbspol_ins_StoreManualInstallationValues()	hsvdvbspol_ins->StoreManualInstallationValues()
#define hsvdvbspol_ins_SetManualInstallationAttributes(AttributeId,Value)	hsvdvbspol_ins->SetManualInstallationAttributes(AttributeId,Value)
#define hsvdvbspol_ins_GetAttribute(Mode,AttributeId)	hsvdvbspol_ins->GetAttribute(Mode,AttributeId)
#define hsvdvbspol_ins_GetScanProgressStatus(Mode)	hsvdvbspol_ins->GetScanProgressStatus(Mode)
#define hsvdvbspol_ins_GetSIDetails(SiValues)	hsvdvbspol_ins->GetSIDetails(SiValues)
#define hsvdvbspol_plfApidvbsN_iPresent() (hsvdvbspol_plfApidvbsN.Present())
#define hsvdvbspol_plfApidvbsN_OnLockChanged(LockState)	hsvdvbspol_plfApidvbsN->OnLockChanged(LockState)
#define hsvdvbspol_plfApidvbsN_OnBlindScanEnd()	hsvdvbspol_plfApidvbsN->OnBlindScanEnd()
#define hsvdvbspol_pow_iPresent() (hsvdvbspol_pow.Present())
#define hsvdvbspol_pow_Init()	hsvdvbspol_pow->Init()
#define hsvdvbspol_pow_TurnOn()	hsvdvbspol_pow->TurnOn()
#define hsvdvbspol_pow_TurnOff()	hsvdvbspol_pow->TurnOff()
#define hsvdvbspol_sort_iPresent() (hsvdvbspol_sort.Present())
#define hsvdvbspol_sort_Sort(PackageIndex)	hsvdvbspol_sort->Sort(PackageIndex)
#define hsvdvbsrussia_ctrlN_iPresent() (hsvdvbsrussia_ctrlN.Present())
#define hsvdvbsrussia_ctrlN_DataNotAvailable	IHsvSdmControlNotifyEx_DataNotAvailable
#define hsvdvbsrussia_ctrlN_OnlyPsiDataAvailable	IHsvSdmControlNotifyEx_OnlyPsiDataAvailable
#define hsvdvbsrussia_ctrlN_SiDataAvailable	IHsvSdmControlNotifyEx_SiDataAvailable
#define hsvdvbsrussia_ctrlN_StartedCollection	IHsvSdmControlNotifyEx_StartedCollection
#define hsvdvbsrussia_ctrlN_StoppedCollection	IHsvSdmControlNotifyEx_StoppedCollection
#define hsvdvbsrussia_ctrlN_DataAvailable	IHsvSdmControlNotifyEx_DataAvailable
#define hsvdvbsrussia_ctrlN_SDT	IHsvSdmControlNotifyEx_SDT
#define hsvdvbsrussia_ctrlN_NIT	IHsvSdmControlNotifyEx_NIT
#define hsvdvbsrussia_ctrlN_EIT	IHsvSdmControlNotifyEx_EIT
#define hsvdvbsrussia_ctrlN_TOT	IHsvSdmControlNotifyEx_TOT
#define hsvdvbsrussia_ctrlN_TDT	IHsvSdmControlNotifyEx_TDT
#define hsvdvbsrussia_ctrlN_PMT	IHsvSdmControlNotifyEx_PMT
#define hsvdvbsrussia_ctrlN_PAT	IHsvSdmControlNotifyEx_PAT
#define hsvdvbsrussia_ctrlN_CAT	IHsvSdmControlNotifyEx_CAT
#define hsvdvbsrussia_ctrlN_UNT	IHsvSdmControlNotifyEx_UNT
#define hsvdvbsrussia_ctrlN_SIMPLEPAT	IHsvSdmControlNotifyEx_SIMPLEPAT
#define hsvdvbsrussia_ctrlN_SIMPLEPMT	IHsvSdmControlNotifyEx_SIMPLEPMT
#define hsvdvbsrussia_ctrlN_BAT	IHsvSdmControlNotifyEx_BAT
#define hsvdvbsrussia_ctrlN_FNT	IHsvSdmControlNotifyEx_FNT
#define hsvdvbsrussia_ctrlN_FST	IHsvSdmControlNotifyEx_FST
#define hsvdvbsrussia_ctrlN_OnEvent(dmx,eventid,value)	hsvdvbsrussia_ctrlN->OnEvent(dmx,eventid,value)
#define hsvdvbsrussia_ins_iPresent() (hsvdvbsrussia_ins.Present())
#define hsvdvbsrussia_ins_ManualInstallLnb	IHsvSatellitePackageInstallation_ManualInstallLnb
#define hsvdvbsrussia_ins_ManualInstallFreq	IHsvSatellitePackageInstallation_ManualInstallFreq
#define hsvdvbsrussia_ins_ManualInstallPolaraization	IHsvSatellitePackageInstallation_ManualInstallPolaraization
#define hsvdvbsrussia_ins_ManualInstallSymRate	IHsvSatellitePackageInstallation_ManualInstallSymRate
#define hsvdvbsrussia_ins_ManualInstallSymRateMode	IHsvSatellitePackageInstallation_ManualInstallSymRateMode
#define hsvdvbsrussia_ins_ManualInstallModulation	IHsvSatellitePackageInstallation_ManualInstallModulation
#define hsvdvbsrussia_ins_GetCurrentInstallationState(mode,state)	hsvdvbsrussia_ins->GetCurrentInstallationState(mode,state)
#define hsvdvbsrussia_ins_StartInstallation(Source,Lnb,Mode)	hsvdvbsrussia_ins->StartInstallation(Source,Lnb,Mode)
#define hsvdvbsrussia_ins_StopInstallation()	hsvdvbsrussia_ins->StopInstallation()
#define hsvdvbsrussia_ins_WriteBarkerMuxData()	hsvdvbsrussia_ins->WriteBarkerMuxData()
#define hsvdvbsrussia_ins_GetNumberOfTvChannelsFound(Mode,Lnb)	hsvdvbsrussia_ins->GetNumberOfTvChannelsFound(Mode,Lnb)
#define hsvdvbsrussia_ins_GetNumberofRadioChannelsFound(Mode,Lnb)	hsvdvbsrussia_ins->GetNumberofRadioChannelsFound(Mode,Lnb)
#define hsvdvbsrussia_ins_GetNumberOfTvChannelsRemoved(Mode,Lnb)	hsvdvbsrussia_ins->GetNumberOfTvChannelsRemoved(Mode,Lnb)
#define hsvdvbsrussia_ins_GetNumberofRadioChannelsRemoved(Mode,Lnb)	hsvdvbsrussia_ins->GetNumberofRadioChannelsRemoved(Mode,Lnb)
#define hsvdvbsrussia_ins_GetNumberOfDigitalChannelsAdded()	hsvdvbsrussia_ins->GetNumberOfDigitalChannelsAdded()
#define hsvdvbsrussia_ins_GetNumberOfDigitalChannelsRemoved()	hsvdvbsrussia_ins->GetNumberOfDigitalChannelsRemoved()
#define hsvdvbsrussia_ins_GetNumberOfDigitalChannelsMoved()	hsvdvbsrussia_ins->GetNumberOfDigitalChannelsMoved()
#define hsvdvbsrussia_ins_LoadManualInstallationDefaultValues()	hsvdvbsrussia_ins->LoadManualInstallationDefaultValues()
#define hsvdvbsrussia_ins_StoreManualInstallationValues()	hsvdvbsrussia_ins->StoreManualInstallationValues()
#define hsvdvbsrussia_ins_SetManualInstallationAttributes(AttributeId,Value)	hsvdvbsrussia_ins->SetManualInstallationAttributes(AttributeId,Value)
#define hsvdvbsrussia_ins_GetAttribute(Mode,AttributeId)	hsvdvbsrussia_ins->GetAttribute(Mode,AttributeId)
#define hsvdvbsrussia_ins_GetScanProgressStatus(Mode)	hsvdvbsrussia_ins->GetScanProgressStatus(Mode)
#define hsvdvbsrussia_ins_GetSIDetails(SiValues)	hsvdvbsrussia_ins->GetSIDetails(SiValues)
#define hsvdvbsrussia_plfApidvbsN_iPresent() (hsvdvbsrussia_plfApidvbsN.Present())
#define hsvdvbsrussia_plfApidvbsN_OnLockChanged(LockState)	hsvdvbsrussia_plfApidvbsN->OnLockChanged(LockState)
#define hsvdvbsrussia_plfApidvbsN_OnBlindScanEnd()	hsvdvbsrussia_plfApidvbsN->OnBlindScanEnd()
#define hsvdvbsrussia_pow_iPresent() (hsvdvbsrussia_pow.Present())
#define hsvdvbsrussia_pow_Init()	hsvdvbsrussia_pow->Init()
#define hsvdvbsrussia_pow_TurnOn()	hsvdvbsrussia_pow->TurnOn()
#define hsvdvbsrussia_pow_TurnOff()	hsvdvbsrussia_pow->TurnOff()
#define hsvdvbsrussia_sort_iPresent() (hsvdvbsrussia_sort.Present())
#define hsvdvbsrussia_sort_Sort(PackageIndex)	hsvdvbsrussia_sort->Sort(PackageIndex)

#define hsvdvbstricolor_ctrlN_iPresent() (hsvdvbstricolor_ctrlN.Present())
#define hsvdvbstricolor_ctrlN_DataNotAvailable	IHsvSdmControlNotifyEx_DataNotAvailable
#define hsvdvbstricolor_ctrlN_OnlyPsiDataAvailable	IHsvSdmControlNotifyEx_OnlyPsiDataAvailable
#define hsvdvbstricolor_ctrlN_SiDataAvailable	IHsvSdmControlNotifyEx_SiDataAvailable
#define hsvdvbstricolor_ctrlN_StartedCollection	IHsvSdmControlNotifyEx_StartedCollection
#define hsvdvbstricolor_ctrlN_StoppedCollection	IHsvSdmControlNotifyEx_StoppedCollection
#define hsvdvbstricolor_ctrlN_DataAvailable	IHsvSdmControlNotifyEx_DataAvailable
#define hsvdvbstricolor_ctrlN_SDT	IHsvSdmControlNotifyEx_SDT
#define hsvdvbstricolor_ctrlN_NIT	IHsvSdmControlNotifyEx_NIT
#define hsvdvbstricolor_ctrlN_EIT	IHsvSdmControlNotifyEx_EIT
#define hsvdvbstricolor_ctrlN_TOT	IHsvSdmControlNotifyEx_TOT
#define hsvdvbstricolor_ctrlN_TDT	IHsvSdmControlNotifyEx_TDT
#define hsvdvbstricolor_ctrlN_PMT	IHsvSdmControlNotifyEx_PMT
#define hsvdvbstricolor_ctrlN_PAT	IHsvSdmControlNotifyEx_PAT
#define hsvdvbstricolor_ctrlN_CAT	IHsvSdmControlNotifyEx_CAT
#define hsvdvbstricolor_ctrlN_UNT	IHsvSdmControlNotifyEx_UNT
#define hsvdvbstricolor_ctrlN_SIMPLEPAT	IHsvSdmControlNotifyEx_SIMPLEPAT
#define hsvdvbstricolor_ctrlN_SIMPLEPMT	IHsvSdmControlNotifyEx_SIMPLEPMT
#define hsvdvbstricolor_ctrlN_BAT	IHsvSdmControlNotifyEx_BAT
#define hsvdvbstricolor_ctrlN_FNT	IHsvSdmControlNotifyEx_FNT
#define hsvdvbstricolor_ctrlN_FST	IHsvSdmControlNotifyEx_FST
#define hsvdvbstricolor_ctrlN_OnEvent(dmx,eventid,value)	hsvdvbstricolor_ctrlN->OnEvent(dmx,eventid,value)
#define hsvdvbstricolor_ins_iPresent() (hsvdvbstricolor.Present())
#define hsvdvbstricolor_ins_ManualInstallLnb	IHsvSatellitePackageInstallation_ManualInstallLnb
#define hsvdvbstricolor_ins_ManualInstallFreq	IHsvSatellitePackageInstallation_ManualInstallFreq
#define hsvdvbstricolor_ins_ManualInstallPolaraization	IHsvSatellitePackageInstallation_ManualInstallPolaraization
#define hsvdvbstricolor_ins_ManualInstallSymRate	IHsvSatellitePackageInstallation_ManualInstallSymRate
#define hsvdvbstricolor_ins_ManualInstallSymRateMode	IHsvSatellitePackageInstallation_ManualInstallSymRateMode
#define hsvdvbstricolor_ins_ManualInstallModulation	IHsvSatellitePackageInstallation_ManualInstallModulation
#define hsvdvbstricolor_ins_GetCurrentInstallationState(mode,state)	hsvdvbstricolor_ins->GetCurrentInstallationState(mode,state)
#define hsvdvbstricolor_ins_StartInstallation(Source,Lnb,Mode)	hsvdvbstricolor_ins->StartInstallation(Source,Lnb,Mode)
#define hsvdvbstricolor_ins_StopInstallation()	hsvdvbstricolor_ins->StopInstallation()
#define hsvdvbstricolor_ins_WriteBarkerMuxData()	hsvdvbstricolor_ins->WriteBarkerMuxData()
#define hsvdvbstricolor_ins_GetNumberOfTvChannelsFound(Mode,Lnb)	hsvdvbstricolor_ins->GetNumberOfTvChannelsFound(Mode,Lnb)
#define hsvdvbstricolor_ins_GetNumberofRadioChannelsFound(Mode,Lnb)	hsvdvbstricolor_ins->GetNumberofRadioChannelsFound(Mode,Lnb)
#define hsvdvbstricolor_ins_GetNumberOfTvChannelsRemoved(Mode,Lnb)	hsvdvbstricolor_ins->GetNumberOfTvChannelsRemoved(Mode,Lnb)
#define hsvdvbstricolor_ins_GetNumberofRadioChannelsRemoved(Mode,Lnb)	hsvdvbstricolor_ins->GetNumberofRadioChannelsRemoved(Mode,Lnb)
#define hsvdvbstricolor_ins_GetNumberOfDigitalChannelsAdded()	hsvdvbstricolor_ins->GetNumberOfDigitalChannelsAdded()
#define hsvdvbstricolor_ins_GetNumberOfDigitalChannelsRemoved()	hsvdvbstricolor_ins->GetNumberOfDigitalChannelsRemoved()
#define hsvdvbstricolor_ins_GetNumberOfDigitalChannelsMoved()	hsvdvbstricolor_ins->GetNumberOfDigitalChannelsMoved()
#define hsvdvbstricolor_ins_LoadManualInstallationDefaultValues()	hsvdvbstricolor_ins->LoadManualInstallationDefaultValues()
#define hsvdvbstricolor_ins_StoreManualInstallationValues()	hsvdvbstricolor_ins->StoreManualInstallationValues()
#define hsvdvbstricolor_ins_SetManualInstallationAttributes(AttributeId,Value)	hsvdvbstricolor_ins->SetManualInstallationAttributes(AttributeId,Value)
#define hsvdvbstricolor_ins_GetAttribute(Mode,AttributeId)	hsvdvbstricolor_ins->GetAttribute(Mode,AttributeId)
#define hsvdvbstricolor_ins_GetScanProgressStatus(Mode)	hsvdvbstricolor_ins->GetScanProgressStatus(Mode)
#define hsvdvbstricolor_ins_GetSIDetails(SiValues)	hsvdvbstricolor_ins->GetSIDetails(SiValues)
#define hsvdvbstricolor_ins_StartTricolorRegionParsing()	hsvdvbstricolor_ins->StartTricolorRegionParsing()
#define hsvdvbstricolor_ins_SetTricolorRegionIndex(indx)	hsvdvbstricolor_ins->SetTricolorRegionIndex(indx)
#define hsvdvbstricolor_ins_GetTricolorRegionNames(names,len)	hsvdvbstricolor_ins->GetTricolorRegionNames(names,len)


#define hsvdvbstricolor_plfApidvbsN_iPresent() (hsvdvbstricolor_plfApidvbsN.Present())
#define hsvdvbstricolor_plfApidvbsN_OnLockChanged(LockState)	hsvdvbstricolor_plfApidvbsN->OnLockChanged(LockState)
#define hsvdvbstricolor_plfApidvbsN_OnBlindScanEnd()	hsvdvbstricolor_plfApidvbsN->OnBlindScanEnd()
#define hsvdvbstricolor_pow_iPresent() (hsvdvbstricolor_pow.Present())
#define hsvdvbstricolor_pow_Init()	hsvdvbstricolor_pow->Init()
#define hsvdvbstricolor_pow_TurnOn()	hsvdvbstricolor_pow->TurnOn()
#define hsvdvbstricolor_pow_TurnOff()	hsvdvbstricolor_pow->TurnOff()
#define hsvdvbstricolor_sort_iPresent() (hsvdvbstricolor_sort.Present())
#define hsvdvbstricolor_sort_Sort(PackageIndex)	hsvdvbstricolor_sort->Sort(PackageIndex)
#define hsvdvbstricolor_strapiN_iPresent() (hsvdvbstricolor_strapiN.Present())
#define hsvdvbstricolor_strapiN_OnCompleted(dest,spid)	hsvdvbstricolor_strapiN->OnCompleted(dest,spid)
#define hsvdvbstricolor_strapiN_OnAdded(dest,spid,key1,key2,key3)	hsvdvbstricolor_strapiN->OnAdded(dest,spid,key1,key2,key3)
#define hsvdvbstricolor_strapiN_OnChanged(dest,spid,key1,key2,key3,eventid)	hsvdvbstricolor_strapiN->OnChanged(dest,spid,key1,key2,key3,eventid)
#define hsvdvbstricolor_strapiN_OnRemoved(dest,spid,key1,key2,key3)	hsvdvbstricolor_strapiN->OnRemoved(dest,spid,key1,key2,key3)


#define ipackage_iPresent() (ipackage.Present())
#define ipackage_IdentifyPackagesAvailable()	ipackage->IdentifyPackagesAvailable()
#define ipackage_GetNumberOfPackages()	ipackage->GetNumberOfPackages()
#define ipackage_GetPackageByIndex(Index,Package)	ipackage->GetPackageByIndex(Index,Package)
#define ipackage_GetPackageByKey(Package)	ipackage->GetPackageByKey(Package)
#define ipackage_GetPackageGroupId(PackageID,PackageGroupId)	ipackage->GetPackageGroupId(PackageID,PackageGroupId)
#define ipackage_GetPackageGroupName(PackageGroupId,PackageGroupName)	ipackage->GetPackageGroupName(PackageGroupId,PackageGroupName)
#define ipackage_LoadPackageGroupInfo()	ipackage->LoadPackageGroupInfo()
#define ipackage_StartPackageParsing()	ipackage->StartPackageParsing()
#define ipackage_StopPackageParsing()	ipackage->StopPackageParsing()
#define ipackage_SetPackageParserXmlString(InputString,PackageParserXmlStringLen)	ipackage->SetPackageParserXmlString(InputString,PackageParserXmlStringLen)
#define pins_iPresent() (pins.Present())
#define pins_InstallationNone	IHsvSatelliteInstallation_InstallationNone
#define pins_InstallationPreScan	IHsvSatelliteInstallation_InstallationPreScan
#define pins_InstallationServiceScan	IHsvSatelliteInstallation_InstallationServiceScan
#define pins_InstallationUpdate	IHsvSatelliteInstallation_InstallationUpdate
#define pins_InstallationManual	IHsvSatelliteInstallation_InstallationManual
#define pins_InstallationAddSatellite	IHsvSatelliteInstallation_InstallationAddSatellite
#define pins_InstallationAutomaticUpdate	IHsvSatelliteInstallation_InstallationAutomaticUpdate
#define pins_InstallationBackground	IHsvSatelliteInstallation_InstallationBackground
#define pins_InstallationMiniPrecan	IHsvSatelliteInstallation_InstallationMiniPrecan
#define pins_InstallationBackgroundUpdate	IHsvSatelliteInstallation_InstallationBackgroundUpdate
#define pins_InstallationPackageParsing	IHsvSatelliteInstallation_InstallationPackageParsing
#define pins_InstallationStateIdle	IHsvSatelliteInstallation_InstallationStateIdle
#define pins_InstallationStateRegionScan	IHsvSatelliteInstallation_InstallationStateRegionScan
#define pins_InstallationStateInProgress	IHsvSatelliteInstallation_InstallationStateInProgress
#define pins_InstallationStateSorting	IHsvSatelliteInstallation_InstallationStateSorting
#define pins_AttributePackageId	IHsvSatelliteInstallation_AttributePackageId
#define pins_AttributePackageOnly	IHsvSatelliteInstallation_AttributePackageOnly
#define pins_AttributePackageGroup	IHsvSatelliteInstallation_AttributePackageGroup
#define pins_AttributeAssetManager	IHsvSatelliteInstallation_AttributeAssetManager
#define pins_ManualInstallLnb	IHsvSatelliteInstallation_ManualInstallLnb
#define pins_ManualInstallFreq	IHsvSatelliteInstallation_ManualInstallFreq
#define pins_ManualInstallPolaraization	IHsvSatelliteInstallation_ManualInstallPolaraization
#define pins_ManualInstallSymRate	IHsvSatelliteInstallation_ManualInstallSymRate
#define pins_ManualInstallSymRateMode	IHsvSatelliteInstallation_ManualInstallSymRateMode
#define pins_ManualInstallModulation	IHsvSatelliteInstallation_ManualInstallModulation
#define pins_SatLnb1	IHsvSatelliteInstallation_SatLnb1
#define pins_SatLnb2	IHsvSatelliteInstallation_SatLnb2
#define pins_SatLnb3	IHsvSatelliteInstallation_SatLnb3
#define pins_SatLnb4	IHsvSatelliteInstallation_SatLnb4
#define pins_GetCurrentInstallationState(mode,state)	pins->GetCurrentInstallationState(mode,state)
#define pins_StartInstallation(Source,Lnb,Mode)	pins->StartInstallation(Source,Lnb,Mode)
#define pins_StopInstallation()	pins->StopInstallation()
#define pins_ResetInstallation()	pins->ResetInstallation()
#define pins_GetNumberOfTvChannelsFound(Lnb)	pins->GetNumberOfTvChannelsFound(Lnb)
#define pins_GetNumberofRadioChannelsFound(Lnb)	pins->GetNumberofRadioChannelsFound(Lnb)
#define pins_GetNumberOfTvChannelsRemoved(Lnb)	pins->GetNumberOfTvChannelsRemoved(Lnb)
#define pins_GetNumberofRadioChannelsRemoved(Lnb)	pins->GetNumberofRadioChannelsRemoved(Lnb)
#define pins_GetSatelliteName(Lnb,SatelliteName)	pins->GetSatelliteName(Lnb,SatelliteName)
#define pins_GetNumberOfDigitalChannelsAdded()	pins->GetNumberOfDigitalChannelsAdded()
#define pins_GetNumberOfDigitalChannelsRemoved()	pins->GetNumberOfDigitalChannelsRemoved()
#define pins_GetNumberOfDigitalChannelsMoved()	pins->GetNumberOfDigitalChannelsMoved()
#define pins_IdentifyPackagesAvailable()	pins->IdentifyPackagesAvailable()
#define pins_GetTotalNumberOfPackagesFound()	pins->GetTotalNumberOfPackagesFound()
#define pins_GetPackageByIndex(Index,Package)	pins->GetPackageByIndex(Index,Package)
#define pins_SetUserPackageIndex(PackageIndex)	pins->SetUserPackageIndex(PackageIndex)
#define pins_GetUserPackageIndex(PackageIndex,IsPackage)	pins->GetUserPackageIndex(PackageIndex,IsPackage)
#define pins_GetInstalledSatellites(mode,SatelliteEntries)	pins->GetInstalledSatellites(mode,SatelliteEntries)
#define pins_InstallAddedSatellites()	pins->InstallAddedSatellites()
#define pins_ResetAddedSatellites()	pins->ResetAddedSatellites()
#define pins_RemoveSatelliteEntry(LnbNumber)	pins->RemoveSatelliteEntry(LnbNumber)
#define pins_GetSatelliteSignalStrength(LnbNumber)	pins->GetSatelliteSignalStrength(LnbNumber)
#define pins_GetSatelliteSignalQuality(LnbNumber)	pins->GetSatelliteSignalQuality(LnbNumber)
#define pins_LoadManualInstallationDefaultValues()	pins->LoadManualInstallationDefaultValues()
#define pins_StoreManualInstallationValues()	pins->StoreManualInstallationValues()
#define pins_GetAttribute(Mode,AttributeId)	pins->GetAttribute(Mode,AttributeId)
#define pins_SetAttribute(Mode,AttributeId,Value)	pins->SetAttribute(Mode,AttributeId,Value)
#define pins_GetScanProgressStatus(Mode)	pins->GetScanProgressStatus(Mode)
#define pins_GetSITableIds(NetworkID,BouquetID)	pins->GetSITableIds(NetworkID,BouquetID)
#define pins_GetPackageName(PackageId,PackageName)	pins->GetPackageName(PackageId,PackageName)
#define pins_GetSIDetails(SiValues)	pins->GetSIDetails(SiValues)
#define pins_EnableUnicable(LnbNumber,Enable)	pins->EnableUnicable(LnbNumber,Enable)
#define pins_StopSignalStrengthMeas(LnbNumber)	pins->StopSignalStrengthMeas(LnbNumber)
#define pins_GetSignalQuality(Param)	pins->GetSignalQuality(Param)
#define pins_StartSignalStrengthMeas(LnbNumber)	pins->StartSignalStrengthMeas(LnbNumber)
#define pins_GetSignalStrength(param)	pins->GetSignalStrength(param)
#define pins_StartPredefinedListCopy()	pins->StartPredefinedListCopy()
#define pins_GetFirstInstalledChannel()	pins->GetFirstInstalledChannel()
#define pins_UpdateConfigXmlStrings(PrescanXmlString,PrescanXmlStringLen,SatellitePackageXmlString,SatellitePackageXmlStringLen)	pins->UpdateConfigXmlStrings(PrescanXmlString,PrescanXmlStringLen,SatellitePackageXmlString,SatellitePackageXmlStringLen)
#define ibckctrlN_DataNotAvailable	IHsvSdmControlNotifyEx_DataNotAvailable
#define ibckctrlN_OnlyPsiDataAvailable	IHsvSdmControlNotifyEx_OnlyPsiDataAvailable
#define ibckctrlN_SiDataAvailable	IHsvSdmControlNotifyEx_SiDataAvailable
#define ibckctrlN_StartedCollection	IHsvSdmControlNotifyEx_StartedCollection
#define ibckctrlN_StoppedCollection	IHsvSdmControlNotifyEx_StoppedCollection
#define ibckctrlN_DataAvailable	IHsvSdmControlNotifyEx_DataAvailable
#define ibckctrlN_SDT	IHsvSdmControlNotifyEx_SDT
#define ibckctrlN_NIT	IHsvSdmControlNotifyEx_NIT
#define ibckctrlN_EIT	IHsvSdmControlNotifyEx_EIT
#define ibckctrlN_TOT	IHsvSdmControlNotifyEx_TOT
#define ibckctrlN_TDT	IHsvSdmControlNotifyEx_TDT
#define ibckctrlN_PMT	IHsvSdmControlNotifyEx_PMT
#define ibckctrlN_PAT	IHsvSdmControlNotifyEx_PAT
#define ibckctrlN_CAT	IHsvSdmControlNotifyEx_CAT
#define ibckctrlN_UNT	IHsvSdmControlNotifyEx_UNT
#define ibckctrlN_SIMPLEPAT	IHsvSdmControlNotifyEx_SIMPLEPAT
#define ibckctrlN_SIMPLEPMT	IHsvSdmControlNotifyEx_SIMPLEPMT
#define ibckctrlN_BAT	IHsvSdmControlNotifyEx_BAT
#define ibckctrlN_FNT	IHsvSdmControlNotifyEx_FNT
#define ibckctrlN_FST	IHsvSdmControlNotifyEx_FST
#define ipackagectrlN_DataNotAvailable	IHsvSdmControlNotifyEx_DataNotAvailable
#define ipackagectrlN_OnlyPsiDataAvailable	IHsvSdmControlNotifyEx_OnlyPsiDataAvailable
#define ipackagectrlN_SiDataAvailable	IHsvSdmControlNotifyEx_SiDataAvailable
#define ipackagectrlN_StartedCollection	IHsvSdmControlNotifyEx_StartedCollection
#define ipackagectrlN_StoppedCollection	IHsvSdmControlNotifyEx_StoppedCollection
#define ipackagectrlN_DataAvailable	IHsvSdmControlNotifyEx_DataAvailable
#define ipackagectrlN_SDT	IHsvSdmControlNotifyEx_SDT
#define ipackagectrlN_NIT	IHsvSdmControlNotifyEx_NIT
#define ipackagectrlN_EIT	IHsvSdmControlNotifyEx_EIT
#define ipackagectrlN_TOT	IHsvSdmControlNotifyEx_TOT
#define ipackagectrlN_TDT	IHsvSdmControlNotifyEx_TDT
#define ipackagectrlN_PMT	IHsvSdmControlNotifyEx_PMT
#define ipackagectrlN_PAT	IHsvSdmControlNotifyEx_PAT
#define ipackagectrlN_CAT	IHsvSdmControlNotifyEx_CAT
#define ipackagectrlN_UNT	IHsvSdmControlNotifyEx_UNT
#define ipackagectrlN_SIMPLEPAT	IHsvSdmControlNotifyEx_SIMPLEPAT
#define ipackagectrlN_SIMPLEPMT	IHsvSdmControlNotifyEx_SIMPLEPMT
#define ipackagectrlN_BAT	IHsvSdmControlNotifyEx_BAT
#define ipackagectrlN_FNT	IHsvSdmControlNotifyEx_FNT
#define ipackagectrlN_FST	IHsvSdmControlNotifyEx_FST
#define ipackageins_ManualInstallLnb	IHsvSatellitePackageInstallation_ManualInstallLnb
#define ipackageins_ManualInstallFreq	IHsvSatellitePackageInstallation_ManualInstallFreq
#define ipackageins_ManualInstallPolaraization	IHsvSatellitePackageInstallation_ManualInstallPolaraization
#define ipackageins_ManualInstallSymRate	IHsvSatellitePackageInstallation_ManualInstallSymRate
#define ipackageins_ManualInstallSymRateMode	IHsvSatellitePackageInstallation_ManualInstallSymRateMode
#define ipackageins_ManualInstallModulation	IHsvSatellitePackageInstallation_ManualInstallModulation
#define ipackageroute_generic	IHsvPackageRoute_generic
#define ipackageroute_m7	IHsvPackageRoute_m7
#define ipackageroute_canal	IHsvPackageRoute_canal
#define ipackageroute_pol	IHsvPackageRoute_pol
#define ipackageroute_russia	IHsvPackageRoute_russia
#define ipackageroute_turk	IHsvPackageRoute_turk
#define ipackageroute_n	IHsvPackageRoute_n
#define ipackageroute_fransat	IHsvPackageRoute_fransat
#define hsvdvbsastra_ctrlN_OnEvent(dmx,eventid,value)	hsvdvbsastra_ctrlN->OnEvent(dmx,eventid,value)
#define hsvdvbsastra_ins_iPresent() (hsvdvbsastra_ins.Present())
#define hsvdvbsastra_ins_ManualInstallLnb	IHsvSatellitePackageInstallation_ManualInstallLnb
#define hsvdvbsastra_ins_ManualInstallFreq	IHsvSatellitePackageInstallation_ManualInstallFreq
#define hsvdvbsastra_ins_ManualInstallPolaraization	IHsvSatellitePackageInstallation_ManualInstallPolaraization
#define hsvdvbsastra_ins_ManualInstallSymRate	IHsvSatellitePackageInstallation_ManualInstallSymRate
#define hsvdvbsastra_ins_ManualInstallSymRateMode	IHsvSatellitePackageInstallation_ManualInstallSymRateMode
#define hsvdvbsastra_ins_ManualInstallModulation	IHsvSatellitePackageInstallation_ManualInstallModulation
#define hsvdvbsastra_ins_GetCurrentInstallationState(mode,state)	hsvdvbsastra_ins->GetCurrentInstallationState(mode,state)
#define hsvdvbsastra_ins_StartInstallation(Source,Lnb,Mode)	hsvdvbsastra_ins->StartInstallation(Source,Lnb,Mode)
#define hsvdvbsastra_ins_StopInstallation()	hsvdvbsastra_ins->StopInstallation()
#define hsvdvbsastra_ins_WriteBarkerMuxData()	hsvdvbsastra_ins->WriteBarkerMuxData()
#define hsvdvbsastra_ins_GetNumberOfTvChannelsFound(Mode,Lnb)	hsvdvbsastra_ins->GetNumberOfTvChannelsFound(Mode,Lnb)
#define hsvdvbsastra_ins_GetNumberofRadioChannelsFound(Mode,Lnb)	hsvdvbsastra_ins->GetNumberofRadioChannelsFound(Mode,Lnb)
#define hsvdvbsastra_ins_GetNumberOfTvChannelsRemoved(Mode,Lnb)	hsvdvbsastra_ins->GetNumberOfTvChannelsRemoved(Mode,Lnb)
#define hsvdvbsastra_ins_GetNumberofRadioChannelsRemoved(Mode,Lnb)	hsvdvbsastra_ins->GetNumberofRadioChannelsRemoved(Mode,Lnb)
#define hsvdvbsastra_ins_GetNumberOfDigitalChannelsAdded()	hsvdvbsastra_ins->GetNumberOfDigitalChannelsAdded()
#define hsvdvbsastra_ins_GetNumberOfDigitalChannelsRemoved()	hsvdvbsastra_ins->GetNumberOfDigitalChannelsRemoved()
#define hsvdvbsastra_ins_GetNumberOfDigitalChannelsMoved()	hsvdvbsastra_ins->GetNumberOfDigitalChannelsMoved()
#define hsvdvbsastra_ins_LoadManualInstallationDefaultValues()	hsvdvbsastra_ins->LoadManualInstallationDefaultValues()
#define hsvdvbsastra_ins_StoreManualInstallationValues()	hsvdvbsastra_ins->StoreManualInstallationValues()
#define hsvdvbsastra_ins_SetManualInstallationAttributes(AttributeId,Value)	hsvdvbsastra_ins->SetManualInstallationAttributes(AttributeId,Value)
#define hsvdvbsastra_ins_GetAttribute(Mode,AttributeId)	hsvdvbsastra_ins->GetAttribute(Mode,AttributeId)
#define hsvdvbsastra_ins_GetScanProgressStatus(Mode)	hsvdvbsastra_ins->GetScanProgressStatus(Mode)
#define hsvdvbsastra_ins_GetSIDetails(SiValues)	hsvdvbsastra_ins->GetSIDetails(SiValues)
#define hsvdvbsastra_plfApidvbsN_iPresent() (hsvdvbsastra_plfApidvbsN.Present())
#define hsvdvbsastra_plfApidvbsN_OnLockChanged(LockState)	hsvdvbsastra_plfApidvbsN->OnLockChanged(LockState)
#define hsvdvbsastra_plfApidvbsN_OnBlindScanEnd()	hsvdvbsastra_plfApidvbsN->OnBlindScanEnd()
#define hsvdvbsastra_pow_iPresent() (hsvdvbsastra_pow.Present())
#define hsvdvbsastra_pow_Init()	hsvdvbsastra_pow->Init()
#define hsvdvbsastra_pow_TurnOn()	hsvdvbsastra_pow->TurnOn()
#define hsvdvbsastra_pow_TurnOff()	hsvdvbsastra_pow->TurnOff()
#define hsvdvbsastra_sort_iPresent() (hsvdvbsastra_sort.Present())
#define hsvdvbsastra_sort_Sort(PackageIndex)	hsvdvbsastra_sort->Sort(PackageIndex)
#define hsvdvbsastra_strapiN_iPresent() (hsvdvbsastra_strapiN.Present())
#define hsvdvbsastra_strapiN_OnCompleted(dest,spid)	hsvdvbsastra_strapiN->OnCompleted(dest,spid)
#define hsvdvbsastra_strapiN_OnAdded(dest,spid,key1,key2,key3)	hsvdvbsastra_strapiN->OnAdded(dest,spid,key1,key2,key3)
#define hsvdvbsastra_strapiN_OnChanged(dest,spid,key1,key2,key3,eventid)	hsvdvbsastra_strapiN->OnChanged(dest,spid,key1,key2,key3,eventid)
#define hsvdvbsastra_strapiN_OnRemoved(dest,spid,key1,key2,key3)	hsvdvbsastra_strapiN->OnRemoved(dest,spid,key1,key2,key3)
#define hsvdvbsastra_bckInstall_iPresent() (hsvdvbsastra_bckInstall.Present())
#define hsvdvbsastra_bckInstall_EnableBackgroundInstallation()	hsvdvbsastra_bckInstall->EnableBackgroundInstallation()
#define hsvdvbsastra_bckInstall_DisableBackgroundInstallation()	hsvdvbsastra_bckInstall->DisableBackgroundInstallation()


#else //GENERATE__LEGACY__DEFINES
#ifdef CLASSSCOPE
#undef CLASSSCOPE
#endif
#ifdef FPCALL
#undef FPCALL
#endif
#ifdef NOCLASS
#undef NOCLASS
#endif
#define LOCAL_UNDEFINES
#include "locals_mroute.h"
#undef LOCAL_UNDEFINES
#endif //GENERATE__LEGACY__DEFINES
#endif

